// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

SubSub := Rectangle {
    width: 30phx;
}

Sub := SubSub {}

TestCase := Rectangle {
    width: 300phx;
    height: 200phx;

    elem1 := Rectangle {
        elem2 := TouchArea {}
    }
    elem3 := Rectangle {
        height: 50%;
    }

    elem4 := Sub { }

    property <bool> elem1_ok: elem1.width == 300phx && elem1.height == 200phx;
    property <bool> elem2_ok: elem2.width == 300phx && elem2.height == 200phx;
    property <bool> elem3_ok: elem3.width == 300phx && elem3.height == 200phx / 2;
    property <bool> elem4_ok: elem4.width == 30phx && elem4.height == 200phx;

    property<bool> test: elem1_ok && elem2_ok && elem3_ok && elem4_ok;
}

/*

```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert(instance.get_elem1_ok());
assert(instance.get_elem2_ok());
assert(instance.get_elem3_ok());
assert(instance.get_elem4_ok());
```


```rust
let instance = TestCase::new().unwrap();
assert!(instance.get_elem1_ok());
assert!(instance.get_elem2_ok());
assert!(instance.get_elem3_ok());
assert!(instance.get_elem4_ok());
```

*/
