// Copyright © Klarälvdalens Datakonsult AB, a KDAB Group company, info@kdab.com, author David Faure <david.faure@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component TestCase inherits Window {
    default-font-size: 20px;
    width: 1000phx;
    height: 300phx;

    property <[{ name: string, colspan: int}]> model_with_colspan: [
        { name: "Jules", colspan: 1 },
        { name: "Emile", colspan: 2 },
        { name: "Charles", colspan: 1 },
    ];

    out property <string> clicked_text;
    out property <bool> clicked: false;

    VerticalLayout {
        Rectangle {
            GridLayout {
                padding-left: 10phx;
                padding-top: 20phx;
                header_row := Row {
                    Text {
                        colspan: 3;
                        text: "Click on one of the numbered cells";
                        height: 50phx;
                    }
                }

                Row {
                    for _ in 3: txt := Text {
                        width: 200phx;
                        height: 50phx;
                        text: txt.row + ", " + txt.col;
                        TouchArea {
                            clicked => {
                                clicked_text = txt.text;
                                clicked = true;
                            }
                        }
                    }
                }

                Row {
                    // Optional item at the beginning of a row, to test that we set new_row correctly
                    if clicked: optionalText := Text {
                        width: 200phx; // make sure column 0 doesn't grow larger
                        height: 50phx;
                        text: "Clicked!";
                        colspan: 2;
                    }
                    // This element exists to test whether the conditional Text above is created or absent (end.col changes accordingly)
                    end := Text {
                        text: "end is at row " + end.row + ", col " + end.col;
                    }
                }
            }
        }

        Rectangle {
            GridLayout {
                before1 := Text {
                    text: "Static1";
                }
                // This one will have new_row=false, and shouldn't use a new_row local variable in the generated code
                before2 := Text {
                    text: "Static2";
                }

                for entry in model_with_colspan: repeated := Text {
                    text: entry.name + " (" + entry.colspan + ")";
                    colspan: entry.colspan;
                }
                // This tests that a variable colspan (different between repeated items) works correctly
                after := Text {
                    text: "Static-After";
                }
            }
        }
    }

    out property <bool> before_cells_ok: before1.row == 0 && before1.col == 0 && before2.row == 0 && before2.col == 1;
    out property <bool> after_cell_ok: after.row == 0 && after.col == 6;
    out property <int> end_row: end.row;
    out property <bool> test: end.row == 2 && end.col == 0 && before_cells_ok && after_cell_ok;
    out property <bool> test_after_clicked: end.row == 2 && end.col == 2 && clicked && before_cells_ok && after_cell_ok;
}

/*

```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert(instance.get_test());
slint_testing::send_mouse_click(&instance, 10. + 5., 75.);
assert_eq(instance.get_clicked_text(), "1, 0");
assert(instance.get_test_after_clicked());
slint_testing::send_mouse_click(&instance, 10. + 200. + 5., 75.);
assert_eq(instance.get_clicked_text(), "1, 1");
slint_testing::send_mouse_click(&instance, 10. + 400. + 5., 75.);
assert_eq(instance.get_clicked_text(), "1, 2");
```


```rust
let instance = TestCase::new().unwrap();
assert!(instance.get_before_cells_ok());
assert!(instance.get_after_cell_ok());
assert_eq!(instance.get_end_row(), 2);
assert!(instance.get_test());
slint_testing::send_mouse_click(&instance, 10. + 5., 75.);
assert_eq!(instance.get_clicked_text(), "1, 0");
assert!(instance.get_test_after_clicked());
slint_testing::send_mouse_click(&instance, 10. + 200. + 5., 75.);
assert_eq!(instance.get_clicked_text(), "1, 1");
slint_testing::send_mouse_click(&instance, 10. + 400. + 5., 75.);
assert_eq!(instance.get_clicked_text(), "1, 2");

```

```js
var instance = new slint.TestCase();
assert(instance.test);
slintlib.private_api.send_mouse_click(instance, 10. + 5., 75.);
assert.deepEqual(instance.clicked_text, "1, 0");
assert(instance.test_after_clicked);
slintlib.private_api.send_mouse_click(instance, 10. + 200. + 5., 75.);
assert.deepEqual(instance.clicked_text, "1, 1");
slintlib.private_api.send_mouse_click(instance, 10. + 400. + 5., 75.);
assert.deepEqual(instance.clicked_text, "1, 2");
```

*/
