// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// Test the propagation of maximum and minimum size through nested grid layouts

export component TestCase inherits Rectangle {
    min-width: 500px;
    max-width: root.min-width;

    in-out property xxx <=> root.preferred-height;
    HorizontalLayout {
        Rectangle { height: 88px; }
    }

    in-out property <bool> test: root.min-width == 500px && root.max-width == 500px && root.xxx == 88px;
}

/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert(instance.get_test());
```

```rust
let instance = TestCase::new().unwrap();
assert!(instance.get_test());
```

```js
var instance = new slint.TestCase({});
assert(instance.test);
```
*/
