// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

TestCase := Window {
    width: 500px;
    height: 550px;
    background: #ecedeb;

    property<[int]> xs: [1, 2, 3];

    VerticalLayout {
        padding: 0px;
        spacing: 0px;
        alignment: start;

        for x_[i] in xs: Rectangle {
            background: i == 0 ? red : i == 1 ? green : blue;
            height: 100px;
            VerticalLayout {
                padding: 1px;
                TouchArea {
                    clicked => { last_clicked = x_; }
                }
            }
        }

        for x_[i] in xs: Rectangle {
            background: i == 0 ? red : i == 1 ? green : blue;
            min-height: 50px;
            HorizontalLayout {
                padding: 1px;
                TouchArea {
                    clicked => { last_clicked = 10 + x_; }
                }
            }
        }
    }

    property<int> last_clicked;
}
/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;

// aim at the padding
slint_testing::send_mouse_click(&instance, 5., 100.);
assert_eq(instance.get_last_clicked(), 0);

slint_testing::send_mouse_click(&instance, 5., 455.);
assert_eq(instance.get_last_clicked(), 0);
slint_testing::send_mouse_click(&instance, 5., 305.);
assert_eq(instance.get_last_clicked(), 11);
slint_testing::send_mouse_click(&instance, 5., 295.);
assert_eq(instance.get_last_clicked(), 3);
slint_testing::send_mouse_click(&instance, 5., 95.);
assert_eq(instance.get_last_clicked(), 1);
```


```rust
let instance = TestCase::new().unwrap();

// aim at the padding
slint_testing::send_mouse_click(&instance, 5., 100.);
assert_eq!(instance.get_last_clicked(), 0);


slint_testing::send_mouse_click(&instance, 5., 455.);
assert_eq!(instance.get_last_clicked(), 0);
slint_testing::send_mouse_click(&instance, 5., 305.);
assert_eq!(instance.get_last_clicked(), 11);
slint_testing::send_mouse_click(&instance, 5., 295.);
assert_eq!(instance.get_last_clicked(), 3);
slint_testing::send_mouse_click(&instance, 5., 95.);
assert_eq!(instance.get_last_clicked(), 1);
```

```js
var instance = new slint.TestCase();

// aim at the padding
instance.send_mouse_click(5., 100.);
assert.equal(instance.last_clicked, 0);


instance.send_mouse_click(5., 455.);
assert.equal(instance.last_clicked, 0);
instance.send_mouse_click(5., 305.);
assert.equal(instance.last_clicked, 11);
instance.send_mouse_click(5., 295.);
assert.equal(instance.last_clicked, 3);
instance.send_mouse_click(5., 95.);
assert.equal(instance.last_clicked, 1);
```
*/
