// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

export TestCase := Window {
    layout1 := VerticalLayout {
        if (true) : test1 := VerticalLayout {
            Rectangle { height: 55px; }
            opacity: 1;
        }
    }
    layout2 := HorizontalLayout {
        if (true) : test2 := Rectangle {
            inner := VerticalLayout { Rectangle { width: 88px; } }
            opacity: 1;
        }
    }

    layout3 := HorizontalLayout {
        for _ in 3 : Rectangle {
            width: 10px;
            opacity: 0.5;
        }
    }

    // issue #915
    layout4 := HorizontalLayout {
        height: 100px;
        for _ in 3 : the_image := Image {
            width: 10px;
            opacity: 0.5;
            source: @image-url("../../../logo/slint-logo-square-light-128x128.png");
        }
    }

    property <length> layout1_height : layout1.min-height;
    property <length> layout2_width : layout2.max-width;
    property <length> layout3_width : layout3.preferred-width;
    property <length> layout4_width : layout4.preferred-width;
    property<bool> test: layout1_height == 55px && layout2_width == 88px && layout3_width == 30px && layout4_width == 30px;
}
