// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial


// A Text that does not use word wrap's height should not depends on the width

TestCase := Rectangle {

    VerticalLayout {
        HorizontalLayout {
            Text {
                text: "Hello World";
            }
            square := Rectangle {
                width: height;
                background: violet;
            }
        }
        Rectangle {}
    }

    property <bool> test: square.width == square.height;
}
