// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

TestCase := Window {
    width: 400px;
    height: 640px;
    VerticalLayout {
        padding: 0px;
        alignment: center;
        text := Text {
            text: "This line needs to be broken into multiple lines of text and yet be centered.";
            font_size: 20px;
            wrap: word-wrap;
        }
    }

    property <bool> test: text.height > 0 && text.width == root.width;
}

/*

```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert(instance.get_test());
```


```rust
let instance = TestCase::new().unwrap();
assert!(instance.get_test());
```

```js
var instance = new slint.TestCase({});
assert(instance.test);
```

*/
