// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

TestCase := Window {
    VerticalLayout {
        padding: 10px;
        spacing: 27px;
        Rectangle {
            background: blue;
            preferred-width: 25phx;
            preferred-height: 500phx;
            horizontal-stretch: 0;
            vertical-stretch: 0;
        }
        Rectangle {
            background: green;
            // implicit: horizontal-stretch: 1
        }
    }

    property w <=> root.preferred-width;

    property <bool> test: root.preferred_height == 500phx + 20px + 27px && root.preferred_width == 25phx + 20px;
}

/*

```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert(instance.get_test());
```


```rust
let instance = TestCase::new().unwrap();
assert!(instance.get_test());
```

```js
var instance = new slint.TestCase();
assert(instance.test);
```

*/
