// Copyright © 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nathan Collins <nathan.collins@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

interface A {
    out property <int> speed;
    in-out property <string> greeting;
    pure callback callback-a() -> int;
    public pure function function-a() -> int;
}

interface B inherits A {
    out property <float> direction;
    pure callback callback-b() -> int;
    public pure function function-b() -> int;
}

export component TestCase implements B {
    speed: 42;
    greeting: "Hola";
    direction: 45.0;

    property <bool> test-properties: self.speed == 42 && self.direction == 45.0 && self.greeting == "Hola";
    property <bool> test-callbacks: self.callback-a() == 2 && self.callback-b() == 3;
    property <bool> test-functions: self.function-a() == 4 && self.function-b() == 5;

    out property <bool> test: test-properties && test-callbacks && test-functions;

    callback-a() => {
        2
    }

    callback-b() => {
        3
    }

    public pure function function-a() -> int {
        4
    }

    public pure function function-b() -> int {
        5
    }
}

/*
```rust
let instance = TestCase::new().unwrap();
assert_eq!(instance.get_speed(), 42);
assert_eq!(instance.get_direction(), 45.0);
assert_eq!(instance.get_greeting(), "Hola");
assert_eq!(instance.invoke_callback_a(), 2);
assert_eq!(instance.invoke_callback_b(), 3);
assert_eq!(instance.invoke_function_a(), 4);
assert_eq!(instance.invoke_function_b(), 5);
```

```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert_eq(instance.get_speed(), 42);
assert_eq(instance.get_direction(), 45.0);
assert_eq(instance.get_greeting(), "Hola");
assert_eq(instance.invoke_callback_a(), 2);
assert_eq(instance.invoke_callback_b(), 3);
assert_eq(instance.invoke_function_a(), 4);
assert_eq(instance.invoke_function_b(), 5);
```

```js
var instance = new slint.TestCase({});
assert.equal(instance.speed, 42);
assert.equal(instance.direction, 45.0);
assert.equal(instance.greeting, "Hola");
assert.equal(instance.callback_a(), 2);
assert.equal(instance.callback_b(), 3);
assert.equal(instance.function_a(), 4);
assert.equal(instance.function_b(), 5);
```
*/
