// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

NotInIf := Rectangle {
    if true: Rectangle {
        @children
//      ^error{The @children placeholder cannot appear in a conditional element}
    }
}

NotInFor := Rectangle {
    HorizontalLayout {
        for xxx in 12: Rectangle {
            VerticalLayout {
                @children
//              ^error{The @children placeholder cannot appear in a repeated element}
            }
        }
    }
}

TestBox := Rectangle {
    @children
    @children
//  ^error{The @children placeholder can only appear once in an element}
}

TestBox2 := Rectangle {
    Rectangle {
        @children
    }
    @children
//  ^error{The @children placeholder can only appear once in an element hierarchy}
}

export Final := TestBox {
    Rectangle {
        @children
//      ^error{children placeholder not allowed in the final component}
    }
}
