// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// comment

// line comment
export SuperSimple := Rectangle {
//                 ^warning{':=' to declare a component is deprecated. The new syntax declare components with 'component MyComponent {'. Read the documentation for more info}
    /* block comment */
    background: green;

    //comment

    /* block comment
       on several
       lines
    */
    background: /* . */ blue;
//  ^error{Duplicated property binding}
}

/* another comment
    /* even with some /*nesting*/*/

plop
*/

// this is a comment
