// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

import { StandardButton } from "std-widgets.slint";

export Test := Dialog {
//             ^error{A Dialog must have a single child element that is not StandardButton}
    StandardButton { kind: ok; }
    StandardButton { }
//  ^error{The `kind` property of the StandardButton in a Dialog must be set}
    StandardButton { kind: true ? ok : cancel; }
//                         ^error{The `kind` property of the StandardButton in a Dialog must be known at compile-time}

}
