// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0


export SuperSimple := Rectangle {
//                 ^warning{':=' to declare a component is deprecated. The new syntax declare components with 'component MyComponent {'. Read the documentation for more info}
    background: green;

    for xx Text {}
//         ^error{Invalid 'for' syntax: there should be a 'in' token}


    for xx in zz: Hello {
        Rectangle {}
    }

    Image {
    }

    for xx[idx] in zz: Hello {
        Rectangle {}
    }

    for x in 0..32: Rectangle { }
//              ^error{Parse error. Range expressions are not supported in Slint. You can use an integer as a model to repeat something multiple time. Eg: `for i in 32 : ...`}


}
