// Copyright © Klarälvdalens Datakonsult AB, a KDAB Group company, info@kdab.com
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component TestCase inherits Window {


    lay1 := GridLayout {

        Text {
            row: 1;
            col: self.x > 10px ? 3 : 4;
//               >                    <warning{The binding for the property 'col' is part of a binding loop (root.layoutinfo-h -> lay1.width -> lay1.layout-cache-h -> Text.x -> Text.col -> lay1.layout-organized-data -> lay1.layoutinfo-h -> root.layoutinfo-h)↵This was allowed in previous version of Slint, but is deprecated and may cause panic at runtime}
        }
    }
}
