// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

Inline1 := Rectangle {
    Rectangle {
        x: 66phx;
    }
}

export SubElements := Rectangle {
    Inline1 {
        background: yellow;
        invalid: yellow;
//      ^error{Unknown property invalid in Inline1}
//               ^^error{Unknown unqualified identifier 'yellow'}
    }
}
