// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component X {
    property <styled-text> t1: @markdown("{}", "test");
    property <styled-text> t2: @markdown("{} {}", "test");
    property <styled-text> t3: @markdown("{}", "test", "test2");
    property <styled-text> t4: @markdown("{0} {0}", "test");
    property <styled-text> t5: @markdown("{1} {1}", "test");
    property <styled-text> t6: @markdown("{1} {1}", "test", "test2");
    property <styled-text> t7: @markdown("{1} {0}", "test", "test2");

}
