// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

Test2 := Path {
    width: 640px;
    height: 480px;
    commands: "M 0 0 M -100 0 A 100 100 0 1 0 100 0 Å 100 100 0 1 0 100 0 Z";
    //        ^error{Error parsing SVG commands}
}

export TestCase := Rectangle {
    Path {
        width: 100px;
        height: 100px;
        commands: "hello world";
        //        ^error{Error parsing SVG commands}
        stroke: red;
        stroke-width: 1px;
    }

    Path {
        width: 640px;
        height: 480px;
        commands: "M 0 0 M -100 0 A 100 100 0 1 0 100 0 A 100 100 0 1 0 100 0 Z";
    }

    Path {
        width: 640px;
        height: 480px;
        commands: "M 0 0 M -100 0 A 100 100 0 1 0 0 A 100 100 0 1 0 100 0 Z";
        //        ^error{Error parsing SVG commands}
    }

    Test2 {}

    property <[{commands: string}]> model: [{commands: "M 0 0 L 0 100 A 1 1 0 0 0 100 100 L 100 0 Z"}];
    for entry in model: Path {
        commands: entry.commands; // Don't panic
    }
}
