// Copyright © SixtyFPS GmbH <info@sixtyfps.io>
// SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)


X := PopupWindow {
//  ^error{PopupWindow cannot be the top level}

    Rectangle {

        popup := PopupWindow {
//              ^error{Cannot access the inside of a PopupWindow from enclosing component}
            r := Rectangle {
            }
        }

        background: r.background;

    }



}
