// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial


export TestCase := Rectangle {
    Path {
        commands: "M 350 300 L 550 300 ";
        LineTo { x: 10; y: 100; }
//      ^error{Path elements cannot be mixed with the use of the SVG commands property}
    }

    property<string> cmds: "M 350 300 L 550 300 ";

    Path {
        commands: cmds;
    }

}
