// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

import { ColorSchemeSelector } from "color-scheme.slint";

import { Button } from "button.slint";
export { Button }

import { ScrollView } from "scrollview.slint";
export { ScrollView }

import { ListItem } from "components.slint";
export { ListItem }

import { CupertinoPalette, CupertinoFontSettings } from "styling.slint";

export global StyleMetrics  {
    out property <length> layout-spacing: 10px;
    out property <length> layout-padding: 12px;
    out property <length> text-cursor-width: 1px;
    out property <color> window-background: CupertinoPalette.background;
    out property <color> default-text-color: CupertinoPalette.foreground;
    out property <color> textedit-background: CupertinoPalette.alternate-background;
    out property <color> textedit-text-color: CupertinoPalette.foreground;
    out property <color> textedit-background-disabled: CupertinoPalette.tertiary-control-background;
    out property <color> textedit-text-color-disabled: CupertinoPalette.foreground-secondary;
    out property <bool> dark-color-scheme: CupertinoPalette.dark-color-scheme;
}

export global Palette {
    out property <brush> background: CupertinoPalette.background;
    out property <brush> alternate-background: CupertinoPalette.alternate-background;
    out property <brush> foreground: CupertinoPalette.foreground;
    out property <brush> accent-background: CupertinoPalette.accent-background;
    out property <brush> accent-foreground: CupertinoPalette.accent-foreground;
    out property <brush> control-background: CupertinoPalette.control-background;
    out property <brush> control-foreground: CupertinoPalette.control-foreground;
    out property <brush> border: CupertinoPalette.border;
    out property <brush> selection-background: CupertinoPalette.selection-background;
}
