// Copyright © 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nathan Collins <nathan.collins@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Host } from "../../typeloader/typed_slot_host.slint";

export component Test inherits Window {
    Host { }
//  >   <error{Typed slot 'control' requires a component that provides 'Interaction'}
    Host {
        control << TouchArea { }
    }
}
