// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

component Button inherits Rectangle {
    background: blue;
    Text { text: "touch me"; }
}

component Empty inherits Rectangle { }

export component TestCase inherits Window {
    Button {
        width: 200px;
        height: 48px;
        inner-shadow-color: #052e1680;
        inner-shadow-blur: 6px;
        inner-shadow-offset-y: 2px;
        inner-shadow-spread: 1px;
    }
    Empty {
        inner-shadow-color: red;
        inner-shadow-blur: 2px;
    }
    for i in 2 : Button {
        inner-shadow-color: green;
        inner-shadow-blur: 2px;
    }
    out property <bool> test: true;
}

/*
```rust
let instance = TestCase::new().unwrap();
assert!(instance.get_test());
```
*/
