// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial


export struct Color {
    SharedVector: string,
}

export struct SharedString {
    Model: string,
    Component: int,
}

export struct ComponentHandle {
    SharedString: string,
}

export struct Model {
    _self: Color,
}

export component TestCase {
    in-out property<Model> Model: {_self: { SharedVector: "ddd" }};
    in-out property<SharedString> SharedString: {Model: Model._self.SharedVector };
    in-out property<[ComponentHandle]> Rectangle: [{SharedString: SharedString.Model}];
}

