// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component SuperSimple {
    property <[keys]> shortcuts: [
        @keys(),
        @keys("a"),
        @keys(Control + "+"),
        @keys(Alt + Control + Shift + Meta + "x"),

        // Lookup in Keys namespace
        @keys(Alt + Control + Shift + Meta + Return),
        @keys(Escape),
        @keys(A),
        @keys(Control + Shift + A),
        @keys(Plus),
        @keys(Control + Alt + Plus),

        // Shift?
        @keys(Shift? + "+"), // equivalent to @keys(Plus)
        @keys(Alt + Shift? + Control + Meta + Escape), // supports both Shift+Escape and Escape in a single shortcut
        @keys(Control + Shift? + A),

        // Alt?
        // note: this is e.g. needed on MacOS with a French layout:
        @keys(Alt? + "{"),
        @keys(Alt? + Shift + Control + Meta + Escape),
        @keys(Control + Alt? + A),

        // Unicode characters (single grapheme clusters are valid)
        @keys("é"),
        @keys(Control + "ñ"),
    ];
}
