// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component SuperSimple {
    property <[keyboard-shortcut]> invalid_shortcuts: [
        // Right-side modifier keys
        @keys(AltR + "a"),
//            >  <error{Right-side modifiers are not supported}
        @keys(AltGr + "a"),
//            >   <error{AltGr as modifier is unnecessary (remove it)}
        @keys(ControlR + "a"),
//            >      <error{Right-side modifiers are not supported}
        @keys(MetaR + "a"),
//            >   <error{Right-side modifiers are not supported}
        @keys(ShiftR + "a"),
//            >    <error{Right-side modifiers are not supported}


        // Duplicate modifier or key
        @keys(Alt + Control + Shift + Meta + Alt + "a"),
//                                           > <error{Duplicated modifier in keyboard shortcut}
        @keys(Alt + Control + Shift + Meta + Control + "a"),
//                                           >     <error{Duplicated modifier in keyboard shortcut}
        @keys(a + b),
//                ^error{A keyboard shortcut can only contain one key (with modifiers)}
        @keys(Alt + Control + Shift + Meta + Meta + "a"),
//                                           >  <error{Duplicated modifier in keyboard shortcut}
        @keys(Alt + Control + Shift + Meta + Shift + "a"),
//                                           >   <error{Duplicated modifier in keyboard shortcut}
        @keys(IgnoreShift + IgnoreShift + "a"),
//                          >         <error{Duplicated modifier in keyboard shortcut}

        // Conflicting Shift + IgnoreShift
        @keys(Alt + Control + Shift + Meta + IgnoreShift + "a"),
//                                           >         <error{Cannot use both Shift and IgnoreShift (remove one of them)}
        @keys(Alt + Control + IgnoreShift + Meta + Shift + "a"),
//                                                 >   <error{Cannot use both Shift and IgnoreShift (remove one of them)}


        // Invalid syntax
        @keys(a, b),
//             ^error{Expected '+', a string literal, or an identifier in the Keys namespace}
        @keys(Alt Control + Shift + Meta + a),
//                >     <error{Expected '+' to separate parts of a keyboard shortcut}
        @keys(Alt + Shift),
//                       ^error{A keyboard shortcut must be empty or contain exactly one key (with modifiers)}
        @keys(Alt ++ a),
//                 ^error{Unexpected '+' in keyboard shortcut}
        @keys("a" +),
//                 ^error{Expected another identifier or string literal}
        @keys(Shift +),
//                   ^error{Expected another identifier or string literal}
    ];
}
