// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export SuperSimple := Rectangle {
//                 ^warning{':=' to declare a component is deprecated. The new syntax declare components with 'component MyComponent {'. Read the documentation for more info}
    property<bool> zz: aa > bb == cc
//                             ^error{Use parentheses to disambiguate equality expression on the same level}
                < dd;
//              ^error{Use parentheses to disambiguate equality expression on the same level}

    property<bool> yy: aa <= bb <= cc;
//                              ^error{Use parentheses to disambiguate equality expression on the same level}
    property<bool> xx: aa<bb>(d);
//                          ^error{Use parentheses to disambiguate equality expression on the same level}

    property<bool> ww: aa && dd && ee || cc ==
//                                    ^error{Use parentheses to disambiguate between && and ||}
        dd == ee;
//         ^error{Use parentheses to disambiguate equality expression on the same level}

}
