#!/usr/bin/env bash
# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

#MISE description="Run clippy fix on all files"

set -e

pnpm install --frozen-lockfile || true
pnpm run format:fix
pnpm run lint:fix
