// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Button, CheckBox, ComboBox, LineEdit, Palette, Slider, TextEdit } from "std-widgets.slint";

import { Api, ColorData, ElementInformation, PreviewData, PreviewDataKind, PropertyContainer, PropertyInformation, PropertyValue, PropertyValueKind } from "../api.slint";
import { BodyStrongText } from "../components/body-strong-text.slint";
import { BodyText } from "../components/body-text.slint";
import { StateLayer } from "../components/state-layer.slint";
import { EditorAnimationSettings, EditorFontSettings, EditorSizeSettings, EditorSpaceSettings, Icons } from "../components/styling.slint";

component CodeButton inherits Button {
    text: @tr("Code");
}

component ResetButton inherits Button {
    text: @tr("Reset");
}

component NameLabel inherits HorizontalLayout {
    in property <string> property-name;
    in property <PropertyValue> property-value;

    horizontal-stretch: 0;

    BodyText {
        min-width: EditorSizeSettings.min-prefix-text-width;
        height: root.property-name != "" ? self.preferred-height : 0;
        text: root.property-name;

        font-size: 1rem;
        font-weight: root.property-value.code != "" ? EditorFontSettings.bold-font-weight : EditorFontSettings.light-font-weight;
        font-italic: root.property-value.code == "";

        overflow: elide;
    }
}

component ResettingLineEdit {
    in property <string> default-text;
    in-out property <bool> can-compile: true;

    in property <bool> enabled;
    in property <InputType> input-type <=> le.input-type;
    in property <TextHorizontalAlignment> horizontal-alignment <=> le.horizontal-alignment;
    in property <string> placeholder-text <=> le.placeholder-text;
    out property <bool> has-focus <=> le.has-focus;
    in-out property <string> text <=> le.text;

    property <length> border: 3px;

    callback accepted <=> le.accepted;
    callback edited <=> le.edited;
    VerticalLayout {
        le := LineEdit {
            enabled: root.enabled;
            text: root.default-text;
            font-size: 1rem;

            // Reset on focus loss:
            changed has-focus => {
                if !self.has_focus && text != default-text {
                    if root.can-compile {
                        root.accepted(self.text);
                    }
                } else {
                    // self.text = root.default-text;
                    root.can-compile = true;
                }
            }
        }
    }

    Rectangle {
        visible: !root.can-compile;

        background: Colors.red.transparentize(0.94);
        x: root.border;
        y: root.border;
        width: root.width - 2 * root.border;
        height: root.height - 2 * root.border;

        border-radius: root.border;
    }
}

component ChildIndicator inherits Rectangle {
    out property <bool> open: false;
    in property <bool> control-hover: false;

    width: 16px;

    indicator := Image {
        vertical-alignment: center;

        colorize: Palette.foreground;
        visible: expand.has-hover || root.control-hover;
        source: Icons.chevron-down;
        rotation-angle: root.open ? 0deg : -90deg;
    }

    expand := TouchArea {
        width: 1cm;
        height: 1cm;

        clicked => {
            root.open = !root.open;
        }
    }
}

component CodeWidget inherits GridLayout {
    in property <bool> enabled;
    in property <string> property-name;
    in property <PropertyValue> property-value;

    callback code-action();
    callback reset-action();

    padding-bottom: EditorSpaceSettings.default-spacing;

    Row {
        NameLabel {
            col: 1;

            property-name: root.property-name;
            property-value: root.property-value;
        }
    }

    Row {
        ChildIndicator {
            visible: false;
        }

        Rectangle {
            min-height: 2rem;
            width: root.property-value.code == "" ? root.width : 0px;
            background: Palette.alternate-background;
            Text {
                horizontal-alignment: left;
                vertical-alignment: center;
                text: @tr("Not Set");
                font-italic: true;
            }
        }

        HorizontalLayout {
            width: root.property-value.code != "" ? root.width : 0px;

            spacing: EditorSpaceSettings.default-spacing;
            ResetButton {
                enabled: root.enabled;
                clicked() => {
                    root.reset-action();
                }
            }

            CodeButton {
                enabled: root.enabled;
                clicked() => {
                    root.code-action();
                }
            }
        }
    }
}

component SecondaryContent inherits Rectangle {
    in property <bool> enabled;
    in property <bool> open: false;
    in property <bool> has-code-action: true;
    in property <bool> has-reset-action: true;
    
    callback reset();

    callback code-action();
    callback reset-action();

    background: Palette.background;
    clip: true;
    height: open ? content.preferred-height : 0px;

    animate height { duration: EditorAnimationSettings.rotation-duration; }

    content := HorizontalLayout {
        width: 100%;

        Rectangle {
            height: 100%;
            width: 1px;
            background: Palette.border;
        }

        VerticalLayout {
            padding: EditorSpaceSettings.default-padding;
            spacing: EditorSpaceSettings.default-padding;

            @children

            HorizontalLayout {
                spacing: EditorSpaceSettings.default-spacing;

                if root.has-reset-action: ResetButton {
                    enabled: root.enabled;
                    clicked() => {
                        root.reset-action();
                        root.reset();
                    }
                }

                if root.has-code-action: CodeButton {
                    enabled: root.enabled;
                    clicked() => {
                        root.code-action();
                    }
                }
            }
        }
    }
}

component FloatWidget inherits GridLayout {
    in property <bool> enabled;
    in property <string> property-name;
    in property <PropertyValue> property-value;

    pure callback test-float-binding(text: string) -> bool;
    pure callback set-float-binding(text: string);

    private property <string> current-unit: find_current_unit(property-value);

    pure function find_current_unit(value: PropertyValue) -> string {
        if value.visual-items.length == 0 {
            return "";
        }
        return value.visual-items[self.find-current-index(value)];
    }

    pure function find_current_index(value: PropertyValue) -> int {
        return value.code == "" ? value.default-selection : value.value-int;
    }

    function set-binding() {
        root.set-float-binding(number.text == "" ? "" : number.text + self.current-unit);
    }

    width: 100%;

    Row {
        NameLabel {
            col: 1;
            property-name: root.property-name;
            property-value: root.property-value;
        }
    }

    Row {
        ChildIndicator {
            horizontal-stretch: 0;
            visible: false;
        }

        HorizontalLayout {
            spacing: EditorSpaceSettings.default-spacing;
            alignment: stretch;
            height: 2rem;

            number := ResettingLineEdit {
                enabled: root.enabled;
                horizontal-alignment: right;
                min-width: EditorSizeSettings.float-size;
                horizontal-stretch: 0;

                default-text: property-value.value-float;

                edited(text) => {
                    self.can-compile = test-float-binding(number.text == "" ? "" : number.text + root.current-unit);
                }

                accepted(text) => {
                    root.set-binding();
                }
            }

            if property-value.visual-items.length > 1: ComboBox {
                enabled: root.enabled;

                horizontal-stretch: 0;

                min-width: EditorSizeSettings.length-combo;
                model: property-value.visual-items;
                current-index: root.find_current_index(root.property-value);

                selected(unit) => {
                    root.current-unit = unit;
                    root.set-float-binding(number.text == "" ? "" : number.text + root.current-unit);
                }
            }
            if property-value.visual-items.length == 1: Text {
                text: property-value.visual-items[0];

                changed text => {
                    root.current-unit = self.text;
                }
            }
        }
    }
}

component StringWidget inherits GridLayout {
    // FIXME: @ogoffart says the plural support is not working at this time, so
    //        we do not offer it in the UI for the time being...

    in property <bool> enabled;
    in property <string> property-name;
    in property <PropertyValue> property-value;
    in property <bool> has-code-action <=> sub.has-code-action;
    in property <bool> has-reset-action <=> sub.has-reset-action;

    out property <length> i-am-a-hack-remove-me: 0px;

    property <bool> open: false;

    callback code-action();
    callback reset-action();

    pure callback test-string-binding(text: string, is-translated: bool) -> bool;
    pure callback set-string-binding(text: string, is-translated: bool);

    pure function tsb() -> bool {
        // return test-string-binding(Api.string-to-code(text-rle.text, tr-cb.checked, tr-context.text, tr-plural.text, tr-plural-expression.text), tr-cb.checked);
        return test-string-binding(Api.string-to-code(text-rle.text, tr-cb.checked, tr-context.text, "", ""), tr-cb.checked);
    }
    pure function ssb() {
        // set-string-binding(Api.string-to-code(text-rle.text, tr-cb.checked, tr-context.text, tr-plural.text, tr-plural-expression.text), tr-cb.checked);
        set-string-binding(Api.string-to-code(text-rle.text, tr-cb.checked, tr-context.text, "", ""), tr-cb.checked);
    }

    init => {
        self.i-am-a-hack-remove-me = self.preferred-height;
    }

    Row {
        NameLabel {
            col: 1;

            property-name: root.property-name;
            property-value: root.property-value;
        }
    }

    Row {
        childIndicator := ChildIndicator {
            horizontal-stretch: 0;
            control-hover: text_rle.has-focus;
        }

        content := HorizontalLayout {
            spacing: EditorSpaceSettings.default-spacing;
            height: 2rem;
            text_rle := ResettingLineEdit {
                enabled: root.enabled;
                default-text: property-value.value-string;
                edited(text) => {
                    self.can-compile = root.tsb();
                }
                accepted(text) => {
                    root.ssb();
                }
            }
        }
    }

    Row {
        sub := SecondaryContent {
            col: 1;

            enabled: root.enabled;
            open: childIndicator.open;

            code-action() => {
                root.code-action();
            }
            reset-action => {
                root.reset-action();
            }

            GridLayout {
                spacing: EditorSpaceSettings.default-spacing;
                Row {
                    tr-cb := CheckBox {
                        colspan: 2;
                        checked: root.property-value.is-translatable;
                        toggled => {
                            root.ssb();
                        }
                        enabled: root.enabled;
                        text: "Translatable";
                    }
                }

                Row {
                    Text {
                        vertical-alignment: center;
                        horizontal-alignment: right;
                        text: "Context";
                    }

                    tr-context := ResettingLineEdit {
                        enabled: root.enabled && tr-cb.checked;
                        default-text: root.property-value.tr-context;
                        edited(text) => {
                            self.can-compile = root.tsb();
                        }
                        accepted(text) => {
                            root.ssb();
                        }
                    }
                }

                // Row {
                //     Text {
                //         vertical-alignment: center;
                //         horizontal-alignment: right;
                //         text: "Plural";
                //     }

                //     tr-plural := ResettingLineEdit {
                //         enabled: root.enabled && tr-cb.checked;
                //         default-text: root.property-value.tr-plural;
                //         edited(text) => {
                //             self.can-compile = root.tsb();
                //         }
                //         accepted(text) => {
                //             root.ssb();
                //         }
                //     }
                // }

                // Row {
                //     Text {
                //         vertical-alignment: center;
                //         horizontal-alignment: right;
                //         text: "Expression";
                //     }

                //     tr-plural-expression := ResettingLineEdit {
                //         enabled: root.enabled && tr-cb.checked;
                //         default-text: root.property-value.tr-plural-expression;
                //         edited(text) => {
                //             self.can-compile = root.tsb();
                //             tr-plural.can-compile = self.can-compile;
                //         }
                //         accepted(text) => {
                //             root.ssb();
                //         }
                //     }
                // }
            }
        }
    }
}

component ColorLineEdit inherits HorizontalLayout {
    in property <bool> enabled;
    in property <string> channel: "R";
    in-out property <float> value;

    alignment: stretch;
    spacing: EditorSpaceSettings.default-spacing;

    Text {
        text: channel;
        vertical-alignment: center;
        color: Palette.foreground;
    }

    slide-value := Slider {
        enabled: root.enabled;
        minimum: 0;
        maximum: 255;
        step: 1;
        value <=> root.value;
        horizontal-stretch: 1;

        changed value => {
            // root.value = Math.floor(self.value);
        }
    }

    num-value := ResettingLineEdit {
        enabled: root.enabled;
        input-type: number;
        width: 5rem;
        default-text: Math.floor(root.value);
        text: Math.floor(root.value);

        edited() => {
            root.value = self.text.to-float();
        }
    }
}

component ColorWidget inherits GridLayout {
    in property <bool> enabled;
    in property <string> property-name;
    in property <PropertyValue> property-value;
    in property <bool> has-code-action <=> sub.has-code-action;
    in property <bool> has-reset-action <=> sub.has-reset-action;

    private property <bool> open: false;

    callback code-action();
    callback reset-action();

    pure callback test-color-binding(text: string) -> bool;
    pure callback set-color-binding(text: string);

    private property <color> current-color: property-value.value-brush;
    private property <ColorData> current-color-data: Api.color-to-data(self.current-color);

    changed current-color-data => {
        root.test-color-binding(current-color-data.text);
    }

    width: 100%;

    Row {
        NameLabel {
            col: 1;

            property-name: root.property-name;
            property-value: root.property-value;
        }
    }

    Row {
        childIndicator := ChildIndicator {
            horizontal-stretch: 0;
            control-hover: rle.has-focus;
        }

        content := HorizontalLayout {
            spacing: EditorSpaceSettings.default-spacing;
            alignment: stretch;

            rle := ResettingLineEdit {
                enabled: root.enabled;
                default-text: root.current-color-data.text;

                edited(text) => {
                    if text == "" {
                        // allow empty text -- which will delete the property
                        self.can-compile = true;
                        color-preview.background = Colors.transparent;
                    } else {
                        self.can-compile = root.test-color-binding(text);
                        if self.can-compile {
                            color-preview.background = Api.string-to-color(text);
                        }
                    }
                }

                accepted(text) => {
                    root.set-color-binding(text);
                }
            }

            color-preview := Rectangle {
                height: 2rem;
                background: root.current-color;
                border-width: 1px;
                border-color: Palette.foreground;
            }
        }
    }

    Row {
        sub := SecondaryContent {
            out property <color> slider-color: Api.rgba-to-color(r.value, g.value, b.value, a.value);

            col: 1;
            enabled: root.enabled;

            changed slider-color => {
                root.current-color = slider-color;
            }

            open: childIndicator.open;

            r := ColorLineEdit {
                enabled: root.enabled;
                value: root.current-color-data.r;
                channel: "R";
                changed value => {
                    root.set-color-binding(rle.text);
                }
            }

            g := ColorLineEdit {
                enabled: root.enabled;
                value: root.current-color-data.g;
                channel: "G";
                changed value => {
                    root.set-color-binding(rle.text);
                }

            }

            b := ColorLineEdit {
                enabled: root.enabled;
                value: root.current-color-data.b;
                channel: "B";
                changed value => {
                    root.set-color-binding(rle.text);
                }
            }

            a := ColorLineEdit {
                enabled: root.enabled;
                value: root.current-color-data.a;
                channel: "A";
                changed value => {
                    root.set-color-binding(rle.text);
                }
            }

            reset => {
                root.current-color = root.property-value.value-brush;
            }

            code-action() => {
                root.code-action();
            }
            reset-action() => {
                root.reset-action();
            }
        }
    }
}

component IntegerWidget inherits GridLayout {
    in property <bool> enabled;
    in property <string> property-name;
    in property <PropertyValue> property-value;

    pure callback test-integer-binding(text: string) -> bool;
    pure callback set-integer-binding(text: string);

    width: 100%;

    Row {
        NameLabel {
            col: 1;
            property-name: root.property-name;
            property-value: root.property-value;
        }
    }

    Row {
        childIndicator := ChildIndicator {
            horizontal-stretch: 0;
            visible: false;
        }

        HorizontalLayout {
            height: 2rem;
            spacing: EditorSpaceSettings.default-spacing;
            ResettingLineEdit {
                enabled: root.enabled;
                horizontal-alignment: right;
                input-type: number;

                default-text: property-value.value-int;

                edited(text) => {
                    self.can-compile = test-integer-binding(text);
                }
                accepted(text) => {
                    set-integer-binding(text);
                }
            }
        }
    }
}

component EnumWidget inherits GridLayout {
    in property <bool> enabled;
    in property <string> property-name;
    in property <PropertyValue> property-value;

    pure callback set-enum-binding(text: string);

    width: 100%;

    Row {
        NameLabel {
            col: 1;
            property-name: root.property-name;
            property-value: root.property-value;
        }
    }

    Row {
        childIndicator := ChildIndicator {
            horizontal-stretch: 0;
            visible: false;
        }
        HorizontalLayout {
            ComboBox {
                enabled: root.enabled;
                current-index: property-value.value-int;

                model: property-value.visual-items;

                selected(value) => {
                    root.set-enum-binding(property-value.value-string + "." + value);
                }
            }
        }
    }
}

component BooleanWidget inherits GridLayout {
    in property <bool> enabled;
    in property <string> property-name;
    in property <PropertyValue> property-value;

    pure callback set-bool-binding(value: bool);

    width: 100%;

    Row {
        NameLabel {
            col: 1;
            property-name: root.property-name;
            property-value: root.property-value;
        }
    }

    Row {
        childIndicator := ChildIndicator {
            horizontal-stretch: 0;
            visible: false;
        }

        HorizontalLayout {
            alignment: start;
            height: 2rem;
            Rectangle {
                width: 100%;
                height: 100%;
                background: Palette.alternate-background;
                HorizontalLayout {
                    alignment: start;
                    padding-left: EditorSpaceSettings.default-padding;
                    spacing: EditorSpaceSettings.default-spacing;
                    checkbox := CheckBox {
                        enabled: root.enabled;
                        checked: root.property-value.value-bool;
                        text: self.checked ? "True" : "False";

                        toggled() => {
                            root.set-bool-binding(self.checked);
                        }
                    }
                }
            }
        }
    }
}

component EditJsonWidget inherits GridLayout {
    in property <bool> enabled;
    in property <string> property-name;
    in property <PropertyValue> property-value;

    property <bool> can-compile: true;
    property <length> border: 3px;

    width: 100%;

    pure callback set-code-binding(text: string) -> bool;

    changed property-value => {
        if !edit.has-focus {
            edit.text = root.property-value.code;
            root.can-compile = true;
        }
    }

    Row {
        NameLabel {
            col: 1;
            property-name: root.property-name;
            property-value: root.property-value;
        }
    }

    Row {
        childIndicator := ChildIndicator {
            horizontal-stretch: 0;
            visible: false;
        }

        Rectangle {
            VerticalLayout {
                edit := TextEdit {
                    min-height: 200px;

                    text: root.property-value.code;
                    enabled: root.enabled;

                    edited(text) => {
                        root.can-compile = root.set-code-binding(text);
                    }

                    changed has-focus => {
                        self.text = root.property-value.code;
                        root.can-compile = true;
                    }
                }
            }

            Rectangle {
                visible: !root.can-compile;

                background: Colors.red.transparentize(0.94);
                x: edit.x + root.border;
                y: edit.y + root.border;
                width: edit.width - 2 * root.border;
                height: edit.height - 2 * root.border;

                border-radius: root.border;
            }
        }
    }
}

export component PropertyValueWidget inherits VerticalLayout {
    in property <PropertyValue> property-value;
    in property <string> property-name;
    in property <bool> enabled;
    in property <bool> has-code-action: true;
    in property <bool> has-reset-action: true;

    pure callback set-bool-binding(value: bool);
    pure callback set-color-binding(text: string);
    pure callback test-color-binding(text: string) -> bool;
    pure callback set-code-binding(text: string);
    pure callback test-code-binding(text: string) -> bool;
    pure callback set-string-binding(text: string, is_translated: bool);
    pure callback test-string-binding(text: string, is_translated: bool) -> bool;
    pure callback set-enum-binding(text: string);

    callback reset-action();
    callback code-action();

    VerticalLayout {
        Rectangle {
            clip: true;
            height: root.property-value.kind == PropertyValueKind.boolean ? self.preferred-height : 0px;

            BooleanWidget {
                enabled <=> root.enabled;
                property-name <=> root.property-name;
                property-value <=> root.property-value;

                set-bool-binding(value) => {
                    root.set-bool-binding(value);
                }
            }
        }
        Rectangle {
            clip: true;
            height: (root.property-value.kind == PropertyValueKind.color) || (root.property-value.kind == PropertyValueKind.brush)  ? self.preferred-height : 0px;

            ColorWidget {
                enabled <=> root.enabled;
                property-name <=> root.property-name;
                property-value <=> root.property-value;

                has-code-action: root.has-code-action;
                has-reset-action: root.has-reset-action;

                test-color-binding(text) => {
                    return (root.test-color-binding(text));
                }
                set-color-binding(text) => {
                    root.set-color-binding(text);
                }
            }
        }
        Rectangle {
            clip: true;
            height: root.property-value.kind == PropertyValueKind.code ? self.preferred-height : 0px;

            CodeWidget {
                enabled <=> root.enabled;
                property-name <=> root.property-name;
                property-value <=> root.property-value;

                reset-action() => {
                    root.reset-action();
                }
                code-action() => {
                    root.code-action();
                }
            }
        }
        Rectangle {
            clip: true;
            height: root.property-value.kind == PropertyValueKind.enum ? self.preferred-height : 0px;

            EnumWidget {
                enabled <=> root.enabled;
                property-name <=> root.property-name;
                property-value <=> root.property-value;

                set-enum-binding(text) => {
                    root.set-enum-binding(text);
                }
            }
        }
        Rectangle {
            clip: true;
            height: root.property-value.kind == PropertyValueKind.float ? self.preferred-height : 0px;

            FloatWidget {
                enabled <=> root.enabled;
                property-name <=> root.property-name;
                property-value <=> root.property-value;

                test-float-binding(text) => {
                    return (root.test-code-binding(text));
                }
                set-float-binding(text) => {
                    root.set-code-binding(text);
                }
            }
        }
        Rectangle {
            clip: true;
            height: root.property-value.kind == PropertyValueKind.integer ? self.preferred-height : 0px;

            IntegerWidget {
                enabled <=> root.enabled;
                property-name <=> root.property-name;
                property-value <=> root.property-value;

                test-integer-binding(text) => {
                    return (root.test-code-binding(text));
                }
                set-integer-binding(text) => {
                    root.set-code-binding(text);
                }
            }
        }
        Rectangle {
            clip: true;
            height: root.property-value.kind == PropertyValueKind.string ? self.preferred-height : 0px;

            StringWidget {
                enabled <=> root.enabled;
                property-name <=> root.property-name;
                property-value: root.property-value;

                has-code-action: root.has-code-action;
                has-reset-action: root.has-reset-action;

                reset-action() => {
                    root.reset-action();
                }
                code-action() => {
                    root.code-action();
                }

                test-string-binding(text, is_translated) => {
                    return root.test-string-binding(text, is_translated);
                }

                set-string-binding(text, is_translated) => {
                    root.set-string-binding(text, is_translated);
                }
            }
        }
    }
}

export component PropertyInformationWidget inherits VerticalLayout {
    in property <PropertyInformation> property-information;
    in property <ElementInformation> element-information;
    in property <bool> enabled;

    PropertyValueWidget {
        property-value: root.property-information.value;
        property-name: root.property-information.name;
        enabled: root.enabled;

        set-bool-binding(value) => {
            self.set-code-binding(value ? "true" : "false");
        }
        set-color-binding(text) => {
            self.set-code-binding(text);
        }
        test-color-binding(text) => {
            return (self.test-code-binding(text));
        }
        set-enum-binding(text) => {
            self.set-code-binding(text);
        }

        set-code-binding(text) => {
            Api.set-code-binding(
                element-information.source-uri,
                element-information.source-version,
                element-information.range.start,
                property-information.name,
                text,
            );
        }
        test-code-binding(text) => {
            return (Api.test-code-binding(
                root.element-information.source-uri,
                root.element-information.source-version,
                root.element-information.range.start,
                root.property-information.name,
                text,
            ));
        }
        set-string-binding(text, is-translated) => {
            Api.set-code-binding(
                element-information.source-uri,
                element-information.source-version,
                element-information.range.start,
                property-information.name,
                text);
        }
        test-string-binding(text, is-translated) => {
            return (Api.test-code-binding(
                root.element-information.source-uri,
                root.element-information.source-version,
                root.element-information.range.start,
                root.property-information.name,
                text));
        }

        reset-action() => {
            Api.set-code-binding(
                element-information.source-uri,
                element-information.source-version,
                element-information.range.start,
                property-information.name,
                "",
            );
        }
        code-action() => {
            Api.show-document-offset-range(
                element-information.source-uri,
                Api.property-declaration-ranges(property-information.name).defined-at.expression-range.start,
                Api.property-declaration-ranges(property-information.name).defined-at.expression-range.start,
                true,
            );
        }
    }
}

export component PreviewDataPropertyValueWidget inherits VerticalLayout {
    in property <PreviewData> preview-data;
    in property <string> property-container-id;

    private property <PropertyValue> value: Api.get-property-value(root.property-container-id, root.preview-data.name);

    callback edit-in-spreadsheet(rp: PropertyContainer);

    function reset-action() {
        self.set-code-binding(self.value.code);
    }

    function set-code-binding(text: string) -> bool {
        return(Api.set-json-preview-data(root.property-container-id, root.preview-data.name, text));
    }

    if root.preview-data.kind == PreviewDataKind.Value: PropertyValueWidget {
        property-value <=> root.value;
        property-name: root.preview-data.name;
        enabled: root.preview-data.has-setter;

        has-code-action: false;
        has-reset-action: false;

        set-bool-binding(value) => {
            self.set-code-binding(value ? "true" : "false");
        }
        set-color-binding(text) => {
            self.set-code-binding("\"\{text}\"");
        }
        test-color-binding(text) => {
            return (root.set-code-binding("\"\{text}\""));
        }
        set-enum-binding(text) => {
            self.set-code-binding("\"\{text}\"");
        }
        set-code-binding(text) => {
            root.set-code-binding(text);
        }
        test-code-binding(text) => {
            return (root.set-code-binding(text));
        }
        set-string-binding(text, is_translated) => {
            self.test-string-binding(text, is_translated);
        }
        test-string-binding(text, is_translated) => {
            return(root.set-code-binding(is_translated ? "\"\{text}\"" : text));
        }
    }
    if root.preview-data.kind == PreviewDataKind.Json: EditJsonWidget {
        enabled: root.preview-data.has-setter;
        property-name: root.preview-data.name;
        property-value <=> root.value;

        set-code-binding(text) => {
            return (root.set-code-binding(text));
        }
    }
}

export component ExpandableGroup  {
    in property <bool> enabled;
    in property <string> text;
    in property <length> panel-width;

    property <bool> open: true;

    group-layer := Rectangle {
        content-layer := VerticalLayout {
            if text != "": Rectangle {
                touch-area := TouchArea {
                    clicked => {
                        root.open = !root.open;
                    }
                }

                state-layer := StateLayer {
                    width: panel-width;
                    height: group-layer.height;
                    y: group-layer.y;
                    has-hover: touch-area.has-hover;
                    pressed: touch-area.pressed;
                }

                HorizontalLayout {
                    spacing: EditorSpaceSettings.default-spacing / 2;
                    icon-image := Image {
                        width: EditorSizeSettings.default-icon-width;
                        colorize: Palette.alternate-foreground.transparentize(0.7);
                        source: Icons.chevron-down;
                        height: 2rem;
                        rotation-origin-x: self.width / 2;
                        rotation-origin-y: self.height / 2;
                        states [
                            closed when !root.open: {
                                rotation-angle: -0.25turn;
                            }
                        ]

                        animate rotation-angle { duration: EditorAnimationSettings.rotation-duration; }
                    }

                    BodyStrongText {
                        text: root.text;
                    }
                }
            }

            Rectangle {
                height: root.open ? self.preferred-height : 0px;
                clip: true;

                @children

                animate height { duration: 200ms; }
            }
        }
    }
}
