// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { MaterialWindow } from "../../../material.slint";
import { MainView } from "./views/main_view.slint";
import { MainWindowAdapter } from "./main_window_adapter.slint";

export component MainWindow inherits MaterialWindow {
    preferred-width: 600px;
    preferred-height: 400px;
    background: MainWindowAdapter.background;

    MainView {
        width: 100%;
        height: 100%;
    }

    changed width => {
        MainWindowAdapter.width = root.width;
    }

    changed height => {
        MainWindowAdapter.height = root.height;
    }
}
