// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { MaterialPalette } from "../../../material.slint";

export global MainWindowAdapter {
    in property <length> width;
    in property <length> height;
    in property <bool> surface_background;
    out property <bool> break_layout: root.width < 852px;
    out property <brush> background: root.surface_background ? MaterialPalette.surface_container :  MaterialPalette.background;
}
