# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

# Cloudflare Worker config for node-docs-staging (PR preview deployments).
name = "node-docs-staging"
compatibility_date = "2026-01-15"
preview_urls = true

[assets]
directory = "./cf-assets"
not_found_handling = "single-page-application"
