// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.2 OR LicenseRef-Slint-commercial

import { VerticalBox } from "./layouts.slint";
import { Button } from "./button.slint";
import { MaterialPalette, MaterialFontSettings, Icons } from "styling.slint";

import { Date, DatePickerBase } from "../common/datepicker_base.slint";
export { Date } 

export component DatePicker {
    in property <string> title: "Select date";
    in property <string> cancel-text: "Cancel";
    in property <string> ok-text: "Ok";
    in property <Date> date <=> base.date;

    callback canceled();
    callback accepted(/* current-date */ Date);

    min-width: content-layer.min-width;
    min-height: content-layer.min-height;

    background-layer := Rectangle {
        background: MaterialPalette.surface-container-high;
        border-radius: 28px;
    }

    content-layer := VerticalBox {        
        Text { 
            text: root.title;
            horizontal-alignment: left;
            overflow: elide;
            font-size: MaterialFontSettings.label-medium.font-size;
            font-weight: MaterialFontSettings.label-medium.font-weight;
            color: MaterialPalette.foreground;
        }

        base := DatePickerBase {
            style: {
                calendar-style: {
                    spacing: 8px,
                    delegate-style: {
                        font-size: MaterialFontSettings.body-large.font-size,
                        font-weight: MaterialFontSettings.body-large.font-weight,
                        foreground: MaterialPalette.foreground,
                        state-brush: MaterialPalette.state-default,
                        background-selected: MaterialPalette.accent-background,
                        foreground-selected: MaterialPalette.accent-foreground,
                        state-brush-selected: MaterialPalette.state-secondary,
                        border-color-today: MaterialPalette.accent-background,
                        foreground-today: MaterialPalette.accent-background,
                        state-brush-today: MaterialPalette.state-tertiary,
                    }
                }
            };
        }

        HorizontalLayout {
            spacing: 8px;
        
            Rectangle { }

            Button {
                text: root.cancel-text;

                clicked => {
                    root.canceled();
                }
            }

            Button {
                text: root.ok-text;
                enabled: base.ok-enabled();

                clicked => {
                    root.accepted(base.get-current-date());
                }
            }
        }
    }
}
