// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.2 OR LicenseRef-Slint-commercial

// cSpell: ignore standardbutton

import { TextEdit, AboutSlint } from "../common/common.slint";
import { StandardButton } from "../common/standardbutton.slint";
import { StyleMetrics, ScrollView, Button, CheckBox, Palette  } from "std-widgets-impl.slint";
import { LineEdit } from "lineedit.slint";
import { TabWidgetImpl, TabImpl, TabBarImpl, TabWidget } from "tabwidget.slint";
import { GroupBox } from "groupbox.slint";
import { VerticalBox, HorizontalBox, GridBox } from "layouts.slint";
import { Slider } from "slider.slint";
import { ComboBox } from "combobox.slint";
import { ListView, StandardListView } from "../common/listview.slint";
import { SpinBox } from "spinbox.slint";
import { StandardTableView } from "tableview.slint";
import { ProgressIndicator } from "progressindicator.slint";
import { Switch } from "switch.slint";

export { StyleMetrics, ScrollView, Button, ComboBox, CheckBox, GroupBox, StandardButton, TextEdit, TabWidgetImpl,
    TabImpl, TabBarImpl, TabWidget, LineEdit, AboutSlint, VerticalBox, HorizontalBox,
    GridBox, Slider, ListView, StandardListView, StandardTableView, SpinBox, ProgressIndicator, Switch, Palette }

import { Spinner } from "spinner.slint";
export { Spinner }
