// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

import { LineEditInner } from "../common/common.slint";
import { ScrollView } from "std-widgets-impl.slint";
import { StateLayer } from "components.slint";
import { Palette, Icons } from "styling.slint";

component TableViewColumn inherits Rectangle {
    callback clicked <=> i-state-layer.clicked;
    callback adjust_size(length);

    in property <SortOrder> sort-order: SortOrder.unsorted;

    i-state-layer := StateLayer {
        background: Palette.primary;
        selection-background: Palette.secondary-container;
        ripple-color: Palette.primary-ripple;
        has-ripple: true;
    }

    HorizontalLayout {
        padding-left: 16px;
        padding-right: 16px;
        spacing: 4px;

        HorizontalLayout {
            @children
        }

        Image {
            visible: root.sort-order != SortOrder.unsorted;
            width: 12px;
            height: 12px;
            y: (parent.height - self.height) / 2;
            source: root.sort-order == SortOrder.ascending ?
                Icons.arrow-upward :
                Icons.arrow-downward;
            colorize: Palette.on-surface;
        }
    }

    // border
    Rectangle {
        y: parent.height - self.height;
        width: 100%;
        height: 1px;
        background: Palette.outline;
    }

    Rectangle {
        x: parent.width - 1px;
        width: 1px;
        background: i-movable-touch-area.has-hover ? Palette.outline : transparent;

        i-movable-touch-area := TouchArea {
            width: 10px;

            moved => {
                if (self.pressed) {
                    adjust_size(self.mouse-x - self.pressed-x);
                }
            }
            mouse-cursor: ew-resize;
        }

        animate background { duration: 250ms; }
    }
}

component TableViewCell inherits Rectangle {
    clip: true;

    HorizontalLayout {
        padding-left: 16px;
        padding-right: 16px;

        @children
    }

    // border
    Rectangle {
        y: parent.height - self.height;
        width: 100%;
        height: 1px;
        background: Palette.outline;
    }
}

component TableViewRow inherits Rectangle {
    callback clicked <=> i-state-layer.clicked;
    callback pointer-event <=> i-state-layer.pointer-event;

    in property<bool> selected;
    out property<length> mouse-x <=> i-state-layer.mouse-x;
    out property<length> mouse-y <=> i-state-layer.mouse-y;

    min-height: max(42px, i-layout.min-height);

    i-state-layer := StateLayer {
        checked: root.selected;
        background: Palette.primary;
        selection-background: Palette.secondary-container;
        ripple-color: Palette.primary-ripple;
        has-ripple: true;
    }

    i-layout := HorizontalLayout {
       @children
    }

    states [
        selected when root.selected : {
            i-state-layer.background: Palette.secondary-container;
        }
    ]
}

export component StandardTableView {
    private property <length> item-height: i-scroll-view.viewport-height / rows.length;
    private property <length> current-item-y: i-scroll-view.viewport-y + current-row * item-height;
    private property <length> min-header-height: 42px;

    callback sort-ascending(int /* column-index */);
    callback sort-descending(int /* column-index */);
    callback row-pointer-event(int /* row-index */, PointerEvent /* event */, Point /* absolute mouse position */);

    in property <[[StandardListViewItem]]> rows;
    out property <int> current-sort-column: -1;
    in-out property <[TableColumn]> columns;
    in-out property<int> current-row: -1;

    min-width: 400px;
    min-height: 200px;
    horizontal-stretch: 1;
    vertical-stretch: 1;

    VerticalLayout {
        Rectangle {
            clip: true;
            vertical-stretch: 0;
            min-height: i-header-layout.min-height;

            i-header-layout := HorizontalLayout {
                padding-right: 20px;
                min-height: root.min-header-height;
                vertical-stretch: 0;

                for column[index] in root.columns : TableViewColumn {
                    sort-order: column.sort-order;
                    horizontal-stretch: column.horizontal-stretch;
                    min-width: max(column.min-width, column.width);
                    preferred-width: self.min-width;
                    max-width: (index < columns.length && column.width >= 1px) ? max(column.min-width, column.width) : 100000px;

                    Text {
                        vertical-alignment: center;
                        text: column.title;
                        font-weight: 900;
                        overflow: elide;
                    }

                    clicked => {
                        root.sort(index);
                    }

                    adjust-size(diff) => {
                        column.width = max(1px, self.width + diff);
                    }
                }
            }
        }

        i-scroll-view := ScrollView {
            vertical-stretch: 1;

            VerticalLayout {
                alignment: start;

                for row[idx] in root.rows : TableViewRow {
                    selected: idx == root.current-row;

                    for cell[index] in row : TableViewCell {
                        private property <bool> has_inner_focus;
                        horizontal-stretch: root.columns[index].horizontal-stretch;
                        min-width: max(columns[index].min-width, columns[index].width);
                        preferred-width: self.min-width;
                        max-width: (index < columns.length && columns[index].width >= 1px) ? max(columns[index].min-width, columns[index].width) : 100000px;

                        Rectangle {
                            Text {
                                width: 100%;
                                height: 100%;
                                overflow: elide;
                                vertical-alignment: center;
                                text: cell.text;
                            }
                        }
                    }

                    clicked => {
                        root.set-current-row(idx);
                    }

                    pointer-event(pe) => {
                        root.row-pointer-event(idx, pe, {
                            x: self.absolute-position.x + self.mouse-x - root.absolute-position.x,
                            y: self.absolute-position.y + self.mouse-y - root.absolute-position.y,
                        });
                    }
                }
            }
        }
    }

    FocusScope {
        key-pressed(event) => {
            if (event.text == Key.UpArrow) {
                root.set-current-row(root.current-row - 1);
                return accept;
            } else if (event.text == Key.DownArrow) {
                root.set-current-row(root.current-row + 1);
                return accept;
            }

            reject
        }
    }

    function sort(index: int) {
        if (root.current-sort-column != index) {
            root.columns[root.current-sort-column].sort-order = SortOrder.unsorted;
        }

        if(root.columns[index].sort-order == SortOrder.ascending) {
            root.columns[index].sort-order = SortOrder.descending;
            root.sort-descending(index);
        } else {
            root.columns[index].sort-order = SortOrder.ascending;
            root.sort-ascending(index);
        }

        root.current-sort-column = index;
    }

    public function set-current-row(index: int) {
        if(index < 0 || index >= rows.length) {
            return;
        }

        current-row = index;

        if(current-item-y < 0) {
            i-scroll-view.viewport-y += 0 - current-item-y;
        }

        if(current-item-y + item-height > i-scroll-view.visible-height) {
            i-scroll-view.viewport-y -= current-item-y + item-height - i-scroll-view.visible-height;
        }
    }
}