// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component TestCase inherits Window {
    in property input-type <=> text-input.input-type;
    out property text-width <=> text-input.min-width;
    out property text-height <=> text-input.min-height;
    out property <Point> cursor-position;

    forward-focus: text-input;

    text-input := TextInput {
        text: "iiiii";
        font-family: "Noto Sans Regular";
        cursor-position-changed(position) => {
            root.cursor-position = position;
        }
    }
}


/*
```rust
use i_slint_core::items::InputType;

let instance = TestCase::new().unwrap();

let clear_text_width = instance.get_text_width();
instance.set_input_type(InputType::Password);

// The characters used for password input should be wider than the "i" characters.
// Make sure this is respected by the implementation, otherwise the password input
// might be too narrow to show the password characters.
let password_text_width = instance.get_text_width();
assert!(password_text_width > clear_text_width, "{password_text_width} should be greater than {clear_text_width}");

use slint::private_unstable_api::re_exports::Key;
let float_eq = |a: f32, b: f32| (a - b).abs() < 0.1;

assert_eq!(instance.get_cursor_position().x, 0., "Cursor should be at 0");
for i in 1..5 {
    slint_testing::send_key_combo(&instance, [Key::RightArrow]);
    let cursor = instance.get_cursor_position().x;
    let expected = i as f32 * 7.2;
    assert!(float_eq(cursor, expected), "After {i} steps cursor should be at {cursor}, was {expected}");
}
```
*/
