// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

TestCase := Window {
    width: 64px;
    height: 64px;

    GridLayout {
        Rectangle { background: red; }
        Rectangle { background: green; }
        Rectangle { background: blue; }
    }
}
   
/*

```rust

let window = slint_testing::init_swr();
window.set_size(slint::PhysicalSize::new(64, 64));

let pattern = slint_testing::image_buffer("../../screenshot/rgb.png");

let instance = TestCase::new();
instance.show();

//slint_testing::save_screenshot("rgb.png", window.clone());

let screenshot = slint_testing::screenshot(window.clone());
assert_eq!(pattern.as_bytes(), screenshot.as_bytes());

let line_screenshot = slint_testing::screenshot_render_by_line(window.clone());
assert_eq!(pattern.as_bytes(), line_screenshot.as_bytes());

```

*/
    