# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "slint-demos"
BBFILE_PATTERN_slint-demos = "^${LAYERDIR}/"
BBFILE_PRIORITY_slint-demos = "10"

LAYERDEPENDS_slint-demos = "core openembedded-layer"
LAYERSERIES_COMPAT_slint-demos = "scarthgap walnascar whinlatter wrynose"
