#!/usr/bin/env bash
# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

# MISE description="Run xtask check reuse compliance on all files"

set -e

if test ! -d "target" ; then
  cargo xtask check_reuse_compliance
fi
