# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

packages:
  - api/node
  - editors/vscode
  - tools/figma-inspector
  - tools/slintpad
  - demos/printerdemo/node
  - demos/home-automation/node
  - examples/imagefilter/node
  - examples/carousel/node
  - examples/todo/node
  - examples/memory
  - docs/astro
  - docs/common
  - ui-libraries/material/docs

catalog:
  knip: 5.86.0
  '@astrojs/check': 0.9.8
  '@astrojs/starlight': 0.38.2
  '@biomejs/biome': 2.4.8
  '@expressive-code/plugin-line-numbers': 0.41.7
  '@playwright/test': 1.58.2
  '@types/node': 24.12.0
  astro: 6.0.8
  astro-embed: 0.12.0
  cspell: 9.7.0
  playwright-ctrf-json-reporter: 0.0.29
  rehype-external-links: 3.0.0
  sharp: 0.34.5
  starlight-links-validator: 0.20.1
  typescript: 5.9.3
  vite: 8.0.1
  vitest: 4.1.0
