// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

//! Internal helpers used by code generated by the Slint SC compiler.
//!
//! **This module is not part of the public API.**  Its contents may change
//! between patch releases without notice.  User code must not import anything
//! from here directly; the compiler is the only client.

pub mod property;
pub mod renderer;

pub use property::Property;
pub use renderer::{PixelFormat, StaticTexture, draw_static_texture, fill_rectangle};
