// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { PushButton, CheckBox, Label } from "../common.slint";
import { PrinterQueue } from "../printer_queue.slint";
import { Page } from "./page.slint";
import { SpinBox } from "../components/spinbox.slint";
import { ComboBox } from "../components/combobox.slint";


export component CopyPage inherits Page {
    header: @tr("Copy");
    subtitle: @tr("Choose Settings");

    GridLayout {
        padding-top: 46px /* header line height in design */
                     + /* extra top-padding in design */ 27px;
        spacing: 24px;
        Row {
            SpinBox {
                value: 1;
                minimum: 1;
                label: @tr("Copies");
            }

            Rectangle {}

            ComboBox {
                value: @tr("DIN A4");
                label: @tr("Size");
            }
        }
        Row {
            ComboBox {
                value: @tr("Portrait");
                label: @tr("Layout");
            }

            Rectangle {}

            ComboBox {
                value: @tr("Special Tray");
                label: @tr("Paper Tray");
            }
        }
        Row {
            ComboBox {
                value: @tr("Best");
                label: @tr("Quality");
            }

            Rectangle {}

            ComboBox {
                value: @tr("Standard");
                label: @tr("Paper Type");
            }
        }
        Row {
            ComboBox {
                value: @tr("Grayscale");
                label: @tr("Color");
            }

            Rectangle {}

            Label { text: @tr("Paper Handling"); }
            CheckBox {
                checked: true;
                text: @tr("Sort Pages");
            }
        }
        Row {
            HorizontalLayout {
                col: 3;
                colspan: 2;

                Rectangle {
                    horizontal-stretch: 0;
                    width: 10%;
                }
                PushButton {
                    icon: @image-url("../images/copy.svg");
                    text: @tr("Start copying");
                    clicked => {
                        PrinterQueue.start-job(@tr("Copy"));
                    }
                }
                Rectangle {
                    horizontal-stretch: 0;
                    width: 10%;
                }
            }
        }
        Row { Rectangle {} }
    }
}
