// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { PrinterQueue } from "../printer_queue.slint";
import { Page } from "./page.slint";
import { SpinBox } from "../components/spinbox.slint";
import { ComboBox } from "../components/combobox.slint";
import { TextButton } from "../components/text_button.slint";
import { IconTextButton } from "../components/icon_text_button.slint";
import { DemoPalette } from "../common.slint";

export component ScanPage inherits Page {
    header: @tr("Scan");
    subtitle: @tr("Choose Settings");

    GridLayout {
        padding: 20px;
        spacing: 20px;
        width: parent.width;

        property <length> item-width: (parent.width - self.spacing - self.padding * 2) / 2;

        Row {
            SpinBox {
                width: self.preferred-width;
                value: 1;
                minimum: 1;
                label: @tr("Copies");
            }

            TextButton {
                property <bool> is-color: true;
                width: item-width;
                text: is-color ? @tr("Color") : @tr("Grayscale");
                background: is-color ? DemoPalette.color-button-gradient : DemoPalette.grayscale-button-gradient;

                clicked => {
                    is-color = !is-color;
                }
            }
        }
        Row {
            ComboBox {
                width: item-width;
                value: @tr("Best");
                label: @tr("Quality");
            }

            ComboBox {
                width: item-width;
                value: @tr("PDF");
                label: @tr("Format");
            }
        }
        Row {
            ComboBox {
                width: item-width;
                value: @tr("A4");
                label: @tr("Paper Size");
            }

            ComboBox {
                width: item-width;
                value: @tr("Portrait");
                label: @tr("Layout");
            }
        }
        Row {
            IconTextButton {
                colspan: 2;
                icon: @image-url("../images/scan.svg");
                text: @tr("Start scanning");
                background: green;
                height: 70px;
                icon-color: white;
                text-color: white;
                clicked => {
                    PrinterQueue.start-job(@tr("Scan"));
                }
            }
        }
    }
}
