// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { CheckBox, Label, DemoPalette } from "../common.slint";
import { Page } from "./page.slint";
import { ComboBox } from "../components/combobox.slint";

export global PrinterSettings {
    callback change-language(int);
}

export component SettingsPage inherits Page {
    header: @tr("Settings");
    subtitle: @tr("General");

    GridLayout {
        padding-top: 46px /* header line height in design */
                     + /* extra top-padding in design */ 27px;
        spacing: 24px;
        Row {
            Text {
                colspan: 4;
                text: @tr("General");
                color: DemoPalette.secondary-foreground-color;
                font-size: DemoPalette.base-font-size * 1.125;
                font-weight: 800;
            }
        }
        Row {
            Label { text: @tr("TURBO mode"); }
            CheckBox { checked: true; }

            Rectangle {}

            Label { text: @tr("Power Management"); }
            CheckBox {
                checked: false;
                text: @tr("Eco Mode");
            }
        }

        Row {
            Text {
                colspan: 4;
                text: @tr("Defaults");
                color: DemoPalette.secondary-foreground-color;
                font-size: DemoPalette.base-font-size * 1.125;
                font-weight: 800;
            }
        }
        Row {
            Label { text: @tr("Layout"); }
            ComboBox {
                value: @tr("Portrait");
            }

            Rectangle {}

            Label { text: @tr("Paper Tray"); }
            ComboBox {
                value: @tr("Special Tray");
            }
        }
        Row {
            Label { text: @tr("Quality"); }
            ComboBox {
                value: @tr("Best");
            }

            Rectangle {}

            Label { text: @tr("Language"); }
            ComboBox {
                value: @tr("English");
            }
        }
        Row {
            Label { text: @tr("Color Mode"); }
            ComboBox {
                value: @tr("Grayscale");
            }

            Rectangle {}

            Label { text: @tr("Paper Handling"); }
            CheckBox {
                checked: true;
                text: @tr("Sort Pages");
            }
        }
        Row { Rectangle {} }
    }

}
