// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import {
    VerticalBox,
    HorizontalBox,
    Button,
    LineEdit,
} from "std-widgets.slint";

import { Webview } from "../src/webview/webview.slint";
import { MobileMenuContent } from "mobile_menu.slint";

export { WebviewLogic } from "../src/webview/webview.slint";
export { Palette } from "std-widgets.slint";


export component MyApp inherits Window {
    preferred-width: 1224px;
    preferred-height: 768px;

    // On mobile (e.g. iOS/Android) safe-area-insets.top is non-zero.
    property <bool> is-mobile: root.safe-area-insets.top > 0px;

    menu := PopupWindow {
        x: root.width - 100px - root.safe-area-insets.right - 8px;
        y: root.safe-area-insets.top + 50px;
        width: 100px;
        height: 160px;
        close-policy: close-on-click;

        MobileMenuContent {
            back => {
                webview.back();
            }
            forward => {
                webview.forward();
            }
            reload => {
                webview.reload();
            }
            go => {
                webview.loadUrl(lineEdit.text);
            }
        }
    }

    VerticalBox {
        padding-left: root.safe-area-insets.left;
        padding-top: root.safe-area-insets.top;
        padding-right: root.safe-area-insets.right;
        padding-bottom: root.safe-area-insets.bottom;

        HorizontalBox {
            height: 50px;
            padding: 8px;
            spacing: 8px;

            if !root.is-mobile: Button {
                text: "Back";
                clicked => {
                    webview.back();
                }
            }

            if !root.is-mobile: Button {
                text: "Forward";
                clicked => {
                    webview.forward();
                }
            }

            if !root.is-mobile: Button {
                text: "Reload";
                clicked => {
                    webview.reload();
                }
            }

            lineEdit := LineEdit {
                text: webview.current_url;
                horizontal-stretch: 1;
                accepted(url) => {
                    webview.loadUrl(lineEdit.text);
                }
            }

            if !root.is-mobile: Button {
                text: "Go";
                clicked => {
                    webview.loadUrl(lineEdit.text);
                }
            }

            if root.is-mobile: Button {
                text: "...";
                clicked => {
                    menu.show();
                }
            }
        }

        Rectangle {
            webview := Webview {
                width: 100%;
                height: 100%;
                changed current_url => {
                    lineEdit.text = self.current_url;
                }
            }
        }
    }
}
