// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Palette } from "std-widgets.slint";

export component MenuItem inherits Rectangle {
    in property <string> label;
    callback clicked;

    border-radius: 8px;
    background: touch.pressed ? Palette.accent-background.transparentize(0.5) : touch.has-hover ? Palette.control-background : transparent;

    animate background { duration: 80ms; }

    touch := TouchArea {
        clicked => {
            root.clicked();
        }
    }

    Text {
        text: root.label;
        x: 16px;
        font-size: 16px;
        vertical-alignment: center;
        color: Palette.foreground;
    }
}

export component MobileMenuContent inherits Rectangle {
    callback back();
    callback forward();
    callback reload();
    callback go();

    width: 120px;
    height: 4 * 48px;
    background: Palette.background;

    border-width: 1px;
    border-color: Palette.border;
    border-radius: 8px;

    VerticalLayout {
        padding: 8px;
        spacing: 8px;

        MenuItem {
            label: "Back";
            clicked => root.back();
        }

        MenuItem {
            label: "Forward";
            clicked => root.forward();
        }

        MenuItem {
            label: "Reload";
            clicked => root.reload();
        }

        MenuItem {
            label: "Go";
            clicked => root.go();
        }
    }
}
