// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

import { CosmicFontSettings, CosmicPalette } from "styling.slint";

export component GroupBox {
    in property <string> title <=> label.text;
    in property <bool> enabled: true;

    VerticalLayout {
        spacing: 8px;
        padding-top: 16px;
        padding-bottom: 8px;

        label := Text {
            vertical-stretch: 0;
            color: !root.enabled ? CosmicPalette.text-disabled : CosmicPalette.control-foreground;
            font-size: CosmicFontSettings.body-strong.font-size;
            font-weight: CosmicFontSettings.body-strong.font-weight;
        }

        Rectangle {
            vertical-stretch: 1;
            background: CosmicPalette.alternate-background;
            border-radius: 8px;

            GridLayout {
                padding: 8px;

                @children
            }
        }
    }
}
