// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

struct Foo := {
    ok: bool,
}

// Make sure that the generated code for this compiles, as we emit
// #[derive(Debug)] for structures and in this case the field of the
// struct contains a model handle.
struct Bar := {
    foos: [Foo],
}

TestCase := Rectangle {
    property <[Bar]> bars: [];

    // make sure the generated code compiles (that we generate .clone() properly)
    property <Foo> foo: {ok: true};
    property <Bar> bar: {foos: [foo, foo]};
    property <[Bar]> bars2: [bar, bar];
}
