// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { DemoPalette, Theme, PrinterState } from "common.slint";
import {
    HomePage,
    InkLevel,
    InkPage,
    SettingsPage,
    PrinterSettings,
} from "./pages/pages.slint";
import { PrinterQueue } from "./printer_queue.slint";

// re-export for the native code
export { PrinterQueue, PrinterSettings }

import "./fonts/NotoSans-Regular.ttf";
import "./fonts/NotoSans-Bold.ttf";
import { Sidebar } from "components/sidebar.slint";


export component MainWindow inherits Window {
    /// Note that this property is overwritten in the .cpp and .rs code.
    /// The data is only in this file so it looks good in the viewer
    in property <[InkLevel]> ink-levels: [
        { color: #0ff, level: 60% },
        { color: #ff0, level: 80% },
        { color: #f0f, level: 70% },
        { color: #000, level: 30% },
    ];

    callback quit();

    min-width: 772px;
    min-height: 504px;
    title: @tr("Slint printer demo");
    background: DemoPalette.primary;
    default-font-family: "Noto Sans";
    default-font-size: DemoPalette.base-font-size;

    HorizontalLayout {

        Sidebar { }

        main-view := Rectangle {

            if PrinterState.active-page == 0:home-page := HomePage {
                property <int> pageNumber: 0;
            }

            if PrinterState.active-page == 1:settings-page := SettingsPage {
                property <int> pageNumber: 1;
            }

            ink-page := InkPage {
                property <int> pageNumber: 2;
                ink-levels <=> root.ink-levels;
                visible: PrinterState.active-page == 2;
            }
        }
    }
}
