// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

// GENERATED. Do not edit by hand. See ffigen.yaml.
// ignore_for_file: always_specify_types, camel_case_types
// ignore_for_file: non_constant_identifier_names, unused_element
// ignore_for_file: public_member_api_docs

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for the slint-dart C ABI, generated from its header.
class SlintBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  SlintBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  SlintBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Release a string returned by any of the functions in this module.
  void freeString(
    ffi.Pointer<ffi.Char> s,
  ) {
    return _freeString(
      s,
    );
  }

  late final _freeStringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'slint_dart_free_string');
  late final _freeString =
      _freeStringPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Generate typed Dart bindings for a `.slint` file.
  ///
  /// The success envelope contains every file whose contents can affect the
  /// result, plus either generated source or a generation error. The Dart builder
  /// registers the dependencies before it reports the error so watch mode can
  /// recover when an imported file changes.
  ///
  /// # Safety
  /// `input_path`, `output_path`, and `options_json` must point to NUL-terminated strings.
  ffi.Pointer<ffi.Char> generate(
    ffi.Pointer<ffi.Char> input_path,
    ffi.Pointer<ffi.Char> output_path,
    ffi.Pointer<ffi.Char> options_json,
  ) {
    return _generate(
      input_path,
      output_path,
      options_json,
    );
  }

  late final _generatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('slint_dart_generate');
  late final _generate = _generatePtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// Create a compiler. Release it with [`slint_dart_compiler_free`].
  ffi.Pointer<SlintCompiler> compilerNew() {
    return _compilerNew();
  }

  late final _compilerNewPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<SlintCompiler> Function()>>(
          'slint_dart_compiler_new');
  late final _compilerNew =
      _compilerNewPtr.asFunction<ffi.Pointer<SlintCompiler> Function()>();

  /// # Safety
  /// `compiler` must come from [`slint_dart_compiler_new`] and not be used afterwards.
  void compilerFree(
    ffi.Pointer<SlintCompiler> compiler,
  ) {
    return _compilerFree(
      compiler,
    );
  }

  late final _compilerFreePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<SlintCompiler>)>>(
      'slint_dart_compiler_free');
  late final _compilerFree =
      _compilerFreePtr.asFunction<void Function(ffi.Pointer<SlintCompiler>)>();

  /// # Safety
  /// `compiler` must be a live compiler, `style` a NUL-terminated string.
  void compilerSetStyle(
    ffi.Pointer<SlintCompiler> compiler,
    ffi.Pointer<ffi.Char> style,
  ) {
    return _compilerSetStyle(
      compiler,
      style,
    );
  }

  late final _compilerSetStylePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<SlintCompiler>,
              ffi.Pointer<ffi.Char>)>>('slint_dart_compiler_set_style');
  late final _compilerSetStyle = _compilerSetStylePtr.asFunction<
      void Function(ffi.Pointer<SlintCompiler>, ffi.Pointer<ffi.Char>)>();

  /// # Safety
  /// `compiler` must be a live compiler, `path` a NUL-terminated string.
  void compilerAddIncludePath(
    ffi.Pointer<SlintCompiler> compiler,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _compilerAddIncludePath(
      compiler,
      path,
    );
  }

  late final _compilerAddIncludePathPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<SlintCompiler>,
              ffi.Pointer<ffi.Char>)>>('slint_dart_compiler_add_include_path');
  late final _compilerAddIncludePath = _compilerAddIncludePathPtr.asFunction<
      void Function(ffi.Pointer<SlintCompiler>, ffi.Pointer<ffi.Char>)>();

  /// Compile a `.slint` file. Inspect the result with
  /// [`slint_dart_result_diagnostics`] and [`slint_dart_result_component`]; it is
  /// null only if the compiler itself panicked.
  ///
  /// # Safety
  /// `compiler` must be a live compiler, `path` a NUL-terminated string.
  ffi.Pointer<SlintCompilationResult> buildFromPath(
    ffi.Pointer<SlintCompiler> compiler,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _buildFromPath(
      compiler,
      path,
    );
  }

  late final _buildFromPathPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<SlintCompilationResult> Function(
              ffi.Pointer<SlintCompiler>,
              ffi.Pointer<ffi.Char>)>>('slint_dart_compiler_build_from_path');
  late final _buildFromPath = _buildFromPathPtr.asFunction<
      ffi.Pointer<SlintCompilationResult> Function(
          ffi.Pointer<SlintCompiler>, ffi.Pointer<ffi.Char>)>();

  /// Compile `.slint` source code. `path` is only used for diagnostics and to
  /// resolve relative imports. See [`slint_dart_compiler_build_from_path`].
  ///
  /// # Safety
  /// `compiler` must be a live compiler, `source` and `path` NUL-terminated strings.
  ffi.Pointer<SlintCompilationResult> buildFromSource(
    ffi.Pointer<SlintCompiler> compiler,
    ffi.Pointer<ffi.Char> source,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _buildFromSource(
      compiler,
      source,
      path,
    );
  }

  late final _buildFromSourcePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<SlintCompilationResult> Function(
              ffi.Pointer<SlintCompiler>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('slint_dart_compiler_build_from_source');
  late final _buildFromSource = _buildFromSourcePtr.asFunction<
      ffi.Pointer<SlintCompilationResult> Function(ffi.Pointer<SlintCompiler>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// # Safety
  /// `result` must come from a `build_from_*` call and not be used afterwards.
  void resultFree(
    ffi.Pointer<SlintCompilationResult> result,
  ) {
    return _resultFree(
      result,
    );
  }

  late final _resultFreePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<SlintCompilationResult>)>>('slint_dart_result_free');
  late final _resultFree = _resultFreePtr
      .asFunction<void Function(ffi.Pointer<SlintCompilationResult>)>();

  bool resultHasErrors(
    ffi.Pointer<SlintCompilationResult> result,
  ) {
    return _resultHasErrors(
      result,
    );
  }

  late final _resultHasErrorsPtr = _lookup<
          ffi.NativeFunction<
              ffi.Bool Function(ffi.Pointer<SlintCompilationResult>)>>(
      'slint_dart_result_has_errors');
  late final _resultHasErrors = _resultHasErrorsPtr
      .asFunction<bool Function(ffi.Pointer<SlintCompilationResult>)>();

  /// All diagnostics as a JSON array of
  /// `{"level": "error"|"warning", "message": …, "file": …, "line": …, "column": …}`.
  ffi.Pointer<ffi.Char> resultDiagnostics(
    ffi.Pointer<SlintCompilationResult> result,
  ) {
    return _resultDiagnostics(
      result,
    );
  }

  late final _resultDiagnosticsPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Char> Function(
                  ffi.Pointer<SlintCompilationResult>)>>(
      'slint_dart_result_diagnostics');
  late final _resultDiagnostics = _resultDiagnosticsPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<SlintCompilationResult>)>();

  /// The names of every component that can be instantiated, as a JSON array.
  ffi.Pointer<ffi.Char> resultComponentNames(
    ffi.Pointer<SlintCompilationResult> result,
  ) {
    return _resultComponentNames(
      result,
    );
  }

  late final _resultComponentNamesPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Char> Function(
                  ffi.Pointer<SlintCompilationResult>)>>(
      'slint_dart_result_component_names');
  late final _resultComponentNames = _resultComponentNamesPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<SlintCompilationResult>)>();

  /// Look up a component by name; a null `name` picks the last exported one.
  /// Returns null when there is no such component.
  ///
  /// # Safety
  /// `name` must be null or a NUL-terminated string.
  ffi.Pointer<SlintComponentDefinition> resultComponent(
    ffi.Pointer<SlintCompilationResult> result,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _resultComponent(
      result,
      name,
    );
  }

  late final _resultComponentPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<SlintComponentDefinition> Function(
              ffi.Pointer<SlintCompilationResult>,
              ffi.Pointer<ffi.Char>)>>('slint_dart_result_component');
  late final _resultComponent = _resultComponentPtr.asFunction<
      ffi.Pointer<SlintComponentDefinition> Function(
          ffi.Pointer<SlintCompilationResult>, ffi.Pointer<ffi.Char>)>();

  /// # Safety
  /// `definition` must come from [`slint_dart_result_component`] and not be used afterwards.
  void definitionFree(
    ffi.Pointer<SlintComponentDefinition> definition,
  ) {
    return _definitionFree(
      definition,
    );
  }

  late final _definitionFreePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<SlintComponentDefinition>)>>(
      'slint_dart_definition_free');
  late final _definitionFree = _definitionFreePtr
      .asFunction<void Function(ffi.Pointer<SlintComponentDefinition>)>();

  ffi.Pointer<ffi.Char> definitionName(
    ffi.Pointer<SlintComponentDefinition> definition,
  ) {
    return _definitionName(
      definition,
    );
  }

  late final _definitionNamePtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Char> Function(
                  ffi.Pointer<SlintComponentDefinition>)>>(
      'slint_dart_definition_name');
  late final _definitionName = _definitionNamePtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<SlintComponentDefinition>)>();

  /// The public API of the component, as
  /// `{"properties": {name: type}, "callbacks": [...], "functions": [...], "globals": [...]}`.
  ffi.Pointer<ffi.Char> definitionApi(
    ffi.Pointer<SlintComponentDefinition> definition,
  ) {
    return _definitionApi(
      definition,
    );
  }

  late final _definitionApiPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Char> Function(
                  ffi.Pointer<SlintComponentDefinition>)>>(
      'slint_dart_definition_api');
  late final _definitionApi = _definitionApiPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<SlintComponentDefinition>)>();

  /// Instantiate the component. Returns null on failure, with the reason written
  /// to `error` (release it with [`slint_dart_free_string`]).
  ///
  /// # Safety
  /// `error` must be a valid pointer to a `*mut c_char`.
  ffi.Pointer<SlintComponentInstance> definitionCreate(
    ffi.Pointer<SlintComponentDefinition> definition,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error,
  ) {
    return _definitionCreate(
      definition,
      error,
    );
  }

  late final _definitionCreatePtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<SlintComponentInstance> Function(
                  ffi.Pointer<SlintComponentDefinition>,
                  ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'slint_dart_definition_create');
  late final _definitionCreate = _definitionCreatePtr.asFunction<
      ffi.Pointer<SlintComponentInstance> Function(
          ffi.Pointer<SlintComponentDefinition>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// # Safety
  /// `instance` must come from [`slint_dart_definition_create`] and not be used afterwards.
  void instanceFree(
    ffi.Pointer<SlintComponentInstance> instance,
  ) {
    return _instanceFree(
      instance,
    );
  }

  late final _instanceFreePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<SlintComponentInstance>)>>(
      'slint_dart_instance_free');
  late final _instanceFree = _instanceFreePtr
      .asFunction<void Function(ffi.Pointer<SlintComponentInstance>)>();

  /// Read a property. Pass a non-null `global` to read it from a global singleton.
  ///
  /// # Safety
  /// `global` must be null or NUL-terminated, `name` NUL-terminated.
  ffi.Pointer<ffi.Char> getProperty(
    ffi.Pointer<SlintComponentInstance> instance,
    ffi.Pointer<ffi.Char> global,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _getProperty(
      instance,
      global,
      name,
    );
  }

  late final _getPropertyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<SlintComponentInstance>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('slint_dart_instance_get_property');
  late final _getProperty = _getPropertyPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<SlintComponentInstance>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// Write a property from its JSON representation. Pass a non-null `global` to
  /// write it into a global singleton.
  ///
  /// # Safety
  /// `global` must be null or NUL-terminated, `name` and `json` NUL-terminated.
  ffi.Pointer<ffi.Char> setProperty(
    ffi.Pointer<SlintComponentInstance> instance,
    ffi.Pointer<ffi.Char> global,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> json,
  ) {
    return _setProperty(
      instance,
      global,
      name,
      json,
    );
  }

  late final _setPropertyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<SlintComponentInstance>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('slint_dart_instance_set_property');
  late final _setProperty = _setPropertyPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<SlintComponentInstance>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  /// Call a callback or a public function with a JSON array of arguments, and
  /// return its result. Pass a non-null `global` to reach into a global singleton.
  ///
  /// # Safety
  /// `global` must be null or NUL-terminated, `name` and `args_json` NUL-terminated.
  ffi.Pointer<ffi.Char> invoke(
    ffi.Pointer<SlintComponentInstance> instance,
    ffi.Pointer<ffi.Char> global,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> args_json,
  ) {
    return _invoke(
      instance,
      global,
      name,
      args_json,
    );
  }

  late final _invokePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<SlintComponentInstance>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('slint_dart_instance_invoke');
  late final _invoke = _invokePtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<SlintComponentInstance>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  /// Install a Dart handler for a callback. Pass a non-null `global` to reach
  /// into a global singleton.
  ///
  /// # Safety
  /// `global` must be null or NUL-terminated and `name` NUL-terminated.
  /// `callback` and `free_result` must stay valid, and `user_data` must stay
  /// meaningful, until the instance is destroyed.
  ffi.Pointer<ffi.Char> setCallback(
    ffi.Pointer<SlintComponentInstance> instance,
    ffi.Pointer<ffi.Char> global,
    ffi.Pointer<ffi.Char> name,
    DartCallback callback,
    DartFree free_result,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _setCallback(
      instance,
      global,
      name,
      callback,
      free_result,
      user_data,
    );
  }

  late final _setCallbackPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<SlintComponentInstance>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              DartCallback,
              DartFree,
              ffi.Pointer<ffi.Void>)>>('slint_dart_instance_set_callback');
  late final _setCallback = _setCallbackPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<SlintComponentInstance>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          DartCallback,
          DartFree,
          ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Char> instanceShow(
    ffi.Pointer<SlintComponentInstance> instance,
    bool visible,
  ) {
    return _instanceShow(
      instance,
      visible,
    );
  }

  late final _instanceShowPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<SlintComponentInstance>,
              ffi.Bool)>>('slint_dart_instance_show');
  late final _instanceShow = _instanceShowPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<SlintComponentInstance>, bool)>();

  /// Show the window and run the event loop until the last window closes or
  /// [`slint_dart_quit_event_loop`] is called.
  ffi.Pointer<ffi.Char> instanceRun(
    ffi.Pointer<SlintComponentInstance> instance,
  ) {
    return _instanceRun(
      instance,
    );
  }

  late final _instanceRunPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<SlintComponentInstance>)>>('slint_dart_instance_run');
  late final _instanceRun = _instanceRunPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<SlintComponentInstance>)>();

  ffi.Pointer<ffi.Char> runEventLoop() {
    return _runEventLoop();
  }

  late final _runEventLoopPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'slint_dart_run_event_loop');
  late final _runEventLoop =
      _runEventLoopPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  void quitEventLoop() {
    return _quitEventLoop();
  }

  late final _quitEventLoopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'slint_dart_quit_event_loop');
  late final _quitEventLoop = _quitEventLoopPtr.asFunction<void Function()>();

  /// Start a timer. Release it with [`slint_dart_timer_free`], which also stops it.
  ///
  /// # Safety
  /// `callback` must stay valid, and `user_data` meaningful, until the returned
  /// timer is freed.
  ffi.Pointer<SlintTimerHandle> timerStart(
    bool repeated,
    int interval_ms,
    ffi.Pointer<
            ffi
            .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> user_data)>>
        callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _timerStart(
      repeated,
      interval_ms,
      callback,
      user_data,
    );
  }

  late final _timerStartPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<SlintTimerHandle> Function(
              ffi.Bool,
              ffi.Uint64,
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Void Function(ffi.Pointer<ffi.Void> user_data)>>,
              ffi.Pointer<ffi.Void>)>>('slint_dart_timer_start');
  late final _timerStart = _timerStartPtr.asFunction<
      ffi.Pointer<SlintTimerHandle> Function(
          bool,
          int,
          ffi.Pointer<
              ffi.NativeFunction<
                  ffi.Void Function(ffi.Pointer<ffi.Void> user_data)>>,
          ffi.Pointer<ffi.Void>)>();

  /// # Safety
  /// `timer` must come from [`slint_dart_timer_start`] and not be used afterwards.
  void timerFree(
    ffi.Pointer<SlintTimerHandle> timer,
  ) {
    return _timerFree(
      timer,
    );
  }

  late final _timerFreePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<SlintTimerHandle>)>>(
      'slint_dart_timer_free');
  late final _timerFree =
      _timerFreePtr.asFunction<void Function(ffi.Pointer<SlintTimerHandle>)>();

  /// Install the software renderer as the Slint platform.
  ///
  /// Must be called before the first component is instantiated, and only makes
  /// sense once per thread; calling it again is a no-op.
  ffi.Pointer<ffi.Char> embeddedInit() {
    return _embeddedInit();
  }

  late final _embeddedInitPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'slint_dart_embedded_init');
  late final _embeddedInit =
      _embeddedInitPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Resize the surface. `width` and `height` are physical pixels; `scale_factor`
  /// maps them to the logical pixels the `.slint` code sizes itself in.
  ffi.Pointer<ffi.Char> embeddedResize(
    int width,
    int height,
    double scale_factor,
  ) {
    return _embeddedResize(
      width,
      height,
      scale_factor,
    );
  }

  late final _embeddedResizePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Uint32, ffi.Uint32,
              ffi.Float)>>('slint_dart_embedded_resize');
  late final _embeddedResize = _embeddedResizePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int, int, double)>();

  /// Draw the current frame into `buffer`, which must hold `width * height`
  /// RGBA pixels with premultiplied alpha — the layout Flutter's
  /// `PixelFormat.rgba8888` expects.
  ///
  /// Returns true when something was drawn. The renderer only repaints what
  /// changed, so pass the same buffer every frame and keep its contents between
  /// calls.
  ///
  /// # Safety
  /// `buffer` must point to at least `width * height * 4` writable bytes.
  bool embeddedRender(
    ffi.Pointer<ffi.Uint8> buffer,
    int width,
    int height,
  ) {
    return _embeddedRender(
      buffer,
      width,
      height,
    );
  }

  late final _embeddedRenderPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<ffi.Uint8>, ffi.Uint32,
              ffi.Uint32)>>('slint_dart_embedded_render');
  late final _embeddedRender = _embeddedRenderPtr
      .asFunction<bool Function(ffi.Pointer<ffi.Uint8>, int, int)>();

  /// Advance Slint's timers and animations, and report how long the caller may
  /// idle before the next update is due: milliseconds, or -1 when nothing is
  /// pending.
  int embeddedTick() {
    return _embeddedTick();
  }

  late final _embeddedTickPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
          'slint_dart_embedded_tick');
  late final _embeddedTick = _embeddedTickPtr.asFunction<int Function()>();

  /// True when an animation is running, so the caller should keep drawing frames.
  bool embeddedHasActiveAnimations() {
    return _embeddedHasActiveAnimations();
  }

  late final _embeddedHasActiveAnimationsPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
          'slint_dart_embedded_has_active_animations');
  late final _embeddedHasActiveAnimations =
      _embeddedHasActiveAnimationsPtr.asFunction<bool Function()>();

  /// Deliver a pointer event at logical position (`x`, `y`).
  ///
  /// `kind` is 0 for pressed, 1 for released, 2 for moved, 3 for scrolled, and 4
  /// when the pointer left the surface; `PointerEventKind` on the Dart side names
  /// the same numbers. `button` is 0 for left, 1 for right, 2 for middle, and is
  /// ignored by the kinds that don't have one. `delta_x` and `delta_y` only apply
  /// to scroll events.
  ffi.Pointer<ffi.Char> embeddedPointerEvent(
    int kind,
    double x,
    double y,
    int button,
    double delta_x,
    double delta_y,
  ) {
    return _embeddedPointerEvent(
      kind,
      x,
      y,
      button,
      delta_x,
      delta_y,
    );
  }

  late final _embeddedPointerEventPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Uint32,
              ffi.Float,
              ffi.Float,
              ffi.Uint32,
              ffi.Float,
              ffi.Float)>>('slint_dart_embedded_pointer_event');
  late final _embeddedPointerEvent = _embeddedPointerEventPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          int, double, double, int, double, double)>();

  /// Deliver a key event. `kind` is 0 for pressed, 1 for repeated, 2 for
  /// released. `text` is the key's unicode text; Slint's non-printable keys are
  /// the private-use characters listed in its `Key` enum, which the Dart side
  /// maps for you.
  ///
  /// # Safety
  /// `text` must be a NUL-terminated string.
  ffi.Pointer<ffi.Char> embeddedKeyEvent(
    int kind,
    ffi.Pointer<ffi.Char> text,
  ) {
    return _embeddedKeyEvent(
      kind,
      text,
    );
  }

  late final _embeddedKeyEventPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Uint32,
              ffi.Pointer<ffi.Char>)>>('slint_dart_embedded_key_event');
  late final _embeddedKeyEvent = _embeddedKeyEventPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)>();

  /// Tell Slint whether the surface has keyboard focus, so that text cursors
  /// blink and selections render the way the platform expects.
  ffi.Pointer<ffi.Char> embeddedFocusEvent(
    bool focused,
  ) {
    return _embeddedFocusEvent(
      focused,
    );
  }

  late final _embeddedFocusEventPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Bool)>>(
          'slint_dart_embedded_focus_event');
  late final _embeddedFocusEvent =
      _embeddedFocusEventPtr.asFunction<ffi.Pointer<ffi.Char> Function(bool)>();

  /// The renderer's current buffer size in physical pixels, as `{"width": …,
  /// "height": …}`. Useful to check what a resize actually took effect as.
  ffi.Pointer<ffi.Char> embeddedSize() {
    return _embeddedSize();
  }

  late final _embeddedSizePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'slint_dart_embedded_size');
  late final _embeddedSize =
      _embeddedSizePtr.asFunction<ffi.Pointer<ffi.Char> Function()>();
}

final class SlintCompiler extends ffi.Opaque {}

final class SlintCompilationResult extends ffi.Opaque {}

final class SlintComponentDefinition extends ffi.Opaque {}

final class SlintComponentInstance extends ffi.Opaque {}

final class SlintTimerHandle extends ffi.Opaque {}

typedef DartCallbackFunction = ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Void> user_data, ffi.Pointer<ffi.Char> args_json);

/// The Dart handler for a Slint callback.
///
/// It receives the arguments as a JSON array and returns the result as a JSON
/// string it allocated itself, or null for a void callback. This module hands
/// that string straight back to `free_result` once it has been read, so the
/// two sides never free each other's allocations.
typedef DartCallback = ffi.Pointer<ffi.NativeFunction<DartCallbackFunction>>;
typedef DartFreeFunction = ffi.Void Function(ffi.Pointer<ffi.Char> s);
typedef DartDartFreeFunction = void Function(ffi.Pointer<ffi.Char> s);

/// Releases a string returned by a [`DartCallback`].
typedef DartFree = ffi.Pointer<ffi.NativeFunction<DartFreeFunction>>;
