# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/**
  language:
    strict-casts: true
    strict-raw-types: true
