# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

builders:
  slint:
    import: "package:slint_generator/builder.dart"
    builder_factories: ["slintBuilder"]
    build_extensions: {".slint": [".slint.dart"]}
    auto_apply: root_package
    build_to: source
