# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

name: slint_generator
description: The build_runner builder that generates a typed Dart API for each .slint file.
version: 1.18.0
homepage: https://slint.dev
repository: https://github.com/slint-ui/slint
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  build: '>=2.4.1 <5.0.0'
  path: ^1.8.0
  slint:
    path: ../slint

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
