// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

export Xxx := Rectangle {

    foo := Rectangle {
        callback hello(int) -> int;
    }

    callback plop(int) -> int <=> foo.hello;
    //                        ^error{When declaring a callback alias, one must omit parentheses. e.g. 'callback foo <=> other.bar;'}

    callback plopsi() <=> foo.hello;
    //                ^error{When declaring a callback alias, one must omit parentheses. e.g. 'callback foo <=> other.bar;'}

}
