// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

export global Icons {
    out property <image> calendar_today: @image-url("calendar_today.svg");
    out property <image> check: @image-url("check.svg");
    out property <image> close: @image-url("close.svg");
    out property <image> chevron_backward: @image-url("chevron_backward.svg");
    out property <image> chevron_forward: @image-url("chevron_forward.svg");
    out property <image> edit: @image-url("edit.svg");
    out property <image> menu: @image-url("menu.svg");
    out property <image> arrow_back: @image-url("arrow_back.svg");
    out property <image> arrow_right: @image-url("arrow_right.svg");
    out property <image> arrow_drop_down: @image-url("arrow_drop_down.svg");
    out property <image> arrow_drop_up: @image-url("arrow_drop_up.svg");
    out property <image> remove: @image-url("remove.svg");
    out property <image> schedule: @image-url("schedule.svg");
    out property <image> keyboard: @image-url("keyboard.svg");
}
