// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

component T{function r@tr""|
//                    ^error{Syntax error: expected '\('}
//                    ^^error{Syntax error: expected '\{'}
//                       ^^^error{Syntax error: expected '\('}

  ""}}}
//  ^error{Syntax error: expected '%'}
//    ^^error{Parse error: expected a top-level item such as a component, a struct, or a global}