// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

Compo1:=R{property<int b;function bb)i{}}c:=Compo1{b:self.bb
//    ^warning{':=' to declare a component is deprecated. The new syntax declare components with 'component MyComponent {'. Read the documentation for more info}
//                     ^^error{Syntax error: expected '>'}
//                                  ^^^error{Syntax error: expected '('}
//                                  ^^^^error{Syntax error: expected '{'}
//                                  ^^^^^error{invalid expression}
//                                  ^^^^^^error{Syntax error: expected '}'}
//                                  ^^^^^^^error{Parse error}
//                                        ^^^^^^^^warning{':=' to declare a component is deprecated. The new syntax declare components with 'component MyComponent {'. Read the documentation for more info}

   }
// ^error{Syntax error: expected ';'}
    /**/
