// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

OtherComp:=Rectangle{
    out property<string> t <=>t;
    text :=Text {  }
}

export ae:=Rectangle{
    OtherComp { t<=>t;}
//              ^error{Property cannot alias to itself}
//              ^^warning{Assigning to output property 't' is deprecated}
}