// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { SpinBox, Button, CheckBox, Slider, GroupBox, StandardListView, GridBox } from "std-widgets.slint";
import { Label, Page, Preview } from "common.slint";

component PrintPage inherits Page {

     layout := GridLayout {
        padding-left: 40px;
        padding-right: 40px;
        spacing: 20px;
        padding-top: 20px;
        padding-bottom: 20px;

        Row {
            preview := Preview { }
            GridBox {
                Row {
                    Label {
                        text: "Select File:";
                    }
                }

                Row {
                    StandardListView {
                        model: [
                            { text: ".." },
                            { text: "cat.jpg" },
                            { text: "dog.jpg" },
                            { text: "elephant.jpg" },
                            { text: "snake.jpg" },
                        ];
                    }
                }

                Row {
                    Label {
                        text: "Copies:";
                    }
                }

                Row {
                    SpinBox {
                        horizontal-stretch: 1;
                    }
                }
                Row {
                    Button {
                        text: "Print Page";
                        horizontal-stretch: 1;
                    }
                }
            }
        }
    }
}
