# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

name: todo
description: The Slint todo example, as a Flutter application written in Dart.
version: 1.18.0
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  slint_flutter:
    path: ../../../api/flutter/slint_flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
