// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export App := Rectangle {

    Rectangle {
        x: inner.absolute-position.x > 10px ? 10px : 0px;
//         ^error{The binding for the property 'x' is part of a binding loop}
        inner := Rectangle {
//               ^error{The binding for the property 'absolute-position' is part of a binding loop}
        }
    }

}
