// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// Issue #2902

import { HorizontalBox, VerticalBox } from "std-widgets.slint";

export component MainWindow inherits Window {
//                                   ^error{The binding for the property 'layoutinfo-h' is part of a binding loop}

    HorizontalBox {
//  ^error{The binding for the property 'width' is part of a binding loop}
//  ^^error{The binding for the property 'layoutinfo-h' is part of a binding loop}

        VerticalBox {

            width: parent.width;
//                 ^error{The binding for the property 'width' is part of a binding loop}
            //height: parent.height;
            Text {
                text: "Test";
            }
        }
    }
}