// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

Wrap := Rectangle {
//   ><warning{':=' to declare a component is deprecated. The new syntax declare components with 'component MyComponent {'. Read the documentation for more info}
    property woo <=> text.wrap;

    VerticalLayout {
        HorizontalLayout {
            text := Text {
                text: "Hello World";
            }
            square := Rectangle {
                width: height;
//                     >     <error{The binding for the property 'width' is part of a binding loop (square.width -> HorizontalLayout.layout-cache -> text.width -> HorizontalLayout.layoutinfo-v -> VerticalLayout.layout-cache -> HorizontalLayout.height -> square.height -> square.width)}
                background: violet;
            }
        }
        Rectangle {}
    }
    property <bool> test: square.width == square.height;
}

export Test := Window {
//          ><warning{':=' to declare a component is deprecated. The new syntax declare components with 'component MyComponent {'. Read the documentation for more info}

    property <image> source;
    GridLayout {


        Image {
            source: root.source;
        }
        Rectangle {
            width: height;
//                 >     <warning{The binding for the property 'width' is part of a binding loop (root.layoutinfo-h -> GridLayout.width -> GridLayout.layout-cache-h -> Image.width -> GridLayout.layoutinfo-v -> root.layoutinfo-v -> GridLayout.height -> GridLayout.layout-cache-v -> Rectangle.height -> Rectangle.width -> GridLayout.layoutinfo-h -> root.layoutinfo-h)↵This was allowed in previous version of Slint, but is deprecated and may cause panic at runtime}
        }
    }

    w := Wrap { }
    callback set_wrap();
    set_wrap => { w.woo = TextWrap.word-wrap; }

}
