// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// Issue 10342

export component MyPanel {
    fb := Image {
        width: 100%;
        source-clip-width: root.width / 0.531px;
        source-clip-height: root.height / 0.531px;
//                          >                    <error{The binding for the property 'source-clip-height' is part of a binding loop (MyPanel.height -> fb.source-clip-height -> MyPanel.layoutinfo-v -> MyPanel.preferred-height -> MyPanel.height)}
    }

}

export component MainWindow inherits Window {
    MyPanel {
        x: 30px;
        y: 30px;
        width: 200px;
    }
}
