// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component DragOutlineCases inherits Window {
    width: 640px;
    height: 480px;
    background: white;

    empty-image := Image {
        x: 48px;
        y: 48px;
        width: 128px;
        height: 96px;
    }

    touch-area := TouchArea {
        x: 240px;
        y: 48px;
        width: 128px;
        height: 96px;
    }
}
