// Copyright © 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nicholas Turner <nicholas.turner@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component Foo {
    in-out property <int> foo: 0;
    match (foo)
        0: Rectangle { }
//      ^error{Expected '{' to start cases}
        1: Rectangle { }
        *: Rectangle { }
    }
}

export component Bar {
    in-out property <int> foo: 0;
    match foo
        0: Rectangle { }
//      ^error{Expected '{' to start cases}
    }
}

export component Baz {
    in-out property <int> foo: 0;
    match foo {
        0: Rectangle { }
        1: Rectangle { }
        *: Rectangle { }

    property<int> xx;
//  >      <error{Syntax error: expected '}'}
}

export component Qux {
    in-out property <int> foo: 0;
    match foo {
        0: { Rectangle { } }
//           >       <error{Remove '{ }' around case element}
    }
}