// Copyright © 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nicholas Turner <nicholas.turner@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

enum Nums {
    one,
    two,
    three,
}

export component ExhaustiveEnum {
    in-out property <Nums> num: one;

    match num {
        one: Rectangle { }
        two: Rectangle { }
        three: Rectangle { }
    }
}

export component NonExhaustiveEnum {
    in-out property <Nums> num: one;

    match num {
//        >  <error{Non-exhaustive match on Nums: missing 'two', 'three'}
        one: Rectangle { }
    }
}

export component WildcardEnum {
    in-out property <Nums> num: one;

    match num {
        one: Rectangle { }
        *: Rectangle { }
    }
}

export component ExhaustiveBool {
    in-out property <bool> flag: true;

    match flag {
        true: Rectangle { }
        false: Rectangle { }
    }
}

export component NonExhaustiveBool {
    in-out property <bool> flag: true;

    match flag {
//        >   <error{Non-exhaustive match on bool: missing 'false'}
        true: Rectangle { }
    }
}

export component NonExhaustiveInt {
    in-out property <int> num: 0;

    match num {
//        >  <error{Non-exhaustive match on int: a '*' case is required}
        0: Rectangle { }
        1: Rectangle { }
    }
}

export component WildcardInt {
    in-out property <int> num: 0;

    match num {
        0: Rectangle { }
        1: Rectangle { }
        *: Rectangle { }
    }
}

export component NonExhaustiveString {
    in-out property <string> str: "hello";

    match str {
//        >  <error{Non-exhaustive match on string: a '*' case is required}
        "hello": Rectangle { }
    }
}
