// Copyright © 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nicholas Turner <nicholas.turner@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export interface Foo {
    out property <string> message;
        match message {
//      >error{An interface cannot have match statements}
            "hi": Rectangle { Text { text: "Hello!"; } }
            "bye": Rectangle { Text { text: "Bye!"; } }
            *: Rectangle { Text { text: "Welcome"; } }
    }
//  <error{An interface cannot have match statements}
}