// Copyright © 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nicholas Turner <nicholas.turner@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component LiteralSubjects {
    match 1 {
//        ><warning{Match subject is a literal, so the same case always applies}
        1: Rectangle { }
        *: Rectangle { }
    }
    match -1 {
//        > <warning{Match subject is a literal, so the same case always applies}
        -1: Rectangle { }
        *: Rectangle { }
    }
    match "a" {
//        >  <warning{Match subject is a literal, so the same case always applies}
        "a": Rectangle { }
        *: Rectangle { }
    }
    match #123 {
//        >   <warning{Match subject is a literal, so the same case always applies}
        #123: Rectangle { }
        *: Rectangle { }
    }
    match 10px {
//        >   <warning{Match subject is a literal, so the same case always applies}
        10px: Rectangle { }
        *: Rectangle { }
    }
    match true {
//        >   <warning{Match subject is a literal, so the same case always applies}
        true: Rectangle { }
        false: Rectangle { }
    }
}

export component Foo {
    out property <int> case0: 0;
    out property <int> case1: 1;
    out property <int> case2: 2;

    out property <int> num: 1;

    match num {
        case0: Rectangle { }
//      >   <error{Cases must be literal values}
        case1: Rectangle { }
//      >   <error{Cases must be literal values}
        case2: Rectangle { }
//      >   <error{Cases must be literal values}
        *: Rectangle { }
    }
}

export component Bar {
    out property <string> greeting: "hello world";

    match greeting {
        "hello": Rectangle { }
        "hello " + "world": Rectangle { }
//      >                <error{Cases must be literal values}
        *: Rectangle { }
    }
}

export component Baz {
    function func(xx: int) -> string {
        return xx == 0 ? "hello world" : "goodbye world";
    }
    out property <string> greeting: "hello world";

    match greeting {
        func(0): Rectangle { }
//      >     <error{Cases must be literal values}
        *: Rectangle { }
    }
}

export component FooBar {
    in property <string> greeting: "hello world";
    in property <string> world: "world";

    match greeting {
        "hello \{world}": Rectangle { }
//      >              <error{Cases must be literal values}
        "hello": Rectangle { }
    }
}

enum Fruit {
    apple,
    pear,
    orange,
    tomato,
}

export component TypeBasedLookupOfEnumCases {
    in property <Fruit> fruit: Fruit.tomato;

    match fruit {
        apple: Text { text: "unqualified Fruit"; }
        Fruit.pear: Text { text: "fully qualified Fruit"; }
        * : { }
    }
}
