// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

export enum DoorState { sealed, locking, locked, ready, released }

export component DoorImage inherits Image {
    in property <DoorState> state: DoorState.sealed;

    source: root.state == DoorState.sealed ? @image-url("assets/door-sealed.png")
        : root.state == DoorState.locking ? @image-url("assets/door-locking.png")
        : root.state == DoorState.locked ? @image-url("assets/door-locked.png")
        : root.state == DoorState.ready ? @image-url("assets/door-ready.png")
        : @image-url("assets/door-released.png");
}

export component RasterDigit inherits Image {
    private property <int> digit: value < 0 ? 0 : value > 9 ? 9 : value;

    in property <int> value: 0;

    source: root.digit == 0 ? @image-url("assets/digits/digit-white-0.png")
        : root.digit == 1 ? @image-url("assets/digits/digit-white-1.png")
        : root.digit == 2 ? @image-url("assets/digits/digit-white-2.png")
        : root.digit == 3 ? @image-url("assets/digits/digit-white-3.png")
        : root.digit == 4 ? @image-url("assets/digits/digit-white-4.png")
        : root.digit == 5 ? @image-url("assets/digits/digit-white-5.png")
        : root.digit == 6 ? @image-url("assets/digits/digit-white-6.png")
        : root.digit == 7 ? @image-url("assets/digits/digit-white-7.png")
        : root.digit == 8 ? @image-url("assets/digits/digit-white-8.png")
        : @image-url("assets/digits/digit-white-9.png");
}
