// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

use std::collections::HashSet;
use std::sync::Arc;
use std::{net::SocketAddr, rc::Rc};

use i_slint_core::SharedString;
use i_slint_core::textlayout::sharedparley::fontique;
use i_slint_core::window::WindowInner;
use i_slint_live_preview::inspector::InspectorOverlay;
use i_slint_live_preview::preview_sessions::{
    PreviewCompilation, PreviewSession, PreviewSessionEvent,
};
use i_slint_live_preview::protocol::{PreviewComponent, PreviewToLspMessage, lsp_types};
use i_slint_live_preview::remote::{Connection, ConnectionMessage, PairingPolicy};
use slint::ComponentHandle as _;

slint::slint! {
    export { RemoteViewerWindow, RemoteViewerState } from "remote/main.slint";
    export { AttributionItem } from "remote/licenses.slint";
}

// CARGO_PKG_VERSION tracks the workspace version, so it is the Slint version.
const SLINT_VERSION: &str = concat!("Slint ", env!("CARGO_PKG_VERSION"));
// Set by CI when building binaries (desktop, Android, iOS) so users can report
// which build they are running. Empty for local developer builds.
const BUILD_NUMBER: Option<&str> = option_env!("SLINT_BUILD_NUMBER");
// Generated by build.rs: the attribution data for the in-app licenses page.
// Android embeds the real listing; other targets embed the empty document
// `{"crates":[],"licenses":[]}` (iOS shows its licenses via a Settings.bundle
// instead, so its in-app page stays hidden).
const THIRD_PARTY_LICENSES_JSON: &str =
    include_str!(concat!(env!("OUT_DIR"), "/third-party-licenses.json"));

/// The model for the idle screen's third-party attribution page: one row per
/// crate, followed by one section per license text. Empty when build.rs wrote
/// the empty document, which hides the page's entry point.
fn third_party_licenses() -> slint::ModelRc<AttributionItem> {
    // The JSON comes from our own generator (`cargo xtask license`), so any
    // shape mismatch is a build bug.
    const MALFORMED: &str = "build.rs produced malformed third-party-licenses.json";
    let json: serde_json::Value = serde_json::from_str(THIRD_PARTY_LICENSES_JSON).expect(MALFORMED);
    let str_field = |value: &serde_json::Value, key: &str| -> SharedString {
        value[key].as_str().expect(MALFORMED).into()
    };
    let mut items: Vec<AttributionItem> = json["crates"]
        .as_array()
        .expect(MALFORMED)
        .iter()
        .map(|c| AttributionItem {
            title: slint::format!("{} {}", str_field(c, "name"), str_field(c, "version")),
            author: str_field(c, "author"),
            license: str_field(c, "license"),
            ..Default::default()
        })
        .collect();
    items.extend(json["licenses"].as_array().expect(MALFORMED).iter().map(|l| AttributionItem {
        title: str_field(l, "name"),
        body: str_field(l, "text"),
        ..Default::default()
    }));
    slint::ModelRc::new(slint::VecModel::from(items))
}

fn build_info() -> SharedString {
    let debug_suffix = if cfg!(debug_assertions) { " (debug build)" } else { "" };
    match BUILD_NUMBER {
        Some(n) => slint::format!("Build {n}{debug_suffix}"),
        None if !debug_suffix.is_empty() => SharedString::from(debug_suffix.trim_start()),
        None => SharedString::default(),
    }
}

/// Events driving the remote main loop: messages from the editor connection plus, on
/// iOS, app lifecycle notifications.
enum Event {
    Connection(ConnectionMessage),
    Preview(PreviewSessionEvent),
    /// The app returned to the foreground after having been suspended: re-announce
    /// the mDNS service (see [`announce_mdns`] for why the old announcement may be
    /// dead). Only iOS has the lifecycle observers that send this.
    #[cfg_attr(not(target_os = "ios"), allow(dead_code))]
    Resumed,
}

#[cfg(target_vendor = "apple")]
mod apple;
#[cfg(target_vendor = "apple")]
use apple::announce_mdns;
#[cfg(target_os = "ios")]
use apple::observe_foregrounding;

pub fn run(
    address: Option<SocketAddr>,
    enable_mdns: bool,
    pairing_policy: PairingPolicy,
) -> anyhow::Result<()> {
    slint_interpreter::spawn_local(async_compat::Compat::new(async move {
        let local_set = tokio::task::LocalSet::new();
        local_set
            .run_until(async move {
                if let Err(err) = run_async(address, enable_mdns, pairing_policy).await {
                    tracing::error!("Remote viewer error: {err}");
                    slint_interpreter::quit_event_loop().ok();
                }
            })
            .await;
    }))?;
    slint_interpreter::run_event_loop()?;
    Ok(())
}

async fn run_async(
    address: Option<SocketAddr>,
    enable_mdns: bool,
    pairing_policy: PairingPolicy,
) -> anyhow::Result<()> {
    let (event_sender, mut event_receiver) = tokio::sync::mpsc::unbounded_channel();

    #[cfg(target_os = "ios")]
    observe_foregrounding(event_sender.clone());

    let pairing_disabled = pairing_policy == PairingPolicy::Disabled;
    if pairing_disabled {
        tracing::warn!(
            "Pairing is disabled: any host that can reach this viewer can drive it. \
             Only use --no-pairing on a network you control."
        );
    }

    let connection_event_sender = event_sender.clone();
    let (connection, preview_session) = Connection::listen(
        address,
        device_name_override(),
        pairing_policy,
        move |message| {
            let _ = connection_event_sender.send(Event::Connection(message));
        },
        move |message| {
            let _ = event_sender.send(Event::Preview(message));
        },
    )
    .await?;
    let connection = Rc::new(connection);

    // Forward all debug output to the LSP, so that the LSP can show it to the user.
    // Slint Viewer itself only displays the previewed app, so it has no UI of its own to show debug messages in.
    let connection_weak = Rc::downgrade(&connection);
    let _ = i_slint_backend_selector::with_global_context(|ctx| {
        ctx.set_log_message_handler(Some(Box::new(move |message| {
            let location = crate::debug::log_message_handler(&message);
            let Some(connection) = connection_weak.upgrade() else {
                return;
            };

            connection
                .send(PreviewToLspMessage::DebugMessage {
                    location,
                    message: message.message_arguments().to_string(),
                })
                .ok();
        })))
    })?;

    let mut placeholder = RemoteViewerWindow::new()?;
    let inspector = InspectorOverlay::new(placeholder.window()).await?;

    #[cfg(not(target_vendor = "apple"))]
    let mdns = enable_mdns.then(mdns_sd::ServiceDaemon::new).transpose()?;

    #[cfg(not(target_vendor = "apple"))]
    {
        let service = connection.service()?;
        mdns.as_ref().map(|mdns| mdns.register(service)).transpose()?;
    }
    #[cfg(target_vendor = "apple")]
    let mut mdns = if enable_mdns { announce_mdns(&connection).await } else { None };

    let local_port = connection.local_port();
    let mut local_ips = connection.local_ips();
    // Prefer IPv4: when any IPv4 address is present, drop the IPv6 ones so the
    // display isn't cluttered with link-local addresses no one types. Fall back
    // to IPv6 only when that's all we have.
    if local_ips.iter().any(std::net::IpAddr::is_ipv4) {
        local_ips.retain(std::net::IpAddr::is_ipv4);
    }
    let local_ip_str: Vec<String> = local_ips
        .iter()
        .map(|ip| match ip {
            std::net::IpAddr::V4(ipv4_addr) => format!("{ipv4_addr}:{local_port}"),
            std::net::IpAddr::V6(ipv6_addr) => {
                format!("[{ipv6_addr}]:{local_port}")
            }
        })
        .collect();
    // Only the Apple resume path renames the device, so on other targets
    // this is never mutated.
    #[cfg_attr(not(target_vendor = "apple"), allow(unused_mut))]
    let mut chrome = Chrome {
        address: local_ip_str.join("\n"),
        // Read after the Apple Bonjour overwrite above so the UI label matches
        // the advertised mDNS instance.
        name: connection.device_name(),
        licenses: third_party_licenses(),
        pairing_disabled,
    };
    chrome.apply(&placeholder);
    placeholder.show()?;

    // Set while a pairing code is on screen. The established session keeps
    // running underneath, and its traffic must not repaint over a code the
    // user is still reading: the code is only worth anything for as long as
    // it is legible on the device.
    let mut prompt_on_screen = false;
    let mut last_connection = None;
    let mut user_instance: Option<slint_interpreter::ComponentInstance> = None;
    let mut current_preview: Option<PreviewComponent> = None;
    let mut current_highlight: Option<(lsp_types::Url, u32)> = None;
    let mut registered_fonts = HashSet::<lsp_types::Url>::new();
    while let Some(event) = event_receiver.recv().await {
        match event {
            Event::Resumed => {
                #[cfg(target_vendor = "apple")]
                if enable_mdns {
                    // Withdraw the old announcement first: re-registering while it is
                    // still alive would trigger Bonjour's conflict rename.
                    drop(mdns.take());
                    mdns = announce_mdns(&connection).await;
                    chrome.name = connection.device_name();
                    chrome.apply(&placeholder);
                }
                continue;
            }
            Event::Preview(message) => match message {
                PreviewSessionEvent::SetUserSettings { .. } => {}
                PreviewSessionEvent::ShowPreview { component } => {
                    current_preview = Some(component);
                    if !prompt_on_screen {
                        show_current(
                            &current_preview,
                            &mut placeholder,
                            &mut user_instance,
                            &inspector,
                            current_highlight.as_ref(),
                            &preview_session,
                            &chrome,
                        )
                        .await?;
                    }
                }
                PreviewSessionEvent::ContentsChanged => {
                    if !prompt_on_screen {
                        show_current(
                            &current_preview,
                            &mut placeholder,
                            &mut user_instance,
                            &inspector,
                            current_highlight.as_ref(),
                            &preview_session,
                            &chrome,
                        )
                        .await?;
                    }
                }
                PreviewSessionEvent::HighlightFromEditor { url, offset } => {
                    current_highlight = url.map(|url| (url, offset));
                    inspector.update(user_instance.as_ref(), current_highlight.as_ref());
                }
                PreviewSessionEvent::RegisterFont { url, contents } => {
                    let len = contents.len();
                    if !registered_fonts.insert(url.clone()) {
                        tracing::debug!("Font {url} already registered, skipping");
                        continue;
                    }
                    let blob = fontique::Blob::new(Arc::new(contents));
                    WindowInner::from_pub(placeholder.window())
                        .context()
                        .font_context()
                        .borrow_mut()
                        .collection
                        .register_fonts(blob, None);
                    tracing::debug!("Registered font {url} ({len} bytes)");
                }
            },
            Event::Connection(ConnectionMessage::Connected { remote_addr }) => {
                last_connection = Some(remote_addr);
                if !prompt_on_screen {
                    placeholder
                        .set_message(SharedString::from(format!("Connected to {remote_addr}")));
                    placeholder.set_state(RemoteViewerState::Connected);
                }
            }
            Event::Connection(ConnectionMessage::Disconnected { remote_addr }) => {
                if last_connection == Some(remote_addr) {
                    last_connection = None;
                    current_preview = None;
                    current_highlight = None;
                    if !prompt_on_screen {
                        swap_to_placeholder(
                            &mut placeholder,
                            &mut user_instance,
                            &inspector,
                            &chrome,
                            "",
                            RemoteViewerState::WaitingForConnection,
                        )?;
                    }
                }
            }
            Event::Connection(ConnectionMessage::PairingStarted {
                remote_addr,
                code,
                expires_in,
            }) => {
                prompt_on_screen = true;
                // Takes the screen even from a running preview. The code is
                // only worth anything if it can be read off this device, so
                // it has to be the thing on screen.
                swap_to_placeholder(
                    &mut placeholder,
                    &mut user_instance,
                    &inspector,
                    &chrome,
                    "",
                    RemoteViewerState::Pairing,
                )?;
                placeholder.set_pairing_code(SharedString::from(code));
                placeholder.set_pairing_peer(SharedString::from(
                    remote_addr.ip().to_canonical().to_string(),
                ));
                placeholder.set_pairing_seconds_left(expires_in.as_secs() as i32);
            }
            // The admitted session takes it from here: it pushes its
            // configuration and asks for a component to show.
            Event::Connection(ConnectionMessage::PairingFinished { accepted: true, .. }) => {
                prompt_on_screen = false;
            }
            Event::Connection(ConnectionMessage::PairingFinished { accepted: false, .. }) => {
                prompt_on_screen = false;
                // Nobody got in, so restore whatever the prompt displaced,
                // including anything the session changed meanwhile.
                let restored = show_current(
                    &current_preview,
                    &mut placeholder,
                    &mut user_instance,
                    &inspector,
                    current_highlight.as_ref(),
                    &preview_session,
                    &chrome,
                )
                .await?;
                if !restored {
                    let state = if last_connection.is_some() {
                        RemoteViewerState::Connected
                    } else {
                        RemoteViewerState::WaitingForConnection
                    };
                    swap_to_placeholder(
                        &mut placeholder,
                        &mut user_instance,
                        &inspector,
                        &chrome,
                        "",
                        state,
                    )?;
                }
            }
        }
    }

    #[cfg(not(target_vendor = "apple"))]
    mdns.map(|mdns| mdns.shutdown())
        .transpose()
        .inspect_err(|err| tracing::error!("mdns shutdown: {err}"))?;

    // Keep the Bonjour announcement alive until the message loop ends.
    #[cfg(target_vendor = "apple")]
    drop(mdns);

    Ok(())
}

/// Rebuild and show whatever component is currently being previewed.
///
/// Returns whether there was one, so callers that have to fall back to a
/// placeholder can tell.
async fn show_current(
    current_preview: &Option<PreviewComponent>,
    placeholder: &mut RemoteViewerWindow,
    user_instance: &mut Option<slint_interpreter::ComponentInstance>,
    inspector: &InspectorOverlay,
    current_highlight: Option<&(lsp_types::Url, u32)>,
    preview_session: &PreviewSession,
    chrome: &Chrome,
) -> anyhow::Result<bool> {
    let Some(preview_component) = current_preview.clone() else { return Ok(false) };
    build_and_show(
        &preview_component,
        placeholder,
        user_instance,
        inspector,
        current_highlight,
        preview_session,
        chrome,
    )
    .await?;
    Ok(true)
}

/// Returns `Err` only on unrecoverable platform failure; compile errors and missing
/// components reinstall the placeholder and return `Ok(())`.
async fn build_and_show(
    preview_component: &PreviewComponent,
    placeholder: &mut RemoteViewerWindow,
    user_instance: &mut Option<slint_interpreter::ComponentInstance>,
    inspector: &InspectorOverlay,
    current_highlight: Option<&(lsp_types::Url, u32)>,
    preview_session: &PreviewSession,
    chrome: &Chrome,
) -> anyhow::Result<()> {
    tracing::debug!("build_and_show");

    let component = match preview_session.compile_component(preview_component).await {
        PreviewCompilation::Ready(component) => component,
        PreviewCompilation::CompilationError { message } => {
            swap_to_placeholder(
                placeholder,
                user_instance,
                inspector,
                chrome,
                &message,
                RemoteViewerState::PreviewError,
            )?;
            return Ok(());
        }
        PreviewCompilation::ComponentNotFound => {
            swap_to_placeholder(
                placeholder,
                user_instance,
                inspector,
                chrome,
                "Component not found",
                RemoteViewerState::PreviewError,
            )?;
            return Ok(());
        }
        PreviewCompilation::Unavailable => return Ok(()),
    };

    let new_instance = component
        .create_with_existing_window(placeholder.window())
        .map_err(|err| anyhow::anyhow!("Cannot create component instance: {err}"))?;

    new_instance.show().map_err(|err| anyhow::anyhow!("Cannot show component: {err}"))?;
    *user_instance = Some(new_instance);
    inspector.attach()?;
    inspector.update(user_instance.as_ref(), current_highlight);
    // The placeholder is hidden now, but keep its state property truthful.
    placeholder.set_state(RemoteViewerState::Previewing);
    Ok(())
}

/// Everything on the placeholder screen that doesn't depend on what the
/// connection is doing.
///
/// [`swap_to_placeholder`] builds a whole new window each time, so anything
/// missing from [`Chrome::apply`] silently disappears the first time the
/// preview is swapped out.
struct Chrome {
    /// Newline-separated `ip:port` list the editor can be pointed at.
    address: String,
    /// Friendly device name. Bonjour can rename us on iOS resume, so this
    /// isn't fixed for the life of the process.
    name: String,
    licenses: slint::ModelRc<AttributionItem>,
    pairing_disabled: bool,
}

impl Chrome {
    fn apply(&self, window: &RemoteViewerWindow) {
        window.set_address(SharedString::from(self.address.as_str()));
        window.set_name(SharedString::from(self.name.as_str()));
        window.set_slint_version(SharedString::from(SLINT_VERSION));
        window.set_build_info(build_info());
        window.set_third_party_licenses(self.licenses.clone());
        window.set_pairing_disabled(self.pairing_disabled);
    }
}

/// Reinstall a fresh placeholder onto the existing window and drop the user instance.
fn swap_to_placeholder(
    placeholder: &mut RemoteViewerWindow,
    user_instance: &mut Option<slint_interpreter::ComponentInstance>,
    inspector: &InspectorOverlay,
    chrome: &Chrome,
    message: &str,
    state: RemoteViewerState,
) -> anyhow::Result<()> {
    inspector.detach();
    let fresh = RemoteViewerWindow::new_with_existing_window(placeholder.window())
        .map_err(|err| anyhow::anyhow!("Cannot create placeholder: {err}"))?;
    chrome.apply(&fresh);
    fresh.set_message(SharedString::from(message));
    fresh.set_state(state);
    fresh.show().map_err(|err| anyhow::anyhow!("Cannot show placeholder: {err}"))?;
    *placeholder = fresh;
    *user_instance = None;
    Ok(())
}

/// Platform-specific override for the friendly device name. Returns `None` on platforms
/// where the default chain in `Connection` (pretty hostname → hostname, then Bonjour on
/// Apple) is already best.
fn device_name_override() -> Option<String> {
    #[cfg(target_os = "android")]
    {
        ANDROID_DEVICE_NAME.lock().unwrap_or_else(|e| e.into_inner()).clone()
    }
    #[cfg(not(target_os = "android"))]
    {
        None
    }
}

/// Set by `android_main` before `run` is called so the connection picks up the
/// user-set device name from `Settings.Global.DEVICE_NAME`.
#[cfg(target_os = "android")]
pub(crate) static ANDROID_DEVICE_NAME: std::sync::Mutex<Option<String>> =
    std::sync::Mutex::new(None);

#[cfg(test)]
mod tests {
    use super::*;
    use i_slint_renderer_software::{
        MinimalSoftwareWindow, PremultipliedRgbaColor, RepaintBufferType, TargetPixel,
    };
    use slint::platform::{Platform, PlatformError, WindowAdapter};

    const WIDTH: u32 = 100;
    const HEIGHT: u32 = 80;
    const TEST_PREVIEW_SOURCE: &str = r#"
        export component TestPreview inherits Window {
            background: white;

            Rectangle {
                x: 20px;
                y: 20px;
                width: 30px;
                height: 20px;
            }
        }
    "#;

    struct SoftwareRendererPlatform(Rc<MinimalSoftwareWindow>);

    impl Platform for SoftwareRendererPlatform {
        fn create_window_adapter(&self) -> Result<Rc<dyn WindowAdapter>, PlatformError> {
            Ok(self.0.clone())
        }
    }

    #[derive(Clone, Copy, Default)]
    struct RgbPixel {
        red: u8,
        green: u8,
        blue: u8,
    }

    impl TargetPixel for RgbPixel {
        fn blend(&mut self, color: PremultipliedRgbaColor) {
            let inverse_alpha = 255u32 - color.alpha as u32;
            self.red = (color.red as u32 + self.red as u32 * inverse_alpha / 255).min(255) as u8;
            self.green =
                (color.green as u32 + self.green as u32 * inverse_alpha / 255).min(255) as u8;
            self.blue = (color.blue as u32 + self.blue as u32 * inverse_alpha / 255).min(255) as u8;
        }

        fn from_rgb(red: u8, green: u8, blue: u8) -> Self {
            Self { red, green, blue }
        }
    }

    #[test]
    fn inspector_overlay_renders_highlight_over_preview() {
        let window_adapter = MinimalSoftwareWindow::new(RepaintBufferType::NewBuffer);
        slint::platform::set_platform(Box::new(SoftwareRendererPlatform(window_adapter.clone())))
            .unwrap();
        window_adapter.set_size(slint::PhysicalSize::new(WIDTH, HEIGHT));

        let preview_path =
            std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("test-preview.slint");
        let compilation_result = crate::poll_ready(
            slint_interpreter::Compiler::default()
                .build_from_source(TEST_PREVIEW_SOURCE.into(), preview_path.clone()),
        );
        assert!(!compilation_result.has_errors());
        let preview = compilation_result.component("TestPreview").unwrap().create().unwrap();
        preview.show().unwrap();
        let preview_item_tree = WindowInner::from_pub(preview.window()).component();
        let inspector = crate::poll_ready(InspectorOverlay::new(preview.window())).unwrap();
        assert!(i_slint_core::item_tree::ItemTreeRc::ptr_eq(
            &preview_item_tree,
            &WindowInner::from_pub(preview.window()).component(),
        ));
        let highlight = (
            lsp_types::Url::from_file_path(&preview_path).unwrap(),
            TEST_PREVIEW_SOURCE.find("Rectangle").unwrap() as u32,
        );
        inspector.update(Some(&preview), Some(&highlight));
        inspector.attach().unwrap();

        let mut pixels = vec![RgbPixel::default(); (WIDTH * HEIGHT) as usize];
        preview.window().request_redraw();
        window_adapter.draw_if_needed(|renderer| {
            renderer.render(pixels.as_mut_slice(), WIDTH as usize);
        });

        let highlighted = pixels[(25 * WIDTH + 25) as usize];
        let outside = pixels[(5 * WIDTH + 5) as usize];
        assert!(highlighted.blue > highlighted.red);
        assert_eq!((outside.red, outside.green, outside.blue), (255, 255, 255));
    }
}
