// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component SimulatorWindow inherits Window {
    title: "Slint Live Preview";
    preferred-width: 800px;
    preferred-height: 600px;

    in property <component-factory> preview-factory;

    MenuBar {
        Menu {
            title: "File";
            MenuItem {
                title: "Close Window";
                shortcut: @keys(Control + W);
                activated => {
                    root.close();
                }
            }
        }
    }

    ComponentContainer {
        component-factory: root.preview-factory;
    }
}
