// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { DemoPalette, Page, PushButton } from "./common.slint";
import { CopyPage } from "./copy_page.slint";
import { ScanPage } from "./scan_page.slint";
import { PrintPage } from "./print_page.slint";
import { PrinterQueueView } from "./printer_queue.slint";
import { UsbPage } from "./usb_page.slint";

component ActionButton inherits Rectangle {

    in property <image> icon <=> img.source;
    in property <string> text <=> label.text;
    callback clicked;

    VerticalLayout {
        spacing: 4px;

        Rectangle {
            border-radius: 25px;
            border-width: 5px;
            border-color: DemoPalette.control-outline-color;
            background: DemoPalette.printer-action-background-color;

            img := Image {
                x: (parent.width / 2) - (self.width / 2);
                y: (parent.height / 2) - (self.height / 2);
                colorize: DemoPalette.text-foreground-color;
            }
        }

        label := Text {
            font-size: DemoPalette.base-font-size * 1.375;
            font-weight: 800;
            horizontal-alignment: center;
            color: DemoPalette.text-foreground-color;
        }
    }

    TouchArea { clicked => { root.clicked() } }
}

export component HomePage inherits Page {
    in-out property <length> header-row-height: 40px;

    in-out property <length> button-spacing: 35px;
    in-out property <length> button-width: 127px;
    in-out property <length> button-height: root.button-width + 37px;

    header: @tr("Slint Printer Demo");

    in-out property <int> current-subpage: 0;


    for action[idx] in [
        { name: @tr("Print"), icon: @image-url("images/print.svg") },
        { name: @tr("Scan"), icon: @image-url("images/scan.svg") },
        { name: @tr("Copy"), icon: @image-url("images/copy.svg") },
        { name: @tr("USB"), icon: @image-url("images/usb.svg") },
    ]: ActionButton {
        x: mod(idx, 2) * (root.button-width + root.button-spacing);
        y: floor(idx / 2) * (root.button-height + root.button-spacing)
           + /* header row height */ 46px
           + /* top-padding of printer queue */ 27px; // align with the first item of the printer queue
        width: root.button-width;
        height: root.button-height;
        icon: action.icon;
        text: action.name;
        clicked => { root.current-subpage = idx + 1; }
    }

    queue-view := PrinterQueueView {
        x: parent.width - self.width;
        width: 313px;
        show-job-details(idx) => {
            root.current-subpage = 1; // Not nice to hard-code the index here...
        }
    }

    PrintPage {
        x: root.current-subpage == 1 ? 0 : parent.width + parent.x + 2px;
        animate x { duration: 125ms; easing: ease; }
        back => { root.current-subpage = 0 }
    }
    ScanPage {
        x: root.current-subpage == 2 ? 0 : parent.width + parent.x + 2px;
        animate x { duration: 125ms; easing: ease; }
        back => { root.current-subpage = 0 }
    }
    CopyPage {
        x: root.current-subpage == 3 ? 0 : parent.width + parent.x + 2px;
        animate x { duration: 125ms; easing: ease; }
        back => { root.current-subpage = 0 }
    }
    UsbPage {
        x: root.current-subpage == 4 ? 0 : parent.width + parent.x + 2px;
        animate x { duration: 125ms; easing: ease; }
        back => { root.current-subpage = 0 }
    }
}
