// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { DemoPalette, Page, SpinBox, Label, PushButton } from "./common.slint";
import { WidePrinterQueueList } from "./printer_queue.slint";


export component PrintPage inherits Page {
    has-back-button: true;
    header: "Print";

    GridLayout {
        padding-top: 46px /* header line height in design */
                     + /* extra top-padding in design */ 27px;
        spacing: 24px;
        Row {
            Text {
                text: "Printing-Queue";
                color: DemoPalette.secondary-foreground-color;
                font-size: DemoPalette.base-font-size * 1.125;
                font-weight: 800;
            }
        }

        Row {
            queue := WidePrinterQueueList {
                viewport-width: self.width;
            }
        }
    }
}
