// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { AboutSlint } from "std-widgets.slint";

export component TestCase inherits Window {
    about := AboutSlint { }
}


/*
```rust
use i_slint_backend_testing::AccessibleRole;

let instance = TestCase::new().unwrap();

let mut image_search = slint_testing::ElementHandle::find_by_accessible_label(&instance, "#MadeWithSlint");
let image = image_search.next().unwrap();

assert_eq!(image.accessible_role(), Some(AccessibleRole::Image));
```
*/
