// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { LineEdit } from "std-widgets.slint";
export component TestCase inherits Window {
    width: 200px;
    height: 200px;

    edit1 := LineEdit {
        y: 0px;
        width: 10 * self.height; // Test that there is no height for width dependency (loop)
    }
}

