// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Button, GroupBox, TabWidget, VerticalBox } from "std-widgets.slint";

export component TestCase inherits Window {
    TabWidget {
        Tab {
            title: "First Tab";

            VerticalBox {
                alignment: start;

                GroupBox {
                    title: "Content of first tab";

                    Button {
                        text: "Button 1";
                    }
                }
            }
        }

        Tab {
            title: "Second Tab";

            VerticalBox {
                alignment: start;

                GroupBox {
                    title: "Content of second tab";

                    Button {
                        text: "Button 2";
                    }
                }
            }
        }

        Tab {
            title: "Third Tab";

            VerticalBox {
                alignment: start;

                GroupBox {
                    title: "Content of third tab";

                    Button {
                        text: "Button 3";
                    }
                }
            }
        }
    }
}

/*
```rust
let instance = TestCase::new().unwrap();

let mut tab1_search = slint_testing::ElementHandle::find_by_accessible_label(&instance, "First Tab");
let _tab1 = tab1_search.next().unwrap();

let mut tab2_search = slint_testing::ElementHandle::find_by_accessible_label(&instance, "Second Tab");
let _tab2 = tab2_search.next().unwrap();

let mut tab3_search = slint_testing::ElementHandle::find_by_accessible_label(&instance, "Third Tab");
let _tab3 = tab3_search.next().unwrap();
```
*/
