# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "drone-course"
version = "1.19.0"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2024"
publish = false
license = "MIT"
description = "Slint Drone Course Demo, rendered with wgpu"

[[bin]]
name = "drone_course"
path = "main.rs"

# Remove the `#wasm#` to uncomment the wasm build.
# The CI has a script that does sed "s/#wasm# //" to generate the wasm build.
#wasm# [lib]
#wasm# path = "main.rs"
#wasm# crate-type = ["cdylib"]

[dependencies]
bytemuck = { workspace = true }
image = { workspace = true }
glam = "0.32"
web-time = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
slint = { path = "../../api/rs/slint", features = ["renderer-skia", "unstable-wgpu-30"] }
pollster = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
slint = { path = "../../api/rs/slint", default-features = false, features = ["std", "compat-1-2", "backend-winit", "renderer-femtovg-wgpu", "unstable-wgpu-30"] }
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3", features = ["Window", "Storage"] }
console_error_panic_hook = "0.1.5"

[build-dependencies]
slint-build = { path = "../../api/rs/build" }
