// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0


component BadOne {
    function focus() {
//           ^error{Cannot override 'focus'}
    }

    TextInput {
        function focus() {
//               ^error{Cannot override 'focus'}
        }
    }
}

component SecondBadOne {
    forward-focus: ti;
    function focus() {
//           ^error{Cannot override 'focus'}
    }
    ti := TextInput {}
}

export X := Rectangle {
    edit := TextInput { }
    TouchArea {
        clicked => {
            (edit.focus)();
//           ^error{Member function must be called. Did you forgot the '\(\)'\?}
            edit.focus;
//          ^error{Member function must be called. Did you forgot the '\(\)'\?}
        }
    }
    x: edit.focus;
//     ^error{Member function must be called. Did you forgot the '\(\)'\?}

    BadOne {}
    SecondBadOne {}
}
