// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

component Sub inherits Rectangle {
    in-out property <bool> cond;
    in-out property <float> child_opacity: inner.opacity;
    inner := Rectangle {
        opacity: cond ? 0 : 1;
        animate opacity { duration: 1s; }
        background: green;
    }
}

export component TestCase inherits Rectangle {
    in-out property cond <=> s.cond;
    in-out property val <=> s.child_opacity;
    s := Sub {}
}

/*

```rust
let instance = TestCase::new().unwrap();
assert_eq!(instance.get_val(), 1.);
instance.set_cond(true);
assert_eq!(instance.get_val(), 1.);
slint_testing::mock_elapsed_time(500);
assert_eq!(instance.get_val(), 0.5);
slint_testing::mock_elapsed_time(500);
assert_eq!(instance.get_val(), 0.);

```

*/
