// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0


export component TestCase inherits Rectangle {
    width: 100px;
    height: 200px;

    r := Rectangle {
        x:0;y:0;
        width <=> root.width;
        height <=> root.height;
    }

    in-out property<bool> test: r.width == 100px && r.height == 200px;
}

/*
```rust
let instance = TestCase::new().unwrap();
assert!(instance.get_test());
```

```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert(instance.get_test());
```

```js
let instance = new slint.TestCase({});
assert(instance.test, 1);
```

*/
