// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { Theme } from "../theme.slint";

export component BarBackground inherits Rectangle {
    border-radius: 2px;
    background: Theme.palette.bar-background-gradient;
    opacity: 0.25;
}

export component ChartPattern {
    in property <int> count;

    HorizontalLayout {
        spacing: 1px;
        for _ in count : BarBackground {}
    }
}