// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { Theme } from "../theme.slint";
import { MenuButton } from "menu_button.slint";

export component Menu {
    private property <bool> open;
    private property <int> container-visibility;

    callback opend();
    callback closed();

    in-out property <bool> menu-button-visible;
    in property <length> start-y;
    in property <length> end-y;
    in property <bool> stays-open;
    in property <length> menu-width <=> i-menu-container.width;
    in property <length> menu-height <=> i-menu-container.height;

    if(open) : TouchArea {
        clicked => {
            hide();
        }
    }

    i-menu-container := Rectangle { 
        x: (parent.width - self.width) / 2;
        y: parent.height - start-y;
        width: root.width / 3;
        height: root.height - 75px;  

        i-container := Rectangle {
            visible: container-visibility == 1.0;
            border-radius: 4px;
            background: Theme.palette.ebony-radial-gradient;
    
            // avoid click-through
            TouchArea {}
    
            @children
        }
    
        HorizontalLayout {  
            y:  -i-menu-button.height / 2;
            alignment: center;
    
            VerticalLayout {  
                alignment: start;
    
                i-menu-button := MenuButton {  
                    visible: menu-button-visible || container-visibility == 1.0 || stays-open;
                   
                    clicked => { 
                        toggle-open(); 
                    }
                }
            }
        }

        animate y { duration: Theme.durations.medium; }
    }

    public function hide-button() {
        menu-button-visible = false;
    }

    public function show-button() {
        menu-button-visible = true;
    }

    function toggle-open() {
        menu-button-visible = false;
        open = !open;

        if(open) {
            opend();
        } else {
            closed();
        }
    }

    public function hide() {
        menu-button-visible = false;
        open = false;
        closed();
    }

    states [  
        open when root.open : {
            container-visibility: 1.0;
            i-menu-container.y: end-y;

            out {
                animate container-visibility { duration: Theme.durations.medium; }
            }
        }
    ]
}