// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component Compo inherits Text {

    property <string> background: text;
//                                ^error{Unknown unqualified identifier 'text'. Did you mean 'self.text'?}

    Rectangle {
        background: background;
//                  ^error{Cannot convert string to brush}
    }

    Text {
        text: background; // works: lookup in the root
    }

    if true : Rectangle {
        property <color> text;
        Text {
            color: text; // works
            text: background; // works
            width: border-color;
//                 ^error{Unknown unqualified identifier 'border-color'}
            height: text;
//                  ^error{Cannot convert color to length}
        }
    }

    Rectangle {
        width: text;
//             ^error{Unknown unqualified identifier 'text'. Did you mean 'root.text'?}
    }

}
