// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

component Unrelated {
    property <string> private-by-default;    
}

export component Compo {
    property <string> i-forgot;
//  ^warning{Properties are private by default. If you want to use them from native code, use in, out or in-out. Use private to suppress this warning}

    in-out property <string> ok;

    Unrelated {  }
}

