// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

component ButtonBase inherits Text { }

component Button inherits ButtonBase {
    accessible-role: button;
    accessible-label: "optimized";
    extra-label := Text { }
}

export component TestCase {
    first := Button { }

    second := Button {
        accessible-label: "plain";
    }

    // third
    Button {
        accessible-label: "third";
    }
}

/*
```rust
let instance = TestCase::new().unwrap();
let mut button_search = slint_testing::ElementHandle::find_by_element_id(&instance, "Button::root");
let mut button = button_search.next().unwrap();
assert!(button.is_valid());
assert_eq!(button.accessible_label().unwrap(), "optimized");
button = button_search.next().unwrap();
assert!(button.is_valid());
assert_eq!(button.accessible_label().unwrap(), "plain");
button = button_search.next().unwrap();
assert!(button.is_valid());
assert_eq!(button.accessible_label().unwrap(), "third");
assert!(button_search.next().is_none());

assert_eq!(slint_testing::ElementHandle::find_by_element_id(&instance, "TestCase::second").count(), 1);
```
*/
