// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { FluentPalette, Icons } from "styling.slint";
import { FocusBorder } from "components.slint";
import { Pressable } from "../common/pressable.slint";

export component CheckBox {
    in property <string> text;
    in property <bool> enabled <=> pressable.enabled;
    in property <length> font-size;
    in property <int> font-weight;
    out property <bool> has-focus: pressable.has-focus;
    in-out property <bool> checked;

    callback toggled;

    private property <color> text-color: FluentPalette.foreground;

    min-height: max(18px, layout.min-height);
    accessible-checkable: true;
    accessible-enabled: root.enabled;
    accessible-label: root.text;
    accessible-checked <=> root.checked;
    accessible-role: checkbox;
    accessible-action-default => {
        if (root.enabled) {
           pressable.activate();
        }
    }
    forward-focus: pressable;

    states [
        disabled when !root.enabled : {
            border.border-color: FluentPalette.control-strong-stroke-disabled;
            background.background: root.checked ? FluentPalette.accent-disabled : FluentPalette.control-alt-disabled;
            icon.colorize: FluentPalette.text-accent-foreground-disabled;
            root.text-color: FluentPalette.text-disabled;
        }
        pressed when pressable.pressed : {
            border.border-color: FluentPalette.control-strong-stroke-disabled;
            background.background: root.checked ? FluentPalette.tertiary-accent-background : FluentPalette.control-alt-quaternary;
            icon.colorize: FluentPalette.text-accent-foreground-secondary;
        }
        hover when pressable.has-hover : {
            background.background: root.checked ?  FluentPalette.secondary-accent-background : FluentPalette.control-alt-tertiary;
        }
        checked when root.checked && root.enabled : {
            background.background: FluentPalette.accent-background;
        }
    ]

    animate text-color { duration: 200ms; }

    pressable := Pressable {
        activated => {
            root.checked = !root.checked;
            root.toggled();
        }

        layout := HorizontalLayout {
            spacing: 12px;

            background := Rectangle {
                width: 18px;
                height: self.width;
                y: (parent.height - self.height) / 2;
                background: FluentPalette.control-alt-secondary;
                border-radius: 2px;

                animate background, border-color { duration: 150ms; }

                border := Rectangle {
                    border-color: FluentPalette.control-strong-stroke;
                    border-width: root.checked ? 0 : 1px;
                    border-radius: parent.border-radius;
                }

                icon := Image {
                    image-fit: contain;
                    visible: root.checked;
                    source: Icons.check-mark;
                    colorize: FluentPalette.accent-foreground;
                    width: 12px;
                    accessible-role: none;

                    animate colorize { duration: 150ms; }
                }
            }

            if root.text != "" : Text {
                text: root.text;
                color: root.text-color;
                font-size: root.font-size;
                font-weight: root.font-weight;
                vertical-alignment: center;
                horizontal-alignment: left;
                accessible-role: none;
            }
        }

        // focus border
        if (root.has-focus && root.enabled) : FocusBorder {
            border-radius: 4px;
        }
    }
}
