// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { FluentPalette, FluentFontSettings } from "styling.slint";
import { MenuBarItemBase, MenuBarBase, MenuFrameBase, MenuItemBase } from "../common/menu-base.slint";

export component MenuBarItem {
    in property <MenuEntry> entry <=> base.entry;

    callback clicked <=> base.clicked;
    callback hovered <=> base.hovered;

    min-width: base.min-width;
    min-height: base.min-height;

    base := MenuBarItemBase {
        horizontal-padding: 11px;
        top-padding: 4px;
        bottom-padding: 6px;
        default-foreground: FluentPalette.foreground;
        hover-foreground: FluentPalette.foreground;
        pressed-foreground: FluentPalette.text-secondary;
        hover-background: FluentPalette.subtle-secondary;
        pressed-background: FluentPalette.control-alt-tertiary;
        font-size: FluentFontSettings.body.font-size;
        font-weight: FluentFontSettings.body.font-weight;
        border-radius: 3px;
    }
}

export component MenuBar inherits MenuBarBase {
    spacing: 10px;
    min-layout-height: 40px;
}

export component MenuFrame inherits MenuFrameBase {
    background: FluentPalette.background;
    border-radius: 7px;
    border-width: 1px;
    border-color: FluentPalette.border;
    drop-shadow-color: FluentPalette.shadow;
    drop-shadow-offset-y: 8px;
    drop-shadow-blur: 16px;
    margin: 1px;
    layout-min-width: 280px;
}

export component MenuItem {
    in property <bool> is-current <=> base.is-current;
    in property <MenuEntry> entry <=> base.entry;

    callback set-current <=> base.set-current;
    callback clear-current <=> base.clear-current;
    callback activate <=> base.activate;

    min-height: max(40px, base.min-height);

    HorizontalLayout {
        padding: 5px;

        base := MenuItemBase {
            default-foreground: FluentPalette.foreground;
            current-foreground: FluentPalette.foreground;
            current-background: FluentPalette.subtle-secondary;
            separator-color: FluentPalette.border;
            font-size: FluentFontSettings.body.font-size;
            font-weight: FluentFontSettings.body.font-weight;
            border-radius: 4px;
            horizontal-padding: 11px;
            spacing: 8px;
            sub-menu-icon: @image-url("_arrow_forward.svg");
            icon-size: 12px;
        }
    }
}
