// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { FluentPalette } from "styling.slint";
import { ProgressIndicatorBase } from "../common/progressindicator-base.slint";

export component ProgressIndicator inherits ProgressIndicatorBase {
    min-height: 3px;
    horizontal-stretch: 1;
    vertical-stretch: 0;

    Rectangle {
        clip: true;

        i-rail := Rectangle {
            height: 1px;
            background: FluentPalette.border;
            border-radius: 1px;
        }

        i-track := Rectangle {
            width: !root.indeterminate ? parent.width * root.normalized-progress : parent.width;
            height: 100%;
            x: !root.indeterminate ? 0px : -parent.width + (parent.width * mod(animation-tick(), 2s) / 1s);
            border-radius: 3px;
            background: FluentPalette.accent-background;
        }
    }
}
