// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

use i_slint_compiler::{CompilerConfiguration, diagnostics::BuildDiagnostics, generator, parser};
use std::error::Error;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::{LazyLock, Mutex};

static GO_TEST_LOCK: LazyLock<Mutex<()>> = LazyLock::new(|| Mutex::new(()));

fn root_dir() -> PathBuf {
    let mut root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    root.pop();
    root.pop();
    root.pop();
    root
}

fn host_goos() -> Result<&'static str, String> {
    match std::env::consts::OS {
        "linux" => Ok("linux"),
        "macos" => Ok("darwin"),
        "windows" => Ok("windows"),
        os => Err(format!("unsupported host OS for Go driver: {os}")),
    }
}

fn host_goarch() -> Result<&'static str, String> {
    match std::env::consts::ARCH {
        "x86_64" => Ok("amd64"),
        "aarch64" => Ok("arm64"),
        arch => Err(format!("unsupported host architecture for Go driver: {arch}")),
    }
}

fn target_id(goos: &str, goarch: &str) -> String {
    format!("{goos}_{goarch}")
}

fn cpp_lib_path() -> PathBuf {
    PathBuf::from(env!("CPP_LIB_PATH"))
}

fn static_artifact_names(_goos: &str) -> &'static [&'static str] {
    &["libslint_cpp.a"]
}

fn runtime_artifact_names(goos: &str) -> Vec<&'static str> {
    match goos {
        "darwin" => vec!["libslint_cpp.dylib", "libslint_cpp.a"],
        "windows" => vec!["slint_cpp.dll", "slint_cpp.dll.a", "slint_cpp.lib", "libslint_cpp.a"],
        _ => vec!["libslint_cpp.so", "libslint_cpp.a"],
    }
}

fn copy_file(src: &Path, dst: &Path) -> Result<(), String> {
    std::fs::create_dir_all(dst.parent().unwrap()).map_err(|err| {
        format!("failed to create destination directory {}: {err}", dst.parent().unwrap().display())
    })?;
    std::fs::copy(src, dst).map_err(|err| {
        format!(
            "failed to copy runtime artifact from {} to {}: {err}",
            src.display(),
            dst.display()
        )
    })?;
    Ok(())
}

fn runtime_flags(goos: &str, target_id: &str, dist_dir: &Path) -> String {
    let static_name = static_artifact_names(goos)
        .iter()
        .find(|name| dist_dir.join(name).exists())
        .expect("static artifact missing");
    let mut flags = vec![format!("${{SRCDIR}}/.slint-build/dist/{}/{}", target_id, static_name)];
    match goos {
        "linux" => flags.extend(
            ["-ldl", "-lm", "-lpthread", "-lfontconfig"].into_iter().map(ToString::to_string),
        ),
        "windows" => flags.extend(
            [
                "-lntdll",
                "-lopengl32",
                "-lgdi32",
                "-lcomctl32",
                "-lole32",
                "-loleaut32",
                "-luuid",
                "-limm32",
                "-ldwmapi",
                "-luxtheme",
                "-lws2_32",
                "-luserenv",
                "-lshlwapi",
                "-luser32",
            ]
            .into_iter()
            .map(ToString::to_string),
        ),
        _ => {}
    }
    flags.join(" ")
}

fn write_runtime_files(
    ui_dir: &Path,
    goos: &str,
    target_id: &str,
    cpp_lib_dir: &Path,
) -> Result<(), String> {
    let staged_dist = ui_dir.join(".slint-build").join("dist").join(target_id);
    std::fs::create_dir_all(&staged_dist)
        .map_err(|err| format!("failed to create {}: {err}", staged_dist.display()))?;

    for artifact_name in runtime_artifact_names(goos) {
        let src = cpp_lib_dir.join(artifact_name);
        if src.exists() {
            copy_file(&src, &staged_dist.join(artifact_name))?;
        }
    }

    let contents = format!(
        "// Code generated by Slint. DO NOT EDIT.\n\npackage ui\n\n/*\n#cgo LDFLAGS: {}\n*/\nimport \"C\"\n",
        runtime_flags(goos, target_id, &staged_dist)
    );
    std::fs::write(ui_dir.join("runtime.go"), contents)
        .map_err(|err| format!("failed to write Go runtime file in {}: {err}", ui_dir.display()))?;

    Ok(())
}

fn library_search_path_env_with(value_to_prepend: &Path) -> (&'static str, String) {
    let (var, separator) = if cfg!(target_os = "windows") {
        ("PATH", ';')
    } else if cfg!(target_os = "macos") {
        ("DYLD_FALLBACK_LIBRARY_PATH", ':')
    } else {
        ("LD_LIBRARY_PATH", ':')
    };
    (
        var,
        format!(
            "{}{}{}",
            value_to_prepend.display(),
            separator,
            std::env::var(var).unwrap_or_default()
        ),
    )
}

fn go_mod_cache() -> Result<PathBuf, String> {
    let output = std::process::Command::new("go")
        .arg("env")
        .arg("GOMODCACHE")
        .output()
        .map_err(|err| format!("failed to query Go module cache: {err}"))?;
    if !output.status.success() {
        return Err(format!(
            "failed to query Go module cache:\n{}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let value = String::from_utf8(output.stdout)
        .map_err(|err| format!("failed to decode Go module cache path: {err}"))?;
    Ok(PathBuf::from(value.trim()))
}

fn go_build_cache(target_id: &str) -> Result<PathBuf, String> {
    let cache_dir =
        root_dir().join("target").join("test-driver-go").join("gocache").join(target_id);
    std::fs::create_dir_all(&cache_dir)
        .map_err(|err| format!("failed to create Go build cache {}: {err}", cache_dir.display()))?;
    Ok(cache_dir)
}

fn write_go_module(dir: &Path) -> Result<(), String> {
    let go_mod = "module github.com/slint-ui/slint\n\ngo 1.26\n\nrequire github.com/stretchr/testify v1.11.1\n".to_string();
    std::fs::write(dir.join("go.mod"), go_mod)
        .map_err(|err| format!("failed to write go.mod in {}: {err}", dir.display()))
        .and_then(|_| {
            std::fs::copy(root_dir().join("go.sum"), dir.join("go.sum"))
                .map_err(|err| format!("failed to write go.sum in {}: {err}", dir.display()))?;
            Ok(())
        })
}

fn write_go_main(dir: &Path, source: &str) -> Result<(), Box<dyn Error>> {
    let go_blocks = test_driver_lib::extract_test_functions(source)
        .filter(|function| function.language_id == "go")
        .map(|function| function.source.to_string())
        .collect::<Vec<String>>();

    let mut file = std::fs::File::create(dir.join("main.go"))?;
    file.write_all(b"package main\n\nimport (\n")?;
    file.write_all(b"\tslint \"github.com/slint-ui/slint/api/go/slint\"\n")?;
    if !go_blocks.is_empty() {
        file.write_all(b"\t\"fmt\"\n")?;
        file.write_all(b"\tui \"github.com/slint-ui/slint/ui\"\n")?;
        file.write_all(b"\tassertpkg \"github.com/stretchr/testify/assert\"\n")?;
    } else {
        file.write_all(b"\t_ \"github.com/slint-ui/slint/ui\"\n")?;
    }
    file.write_all(b")\n\n")?;

    if !go_blocks.is_empty() {
        file.write_all(
            br#"type panicT struct{}

func (*panicT) Errorf(format string, args ...any) {
	panic(fmt.Sprintf(format, args...))
}

var assertion = assertpkg.New(&panicT{})

"#,
        )?;
    }

    file.write_all(b"func main() {\n")?;
    writeln!(file, "\tslint.InitTestingBackend()")?;

    for block in &go_blocks {
        writeln!(file, "\t{{")?;
        for line in block.lines() {
            writeln!(file, "\t\t{line}")?;
        }
        writeln!(file, "\t}}")?;
    }

    file.write_all(b"}\n")?;
    Ok(())
}

fn copy_go_runtime_package(dir: &Path) -> Result<(), String> {
    let source_dir = root_dir().join("api/go/slint");
    let destination_dir = dir.join("api/go/slint");
    std::fs::create_dir_all(&destination_dir)
        .map_err(|err| format!("failed to create {}: {err}", destination_dir.display()))?;
    for entry in std::fs::read_dir(&source_dir)
        .map_err(|err| format!("failed to read {}: {err}", source_dir.display()))?
    {
        let entry =
            entry.map_err(|err| format!("failed to inspect Go runtime package entry: {err}"))?;
        if entry.file_type().map_err(|err| format!("failed to inspect file type: {err}"))?.is_file()
        {
            copy_file(&entry.path(), &destination_dir.join(entry.file_name()))?;
        }
    }
    Ok(())
}

fn go_mod_tidy(dir: &Path, go_cache: &Path, go_mod_cache: &Path) -> Result<(), String> {
    let output = std::process::Command::new("go")
        .arg("mod")
        .arg("tidy")
        .current_dir(dir)
        .env("GOCACHE", go_cache)
        .env("GOMODCACHE", go_mod_cache)
        .env("GOWORK", "off")
        .output()
        .map_err(|err| format!("failed to launch go mod tidy: {err}"))?;
    if !output.status.success() {
        return Err(format!(
            "go mod tidy failed\nSTDERR:\n{}\nSTDOUT:\n{}",
            String::from_utf8_lossy(&output.stderr),
            String::from_utf8_lossy(&output.stdout)
        ));
    }
    Ok(())
}

pub fn test(testcase: &test_driver_lib::TestCase) -> Result<(), Box<dyn Error>> {
    let _guard = GO_TEST_LOCK.lock().unwrap();

    let source = std::fs::read_to_string(&testcase.absolute_path)?;

    let include_paths =
        test_driver_lib::extract_include_paths(&source).map(PathBuf::from).collect::<Vec<_>>();
    let library_paths = test_driver_lib::extract_library_paths(&source)
        .map(|(k, v)| (k.to_string(), PathBuf::from(v)))
        .collect::<std::collections::HashMap<_, _>>();

    let mut diag = BuildDiagnostics::default();
    let syntax_node = parser::parse(source.clone(), Some(&testcase.absolute_path), &mut diag);
    let output_format = generator::OutputFormat::Go;

    let mut compiler_config = CompilerConfiguration::new(output_format.clone());
    compiler_config.include_paths = include_paths;
    compiler_config.library_paths = library_paths;
    compiler_config.style = testcase.requested_style.map(str::to_string);
    compiler_config.debug_info = true;
    if source.contains("//bundle-translations") {
        compiler_config.translation_path_bundle =
            Some(testcase.absolute_path.parent().unwrap().to_path_buf());
        compiler_config.translation_domain =
            Some(testcase.absolute_path.file_stem().unwrap().to_str().unwrap().to_string());
    }
    if source.contains("//no-default-translation-context") {
        compiler_config.default_translation_context =
            i_slint_compiler::DefaultTranslationContext::None;
    }

    let (root_component, diag, loader) =
        spin_on::spin_on(i_slint_compiler::compile_syntax_node(syntax_node, diag, compiler_config));

    if diag.has_errors() {
        let vec = diag.to_string_vec();
        return Err(vec.join("\n").into());
    }

    let keep_temp_files = std::env::var("KEEP_TEMP_FILES").is_ok();
    let dir = tempfile::Builder::new().prefix("slint-go-driver").tempdir()?;
    let dir = scopeguard::guard(dir, |dir| {
        if !keep_temp_files {
            dir.close().unwrap_or(());
        }
    });
    let ui_dir = dir.path().join("ui");
    std::fs::create_dir_all(&ui_dir)?;

    let generated_go_path = ui_dir.join("testcase.slint.go");
    let mut generated_go: Vec<u8> = Vec::new();
    generator::generate(
        output_format,
        &mut generated_go,
        Some(&generated_go_path),
        &root_component,
        &loader.compiler_config,
    )?;

    if diag.has_errors() {
        let vec = diag.to_string_vec();
        return Err(vec.join("\n").into());
    }

    std::fs::write(&generated_go_path, generated_go)
        .map_err(|err| format!("Error writing generated code: {err}"))?;
    write_go_module(dir.path()).map_err(std::io::Error::other)?;
    copy_go_runtime_package(dir.path()).map_err(std::io::Error::other)?;
    write_go_main(dir.path(), &source)?;
    let goos = host_goos().map_err(std::io::Error::other)?;
    let goarch = host_goarch().map_err(std::io::Error::other)?;
    let target_id = target_id(goos, goarch);
    let cpp_lib_dir = cpp_lib_path();
    write_runtime_files(&ui_dir, goos, &target_id, &cpp_lib_dir).map_err(std::io::Error::other)?;
    let staged_dist = ui_dir.join(".slint-build").join("dist").join(&target_id);
    let go_cache = go_build_cache(&target_id).map_err(std::io::Error::other)?;
    let go_mod_cache = go_mod_cache().map_err(std::io::Error::other)?;
    go_mod_tidy(dir.path(), &go_cache, &go_mod_cache).map_err(std::io::Error::other)?;

    if keep_temp_files {
        println!(
            "Leaving temporary files behind for {} : {}",
            testcase.absolute_path.display(),
            dir.path().display()
        );
    }

    let output = std::process::Command::new("go")
        .arg("run")
        .arg("-tags")
        .arg("slint_static,slint_testing")
        .arg(".")
        .current_dir(dir.path())
        .env("GOCACHE", &go_cache)
        .env("GOMODCACHE", &go_mod_cache)
        .env("SLINT_BACKEND", "testing")
        .env("SLINT_ENABLE_EXPERIMENTAL_FEATURES", "1")
        .env("SLINT_SCALE_FACTOR", "1")
        .env("CGO_ENABLED", "1")
        .envs(std::iter::once(library_search_path_env_with(&staged_dist)))
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output()
        .map_err(|err| format!("could not launch go run: {err}"))?;

    if !output.status.success() {
        print!("{}", String::from_utf8_lossy(output.stdout.as_ref()));
        print!("{}", String::from_utf8_lossy(output.stderr.as_ref()));
        return Err(String::from_utf8_lossy(output.stderr.as_ref()).into_owned().into());
    }

    Ok(())
}
