// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

import { Button } from "std-widgets.slint";

export component TestCase inherits Rectangle {
    cont1 := ComponentContainer { }

    cont2 := ComponentContainer { }

    outside := Button { text: "Outside button"; }

    in property<component-factory> c1 <=> cont1.component-factory;
    in property<component-factory> c2 <=> cont2.component-factory;
    out property<bool> outside-focus <=> outside.has-focus;
}

/*
```cpp
// ComponentFactory not supported yet!

// THIS TEST IS HARD DISABLED IN build.rs of the C++ test driver
```

```rust
let factory = slint::ComponentFactory::new(|| {
     let mut compiler = slint_interpreter::ComponentCompiler::new();
     let e = spin_on::spin_on(compiler.build_from_source(
        r#"import { Button } from "std-widgets.slint";

export component E1 inherits Rectangle {
    background: Colors.red;

    Button {
        text: "red";
    }
}"#.into(),
        std::path::PathBuf::from("embedded.slint"),
     )).unwrap();
     e.create().ok()
});

let instance = TestCase::new().unwrap();
assert!(!instance.get_outside_focus()); // Nothing has focus be default
slint_testing::send_keyboard_string_sequence(&instance, "\t");
assert!(instance.get_outside_focus()); // The outside button is the only thing
                                       // accepting focus at this point.

instance.set_c1(factory.clone());
instance.set_c2(factory);

assert!(instance.get_outside_focus()); // embedding does not move the focus

// focus the two embedded buttons:
slint_testing::send_keyboard_string_sequence(&instance, "\t");
assert!(!instance.get_outside_focus());
slint_testing::send_keyboard_string_sequence(&instance, "\t");
assert!(!instance.get_outside_focus());

// Go back to outside button
slint_testing::send_keyboard_string_sequence(&instance, "\t");
assert!(instance.get_outside_focus());

// Focus backwards over the embedded buttons
slint_testing::send_keyboard_string_sequence(&instance, "\u{0019}");
assert!(!instance.get_outside_focus());
slint_testing::send_keyboard_string_sequence(&instance, "\u{0019}");
assert!(!instance.get_outside_focus());

slint_testing::send_keyboard_string_sequence(&instance, "\u{0019}");
assert!(instance.get_outside_focus());
```

```js
var _instance = new slint.TestCase();
```
*/
