// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// Allow for accessing built-in functions on root elements even with an injected window item

export component TestCase inherits TextInput {
    width: 100phx;
    height: 100phx;

    out property<bool> selection-set;

    text: "Hello World";
    if (true): TouchArea {
        clicked => {
            root.select-all();
            root.selection-set = root.anchor-position-byte-offset == 0 && root.cursor-position-byte-offset == 11;
        }
    }
}

/*

```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert(!instance.get_selection_set());
slint_testing::send_mouse_click(&instance, 5., 5.);
assert(instance.get_selection_set());
```

```rust
let instance = TestCase::new().unwrap();
assert!(!instance.get_selection_set());
slint_testing::send_mouse_click(&instance, 5., 5.);
assert!(instance.get_selection_set());
```

```js
var instance = new slint.TestCase();
assert(!instance.selection_set);
slintlib.private_api.send_mouse_click(instance, 5., 5.);
assert(instance.selection_set);
```
*/
