// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component TestCase  {
    in-out property <int> touch1;

    in-out property <string> pointer-event-test;

    in property <bool> enabled1 <=> area.enabled;
    out property <bool> pressed1 <=> area.pressed;
    out property <bool> has-hover1 <=> area.has-hover;

    width: 800px;
    height: 600px;

    Rectangle {
        x: 0phx;
        y: -5phx;
        width: 200phx;
        height: 10phx;
        rotation-angle: 45deg;
        rotation-origin-x: 0phx;
        rotation-origin-y: 5phx;
        background: area.has-hover? green : red;
        area := TouchArea {
            clicked => {
                pointer-event-test += "click";
                touch1+=1;
            }
            pointer-event(e) => {
                if (e.kind == PointerEventKind.cancel) {
                    pointer-event-test += "cancel";
                } else if (e.kind == PointerEventKind.up) {
                    pointer-event-test += "up";
                } else if (e.kind == PointerEventKind.down) {
                    pointer-event-test += "down";
                } else if (e.kind == PointerEventKind.move) {
                    pointer-event-test += "move";
                } else {
                    pointer-event-test += "err";
                }
                if (e.button == PointerEventButton.right) {
                    pointer-event-test += "right";
                } else if (e.button == PointerEventButton.left) {
                    pointer-event-test += "left";
                } else if (e.button == PointerEventButton.middle) {
                    pointer-event-test += "middle";
                } else if (e.button == PointerEventButton.back) {
                    pointer-event-test += "back";
                } else if (e.button == PointerEventButton.forward) {
                    pointer-event-test += "forward";
                } else if (e.button == PointerEventButton.other) {
                    pointer-event-test += "other";
                } else {
                    pointer-event-test += "???";
                }
                if (e.modifiers.control) {
                    pointer-event-test += "(ctrl)";
                }
                if (e.modifiers.shift) {
                    pointer-event-test += "(shift)";
                }
                if (e.modifiers.meta) {
                    pointer-event-test += "(meta)";
                }
                if (e.modifiers.alt) {
                    pointer-event-test += "(alt)";
                }
            }
        }
    }
}

/*
```rust
use slint::private_unstable_api::re_exports::MouseCursor;

let instance = TestCase::new().unwrap();
assert_eq!(slint_testing::access_testing_window(instance.window(), |window| window.mouse_cursor.get()), MouseCursor::Default);

// can click on center

for i in 1 .. 100 {
dbg!(i);
slint_testing::send_mouse_click(&instance, i as f32, i as f32);
assert_eq!(instance.get_touch1(), i);
}
```
*/
