// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// When first trying to scroll horizontally and then vertically it should still be scrolled

import { ListView  } from "std-widgets.slint";

export component TestCase inherits Window {
    width: 400px;
    height: 540px;

    in-out property <length> content-y: listview.content-y;
    in-out property <length> content-x: listview.content-x;
    out property listview-content-height <=> listview.content-height;
    out property listview-content-width <=> listview.content-width;
    out property listview-preferred-height <=> listview.preferred-height;

    out property <bool> test: true;



    listview := ListView {
        width: parent.width;
        height: parent.height;
        mouse-drag-pan-enabled: true;

        for data in [
            { text: "Blue", color: #0000ff, bg: #eeeeee},
            { text: "Red", color: #ff0000, bg: #eeeeee},
            { text: "Green", color: #00ff00, bg: #eeeeee},
            { text: "Yellow", color: #ffff00, bg: #222222 },
            { text: "Black", color: #000000, bg: #eeeeee },
            { text: "White", color: #ffffff, bg: #222222 },
            { text: "Magenta", color: #ff00ff, bg: #eeeeee },
            { text: "Cyan", color: #00ffff, bg: #222222 },
        ] : delegate := Rectangle {
            background: @linear-gradient(90deg, data.bg,data.bg.brighter(0.5));
            HorizontalLayout {
                text_Name := Text {
                    height: 100px;
                    text: data.text;
                    color: data.color;
                    font_size: 20px ;
                }
            }
        }
    }
}

/*
```rust
use slint::{platform::WindowEvent, platform::PointerEventButton, LogicalPosition};

let instance = TestCase::new().unwrap();

// First try to scroll horizontally (But this will not work)
instance.window().dispatch_event(WindowEvent::PointerMoved { position: LogicalPosition::new(150.0, 200.0) });
slint_testing::mock_elapsed_time(16);
instance.window().dispatch_event(WindowEvent::PointerPressed { position: LogicalPosition::new(150.0, 200.0), button: PointerEventButton::Left });
slint_testing::mock_elapsed_time(16);
// Like a real drag, start with a move below the drag threshold
instance.window().dispatch_event(WindowEvent::PointerMoved { position: LogicalPosition::new(147.0, 200.0) });
slint_testing::mock_elapsed_time(16);
instance.window().dispatch_event(WindowEvent::PointerMoved { position: LogicalPosition::new(100.0, 200.0) });
slint_testing::mock_elapsed_time(16);
instance.window().dispatch_event(WindowEvent::PointerMoved { position: LogicalPosition::new(120.0, 200.0) });
// shouldn't move because the listview is vertical
assert_eq!(instance.get_content_x(), 0.);
assert_eq!(instance.get_content_y(), 0.);

// Now scroll vertically and it should work
slint_testing::mock_elapsed_time(4000);
instance.window().dispatch_event(WindowEvent::PointerMoved { position: LogicalPosition::new(100.0, 150.0) });
assert_eq!(instance.get_content_y(), -50.);
slint_testing::mock_elapsed_time(16);
instance.window().dispatch_event(WindowEvent::PointerMoved { position: LogicalPosition::new(100.0, 100.0) });
assert_eq!(instance.get_content_y(), -100.);
```

// Wait long after first press
```rust
use slint::{platform::WindowEvent, platform::PointerEventButton, LogicalPosition};

let instance = TestCase::new().unwrap();

// First try to scroll horizontally (But this will not work)
instance.window().dispatch_event(WindowEvent::PointerMoved { position: LogicalPosition::new(150.0, 200.0) });
slint_testing::mock_elapsed_time(16);
instance.window().dispatch_event(WindowEvent::PointerPressed { position: LogicalPosition::new(150.0, 200.0), button: PointerEventButton::Left });
slint_testing::mock_elapsed_time(300);
// Like a real drag, start with a move below the drag threshold
instance.window().dispatch_event(WindowEvent::PointerMoved { position: LogicalPosition::new(147.0, 200.0) });
slint_testing::mock_elapsed_time(16);
instance.window().dispatch_event(WindowEvent::PointerMoved { position: LogicalPosition::new(100.0, 200.0) });
slint_testing::mock_elapsed_time(16);
instance.window().dispatch_event(WindowEvent::PointerMoved { position: LogicalPosition::new(120.0, 200.0) });
// shouldn't move because the listview is vertical
assert_eq!(instance.get_content_x(), 0.);
assert_eq!(instance.get_content_y(), 0.);

// Now scroll vertically and it should work
slint_testing::mock_elapsed_time(4000);
instance.window().dispatch_event(WindowEvent::PointerMoved { position: LogicalPosition::new(100.0, 150.0) });
assert_eq!(instance.get_content_y(), -50.);
slint_testing::mock_elapsed_time(16);
instance.window().dispatch_event(WindowEvent::PointerMoved { position: LogicalPosition::new(100.0, 100.0) });
assert_eq!(instance.get_content_y(), -100.);
```

*/
