// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

TestCase := Rectangle {

    Text {
        text: "The path should fit into the red rectangle";
        color: black;
    }

    fit_rect := Rectangle {
        x: 0phx;
        y: 100phx;
        background: red;
        width: 700phx;
        height: 500phx;

        Path {
            x: 0phx;
            y: 0phx;
            width: fit_rect.width;
            height: fit_rect.height;
            commands: "M 100 300 Q 150 50 1100 400 Q 1450 500 750 500 Q 1000 600 950 600 C 325 575 350 450 150 550 Q 0 600 100 800 C 250 850 300 600 550 850 C 800 850 850 650 2000 700 ";
            stroke: black;
            stroke_width: 2px;
        }
    }
}
