// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Button } from "std-widgets.slint";

export component TestCase inherits Window {
    width: 400px;
    height: 400px;

    in-out property <int> popup_click_count;
	in-out property <length> popup_x;

	VerticalLayout {
		alignment: start;

		HorizontalLayout {
			Button {
				text: "Open";
				clicked => {
					popup_x = 0px;
					popup.show();
				}
			}
		}
	}

    popup := PopupWindow {
        x: popup_x;
		y: 200px;
		width: 200px;
		height: 200px;
		close-policy: no-auto-close;

		TouchArea {
			clicked => {
				popup_click_count += 1;

				if (popup_x == 0px) {
					popup_x = 200px;
					popup.show();
				}
			}
		}
    }
}

/*

```rust
#[allow(unused)]
use slint::{platform::WindowEvent, platform::PointerEventButton, LogicalPosition};
let instance = TestCase::new().unwrap();

// open on the left
slint_testing::send_mouse_click(&instance, 20., 10.);

// use left popup to open on the right
slint_testing::send_mouse_click(&instance, 10., 210.);
assert_eq!(instance.get_popup_click_count(), 1);

// no longer open on the left
slint_testing::send_mouse_click(&instance, 10., 210.);
assert_eq!(instance.get_popup_click_count(), 1);

// now open on the right
slint_testing::send_mouse_click(&instance, 210., 210.);
assert_eq!(instance.get_popup_click_count(), 2);

```

```cpp
auto handle = TestCase::create();
TestCase &instance = *handle;

// open on the left
slint_testing::send_mouse_click(&instance, 20., 10.);

// use left popup to open on the right
slint_testing::send_mouse_click(&instance, 10., 210.);
assert_eq(instance.get_popup_click_count(), 1);

// no longer open on the left
slint_testing::send_mouse_click(&instance, 10., 210.);
assert_eq(instance.get_popup_click_count(), 1);

// now open on the right
slint_testing::send_mouse_click(&instance, 210., 210.);
assert_eq(instance.get_popup_click_count(), 2);
```

*/
