// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { TabWidget } from "std-widgets.slint";

export component TestCase inherits Window {
    preferred_height: 500px;
    preferred_width: 500px;

    in-out property <int> current_tab: tw.current-index;

    VerticalLayout {
        padding: 20px;
        tw := TabWidget {
            current-index: 1;
            Tab {
                title: "Hello";
                Rectangle {
                    background: #8555;
                }

            }
            Tab {
                title: "World";
                Text { x:0;y:0; text: "This is the second widget"; }
            }
            Tab {
                title: "Third";
                Rectangle {
                    background: pink;
                }
                min_height: 200px;
            }
        }
    }

    in-out property <bool> test: tw.vertical_stretch == 1 && tw.horizontal_stretch == 1 && tw.min_height > 200px && root.current-tab == 1;
}
