// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { CheckBox, GridBox, ListView, StyleMetrics } from "std-widgets.slint";

import { GallerySettings } from "../gallery_settings.slint";

export Page := GridLayout {
    property<string> title: "title";
    property<string> description: "description";

    padding: StyleMetrics.layout-padding;
    spacing: StyleMetrics.layout-spacing;
   
    // header
    Row {
        Text {  
            font-size: 28px;
            text <=> root.title;
        }

        // Spacer
        Rectangle {}

        CheckBox { 
            horizontal-stretch: 0;
            text: "Disable widgets";
            checked <=> GallerySettings.widgets-disabled;
        }
    }
    
    Row {
        GridLayout {  
            colspan: 3;
           

            @children
        }
    }

    // vertical spacer
    Row {
        Rectangle {}
    }
}