// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Palette, Button } from "std-widgets.slint";

export component EmptyWindow inherits Window {
    in property <string> name;
    in property <string> address;
    in property <string> message;
    in property <string> slint-version;
    in property <string> build-info;

    property <bool> has-name: name != "";
    property <bool> showing-name: true;

    property <bool> dark-color-scheme: Palette.color-scheme == ColorScheme.dark;

    hidden-input := TextInput {
        enabled: false;
        visible: false;
        text: root.address;
    }

    Rectangle {
        background: root.dark-color-scheme ? @linear-gradient(180deg, #1C1C1C, black) : @linear-gradient(0deg, #D7D9DD, white);
    }

    Image {
        y: root.height - self.height;
        width: 100%;
        source: root.dark-color-scheme ? @image-url("assets/bg-frame.svg") : @image-url("assets/bg-frame-light.svg");
    }

    TouchArea {
        y: 0;
        height: root.safe-area-insets.top + 246px;

        clicked => {
            hidden-input.select-all();
            hidden-input.copy();
            if hide-toast-timer.running == false {
                hide-toast-timer.start();
            } else {
                hide-toast-timer.restart();
            }

            toast.opacity = 1;
        }
    }

    hide-toast-timer := Timer {
        interval: 2000ms;
        running: false;
        triggered => {
            toast.opacity = 0;
            self.stop();
        }
    }


    VerticalLayout {
        alignment: space-between;
        padding-left: 24px;
        padding-top: root.safe-area-insets.top + 146px;
        padding-bottom: root.safe-area-insets.bottom;
        VerticalLayout {
            alignment: start;
            spacing: 8px;

            HorizontalLayout {
                alignment: start;
                spacing: 2px;
                cross-axis-alignment: end;
                opacity: 0.9;
                Text {
                    text: "Connect Live Preview to";
                    font-size: 1.41rem;
                    font-weight: 100;
                }
            }

            Text {
                text: root.showing-name && root.has-name ? name : address;
                font-size: 1.41rem;
                font-weight: 400;
            }
        }

        VerticalLayout {
            alignment: center;
            spacing: 8px;
            Text {
                text: root.slint-version;
                font-size: 0.82rem;
                font-weight: 400;
            }

            if root.build-info != "": Text {
                text: root.build-info;
                font-size: 0.71rem;
                font-weight: 400;
            }
        }
    }

    toast := Rectangle {
        y: root.height - root.safe-area-insets.bottom - self.height - 100px;
        width: 300px;
        height: 50px;
        border-radius: self.height / 2;
        drop-shadow-color: root.dark-color-scheme ? black : #0000002e;
        drop-shadow-blur: 30px;
        drop-shadow-offset-x: 10px;
        drop-shadow-offset-y: 10px;
        opacity: 0;
        animate opacity {
            duration: 300ms;
            easing: cubic-bezier(0.33, 1, 0.68, 1);
        }

        Rectangle {
            border-radius: parent.border-radius;
            background: root.dark-color-scheme ? #212121 : #f6f7f8;
            Text {
                text: @tr("IP copied to clipboard");
                font-weight: 400;
            }
        }

    }

    VerticalLayout {
        alignment: center;
        padding-left: 24px;
        padding-right: 24px;
        padding-top: root.safe-area-insets.top;
        padding-bottom: root.safe-area-insets.bottom;

        if message != "": Text {
            text: message;
            horizontal-alignment: center;
            font-weight: 400;
        }
    }
}
