// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

TestCase := Rectangle {
    property<duration> d1: 100ms;
    property<duration> d2: 3s;
    property<duration> d3: 1.5s;
    property<duration> d4: 30 * 1ms;
    property<duration> d5: 8ms + 3s;
    property<duration> d6: d1 - d2;
    property<duration> d7: -0.5s;
    property<duration> d8: -0.5s / 2 * 1px / 1px;
    property<int> i1: d1 / 1ms;
    property<int> i2: d1 / (2ms + 0);

    property<int> untyped_d1: self.d1 / 1ms;
    property<int> untyped_d2: self.d2 / 1ms;
    property<int> untyped_d3: self.d3 / 1ms;
    property<int> untyped_d4: self.d4 / 1ms;
    property<int> untyped_d5: self.d5 / 1ms;
    property<int> untyped_d6: self.d6 / 1ms;
    property<int> untyped_d7: self.d7 / 1ms;
    property<int> untyped_d8: self.d8 / 1ms;
}


/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert_eq(instance.get_untyped_d1(), 100);
assert_eq(instance.get_untyped_d2(), 3000);
assert_eq(instance.get_untyped_d3(), 1500);
assert_eq(instance.get_untyped_d4(), 30);
assert_eq(instance.get_untyped_d5(), 3008);
assert_eq(instance.get_untyped_d6(), -2900);
assert_eq(instance.get_untyped_d7(), -500);
assert_eq(instance.get_untyped_d8(), -250);
assert_eq(instance.get_i1(), 100);
assert_eq(instance.get_i2(), 50);
```


```rust
let instance = TestCase::new().unwrap();
assert_eq!(instance.get_untyped_d1(), 100);
assert_eq!(instance.get_untyped_d2(), 3000);
assert_eq!(instance.get_untyped_d3(), 1500);
assert_eq!(instance.get_untyped_d4(), 30);
assert_eq!(instance.get_untyped_d5(), 3008);
assert_eq!(instance.get_untyped_d6(), -2900);
assert_eq!(instance.get_untyped_d7(), -500);
assert_eq!(instance.get_untyped_d8(), -250);
assert_eq!(instance.get_i1(), 100);
assert_eq!(instance.get_i2(), 50);
```

```js
var instance = new slint.TestCase({});
assert.equal(instance.untyped_d1, 100);
assert.equal(instance.untyped_d2, 3000);
assert.equal(instance.untyped_d3, 1500);
assert.equal(instance.untyped_d4, 30);
assert.equal(instance.untyped_d5, 3008);
assert.equal(instance.untyped_d6, -2900);
assert.equal(instance.untyped_d7, -500);
assert.equal(instance.untyped_d8, -250);
assert.equal(instance.i1, 100);
assert.equal(instance.i2, 50);
```

```go
instance, err := ui.NewTestCase()
assertion.NoError(err)
untypedD1, err := instance.GetUntypedD1()
assertion.NoError(err)
assertion.Equal(100, untypedD1)
untypedD2, err := instance.GetUntypedD2()
assertion.NoError(err)
assertion.Equal(3000, untypedD2)
untypedD3, err := instance.GetUntypedD3()
assertion.NoError(err)
assertion.Equal(1500, untypedD3)
untypedD4, err := instance.GetUntypedD4()
assertion.NoError(err)
assertion.Equal(30, untypedD4)
untypedD5, err := instance.GetUntypedD5()
assertion.NoError(err)
assertion.Equal(3008, untypedD5)
untypedD6, err := instance.GetUntypedD6()
assertion.NoError(err)
assertion.Equal(-2900, untypedD6)
untypedD7, err := instance.GetUntypedD7()
assertion.NoError(err)
assertion.Equal(-500, untypedD7)
untypedD8, err := instance.GetUntypedD8()
assertion.NoError(err)
assertion.Equal(-250, untypedD8)
i1, err := instance.GetI1()
assertion.NoError(err)
assertion.Equal(100, i1)
i2, err := instance.GetI2()
assertion.NoError(err)
assertion.Equal(50, i2)
```
*/
