// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component TestCase {
    in-out property <keyboard-shortcut> shortcut: @keys(Control + Alt + Escape);
}


/*

```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;

const auto shortcut = instance.get_shortcut();
slint::SharedString shortcut_string;
slint::cbindgen_private::slint_keyboard_shortcut_to_string(&shortcut, &shortcut_string);
assert_eq(shortcut_string, "Alt+Control+\\u{1b}");
```

```rust
let instance = TestCase::new().unwrap();
let shortcut = instance.get_shortcut();
assert_eq!(shortcut.to_string(), "Alt+Control+\\u{1b}");
```

```js
var instance = new slint.TestCase({});

var shortcut = instance.shortcut;
assert.equal(shortcut, "Alt+Control+\\u{1b}")
```

*/
