// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

// This test case verifies that we do emit the code for the `Nested` struct,
// when it's only indirectly referenced through the `Item` struct.

struct Nested := {
    ok: bool
}

struct Item := {
    nested: Nested
}

export TestCase := Rectangle {
    property <Item> fob;
}
