// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// cSpell:ignore hellohellohello

export component TestCase {
    out property<string> s: "hello";
    out property <string> res: s.repeat(3);
}

/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert_eq(instance.get_res(), "hellohellohello");
```

```rust
let instance = TestCase::new().unwrap();
assert_eq!(instance.get_res(), "hellohellohello");
```

```js
var instance = new slint.TestCase({});
assert.equal(instance.res, "hellohellohello");
```
*/
