// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// Test that structs work if they are only referenced by callbacks

struct Foo1  { member: int, }
struct Foo2  { a: Foo1 }
struct Foo3  { b: int }

struct DeleteMe  { c: color }

struct Palette  {
    menuBar : brush,
    mainContent : brush,
    box : brush,
}

export component TestCase inherits Rectangle {
    pure callback cb1(Foo2) -> Foo3;
    cb1(foo) => { return { b: foo.a.member+1 }; }

    in-out property<Foo2> xx;
    pure callback cb2(Foo2, Foo2)->Foo2;
    in-out property<Foo2> xx2: root.cb2(root.xx, root.xx);


    // Based on Issue #1733
    Rectangle {
        property<[DeleteMe]> data;
        for d[i] in self.data: Rectangle { }
    }

    // Bug #2765
    out property<Palette> palette : xx.a.member > 32 ? {
       menuBar : #6D7BFB,
       mainContent :  #fbfbfb,
       box :   #ffffff,
    } : {
       menuBar : #2937A7,
       mainContent : #040404,
       box : #000000,
    };

}


/*
```rust
let instance = TestCase::new().unwrap();

assert_eq!(instance.invoke_cb1(Foo2{ a: Foo1{ member: 123 } }).b, 124);
```

```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;

assert_eq(instance.invoke_cb1(Foo2{ Foo1{ 123 } }).b, 124);
```

```d.ts
export interface DeleteMe {
    c: slint.Brush | slint.RgbaColor | string;
}

export interface Foo1 {
    member: number;
}

export interface Foo2 {
    a: Foo1;
}

export interface Foo3 {
    b: number;
}

export interface Palette {
    box: slint.Brush | string;
    mainContent: slint.Brush | string;
    menuBar: slint.Brush | string;
}

export interface TestCase {
    cb1: (arg_0: Foo2) => Foo3;
    cb2: (arg_0: Foo2, arg_1: Foo2) => Foo2;
    readonly palette: Palette;
    xx: Foo2;
    xx2: Foo2;
}

export declare const TestCase: { new(properties?: Partial<TestCase>): TestCase & slint.ComponentHandle };
export declare function DeleteMe(properties?: Partial<DeleteMe>): DeleteMe;
export declare function Foo1(properties?: Partial<Foo1>): Foo1;
export declare function Foo2(properties?: Partial<Foo2>): Foo2;
export declare function Foo3(properties?: Partial<Foo3>): Foo3;
export declare function Palette(properties?: Partial<Palette>): Palette;
```

```js
var instance = new slint.TestCase();
assert.equal(instance.cb1({a: {member: 123}}).b, 124);
```

*/
