// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

//! Code generator for the Slint SC (safety-critical) runtime.
//!
//! Slint SC is a drastically reduced subset of Slint: no layouts, no
//! callbacks, no models, no text, no animations, and only three visual
//! elements (`Window`, `Rectangle`, `Image`).  The generator walks the
//! post-pass `object_tree` directly — LLR would be overkill — and emits a
//! small, auditable Rust module that depends only on the `slint_sc` runtime
//! crate.  Anything outside the supported subset causes a compile error with
//! a clear diagnostic.
//!
//! The generated code shape for
//!
//! ```slint,ignore
//! export component Hello inherits Window {
//!     width: 100px; height: 50px;
//!     Rectangle { x: 10px; y: 10px; width: 20px; height: 20px; background: red; }
//! }
//! ```
//!
//! is roughly
//!
//! ```ignore
//! pub struct Hello { /* user-declared properties as `Property<T>` */ }
//! impl Hello {
//!     pub fn new() -> Self { ... }
//!     pub fn render<B: slint_sc::TargetPixelBuffer>(&self, buffer: &mut B) {
//!         slint_sc::private_unstable_api::fill_rectangle(buffer, 10, 10, 20, 20, Color::...);
//!     }
//! }
//! ```

use crate::CompilerConfiguration;
use crate::embedded_resources::EmbeddedResourcesKind;
#[cfg(feature = "software-renderer")]
use crate::embedded_resources::PixelFormat;
use crate::expression_tree::{Expression, ImageReference, Unit};
use crate::langtype::{ElementType, Type};
use crate::object_tree::{Component, Document, Element, ElementRc};
use itertools::Either;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use smol_str::SmolStr;
use std::rc::Rc;

/// Mutable context carried through every `emit_*` helper.
struct Ctx {
    errors: Vec<String>,
    /// Compile-time scale factor applied to `px` literals so that every
    /// coordinate the generated code emits is already in physical pixels.
    /// Slint SC has no runtime window with a scale factor — the rendering
    /// buffer is addressed directly in physical pixels — so we have to
    /// bake this conversion in at generation time.
    scale_factor: f32,
}

/// Public entry point called from `generator::generate`.
pub fn generate(
    doc: &Document,
    compiler_config: &CompilerConfiguration,
) -> std::io::Result<TokenStream> {
    let mut ctx = Ctx {
        errors: Vec::new(),
        scale_factor: compiler_config.const_scale_factor.unwrap_or(1.0),
    };

    let textures = emit_resources(doc, &mut ctx);

    let mut components = Vec::new();
    let mut public_names = Vec::new();
    for (exported_name, entry) in doc.exports.clone().into_iter() {
        if let Either::Left(component) = entry {
            components.push(emit_component(&exported_name.name, &component, &mut ctx));
            public_names.push(format_ident!("{}", exported_name.name.as_str()));
        }
    }

    if !ctx.errors.is_empty() {
        return Err(std::io::Error::other(format!(
            "slint-sc generator errors:\n  - {}",
            ctx.errors.join("\n  - ")
        )));
    }

    // Wrap the output in a private `mod slint_sc_generated { ... }` so we
    // can put an inner `#![allow(...)]` *there*.  The user's own code
    // never sees those lint suppressions, and the public components are
    // re-exported at the include site so the ergonomics match the normal
    // `slint::include_modules!()` flow.
    let out = quote! {
        // Generated by the Slint SC compiler generator.  Do not edit.
        mod slint_sc_generated {
            #![allow(
                non_snake_case,
                non_camel_case_types,
                non_upper_case_globals,
                unused_imports,
                unused_parens,
                unused_braces,
                dead_code,
                clippy::all,
                clippy::pedantic,
                clippy::nursery,
            )]

            use slint_sc as sp;
            #(#textures)*
            #(#components)*
        }
        pub use slint_sc_generated::{#(#public_names),*};
    };

    Ok(out)
}

use super::rust::ident;

fn texture_symbol(id: usize) -> proc_macro2::Ident {
    format_ident!("SLINT_SC_TEXTURE_{}", id)
}

/// Rust type used to store a user-declared property of the given Slint type.
fn property_rust_type(ty: &Type) -> Option<TokenStream> {
    Some(match ty {
        Type::Bool => quote!(bool),
        Type::Int32 => quote!(i32),
        Type::Float32 => quote!(f32),
        Type::Color => quote!(sp::Color),
        // A brush in this subset is always a solid color.
        Type::Brush => quote!(sp::Color),
        // Lengths are stored as plain f32 physical pixels (no logical/physical
        // distinction in the prototype).
        Type::PhysicalLength | Type::LogicalLength => quote!(f32),
        _ => return None,
    })
}

fn property_default(ty: &Type) -> TokenStream {
    match ty {
        Type::Bool => quote!(false),
        Type::Int32 => quote!(0i32),
        Type::Float32 => quote!(0.0f32),
        Type::Color | Type::Brush => quote!(sp::Color::from_argb_encoded(0)),
        Type::PhysicalLength | Type::LogicalLength => quote!(0.0f32),
        _ => quote!(Default::default()),
    }
}

fn emit_resources(doc: &Document, ctx: &mut Ctx) -> Vec<TokenStream> {
    let errors = &mut ctx.errors;
    let mut out = Vec::new();
    for (_path, res) in doc.embedded_file_resources.borrow().iter() {
        match &res.kind {
            #[cfg(feature = "software-renderer")]
            EmbeddedResourcesKind::TextureData(tex) => {
                let format_tokens = match tex.format {
                    PixelFormat::Rgb => quote!(sp::private_unstable_api::PixelFormat::Rgb),
                    PixelFormat::RgbaPremultiplied => {
                        quote!(sp::private_unstable_api::PixelFormat::RgbaPremultiplied)
                    }
                    PixelFormat::Rgba => {
                        errors.push(
                            "slint-sc requires embed-resources=EmbedForSoftwareRenderer; \
                             got a non-premultiplied Rgba texture"
                                .into(),
                        );
                        continue;
                    }
                    PixelFormat::AlphaMap(_) => {
                        errors.push(
                            "slint-sc does not yet support AlphaMap textures (masked fonts / \
                             monochrome sprites)"
                                .into(),
                        );
                        continue;
                    }
                };

                // `Texture::data` already holds exactly the bytes of the
                // trimmed sub-rectangle (see `embed_images::convert_image`
                // which walks `SubImage::new(..., rect)`), so the rect's
                // width and height are the texture's natural dimensions
                // and we emit the data verbatim.
                // The rect's offset inside the original image is carried
                // through so the runtime can place the visible pixels where
                // the software renderer would.
                let rect_w = tex.rect.width() as u32;
                let rect_h = tex.rect.height() as u32;
                let rect_x = tex.rect.x() as u32;
                let rect_y = tex.rect.y() as u32;

                let sym = texture_symbol(res.id);
                let sym_data = format_ident!("{}_DATA", sym);
                let data_len = tex.data.len();
                let data_iter = tex.data.iter().copied();
                out.push(quote! {
                    // 8-byte alignment via a zero-length u32 array (same trick
                    // as the normal Slint generator).
                    static #sym_data: ([u8; #data_len], [u32; 0]) = ([#(#data_iter),*], []);
                    static #sym: sp::private_unstable_api::StaticTexture =
                        sp::private_unstable_api::StaticTexture {
                            width: #rect_w,
                            height: #rect_h,
                            offset_x: #rect_x,
                            offset_y: #rect_y,
                            data: &#sym_data.0,
                            format: #format_tokens,
                        };
                });
            }
            EmbeddedResourcesKind::ListOnly => {}
            // Bitmap fonts may be pulled in by the default style even if the
            // .slint source has no text: silently ignore them — Slint SC does
            // not render text anyway.
            #[cfg(feature = "software-renderer")]
            EmbeddedResourcesKind::BitmapFontData(_) => {}
            EmbeddedResourcesKind::FileData | EmbeddedResourcesKind::DataUriPayload(_, _) => {
                errors.push(
                    "slint-sc: embedded file resources are not supported, use \
                     embed-resources=EmbedForSoftwareRenderer so that images are pre-decoded"
                        .into(),
                );
            }
        }
    }
    out
}

#[derive(Debug)]
enum ItemKind {
    Window,
    Rectangle,
    Image,
}

/// One element flattened out by [`walk_items`] into a draw-order list,
/// with its absolute origin pre-computed as a Rust expression.
struct DrawItem {
    kind: ItemKind,
    element: ElementRc,
    /// Absolute x in physical pixels, as `i32`.
    /// For a child rectangle `{ x: 6px }` inside `{ x: 4px }`, this is
    /// `(0 + 4) + 6`.
    abs_x: TokenStream,
    /// Absolute y in physical pixels, as `i32`.
    abs_y: TokenStream,
}

struct RootProperty {
    name: SmolStr,
    is_public: bool,
    ty: Type,
    default: Option<TokenStream>,
}

fn emit_component(
    exported_name: &SmolStr,
    component: &Rc<Component>,
    ctx: &mut Ctx,
) -> TokenStream {
    let struct_name = format_ident!("{}", exported_name.as_str());
    let user_props = collect_root_properties(component, ctx);

    // Each draw item carries the absolute origin at which it should be
    // drawn, expressed as a Rust token stream that sums the element's own
    // x/y with every ancestor's x/y.
    // See [`walk_items`] for the walk.
    let mut draw_items: Vec<DrawItem> = Vec::new();
    walk_items(&component.root_element, &quote!(0i32), &quote!(0i32), ctx, &mut draw_items);

    let prop_fields = user_props.iter().map(|p| {
        let n = ident(&p.name);
        let t = property_rust_type(&p.ty).unwrap();
        quote! { #n: sp::private_unstable_api::Property<#t>, }
    });
    let prop_defaults = user_props.iter().map(|p| {
        let n = ident(&p.name);
        let default = p.default.clone().unwrap_or_else(|| property_default(&p.ty));
        quote! { #n: sp::private_unstable_api::Property::new(#default), }
    });
    // Only properties the user declared with `in` / `out` / `in-out`
    // visibility get public accessors; materialised fake properties
    // (`fixed_width`, `rectangle_N_x`, …) stay behind the struct wall.
    let prop_accessors = user_props.iter().filter(|p| p.is_public).map(|p| {
        let n = ident(&p.name);
        let snake = p.name.replace('-', "_");
        let get_n = format_ident!("get_{}", snake);
        let set_n = format_ident!("set_{}", snake);
        let t = property_rust_type(&p.ty).unwrap();
        quote! {
            pub fn #get_n(&self) -> #t { self.#n.get() }
            pub fn #set_n(&self, value: #t) { self.#n.set(value); }
        }
    });

    let mut render_body = TokenStream::new();
    for item in &draw_items {
        render_body.extend(emit_draw(item, ctx));
    }

    quote! {
        pub struct #struct_name {
            #(#prop_fields)*
        }

        impl #struct_name {
            pub fn new() -> Self {
                Self { #(#prop_defaults)* }
            }

            #(#prop_accessors)*

            pub fn render<B: sp::TargetPixelBuffer>(&self, buffer: &mut B) {
                let _self = self;
                #render_body
            }
        }

        impl Default for #struct_name {
            fn default() -> Self { Self::new() }
        }
    }
}

/// Collects every property stored on the root element — both user-declared
/// and materialised by later compiler passes — together with their initial
/// bindings.
fn collect_root_properties(component: &Rc<Component>, ctx: &mut Ctx) -> Vec<RootProperty> {
    let root = component.root_element.borrow();
    let mut out = Vec::new();
    for (name, decl) in &root.property_declarations {
        if !decl.property_type.is_property_type() {
            // Materialised properties are always plain data properties, so a
            // non-data declaration must come from the user.
            if decl.expose_in_public_api {
                ctx.errors.push(format!(
                    "slint-sc: property `{name}` has unsupported kind (only plain data \
                     properties are allowed — callbacks, functions and models are rejected)"
                ));
            }
            continue;
        }
        // Image-typed properties have no runtime storage: they are
        // compile-time aliases for a static texture.
        // `resolve_static_image` follows the `PropertyReference` back to
        // the `@image-url(...)` binding, so no field, getter or setter is
        // emitted.
        if matches!(decl.property_type, Type::Image) {
            continue;
        }
        if property_rust_type(&decl.property_type).is_none() {
            ctx.errors.push(format!(
                "slint-sc: property `{name}` has unsupported type `{:?}` (supported: bool, \
                 int, float, length, color, brush, image)",
                decl.property_type
            ));
            continue;
        }
        let binding_expr = root.bindings.get(name).and_then(|b| {
            let b = b.borrow();
            if !b.has_binding() {
                return None;
            }
            if !b.two_way_bindings.is_empty() {
                ctx.errors.push(format!(
                    "slint-sc: property `{name}` has a two-way binding, which is unsupported"
                ));
                return None;
            }
            if b.animation.is_some() {
                ctx.errors.push(format!(
                    "slint-sc: property `{name}` has an animation, which is unsupported"
                ));
                return None;
            }
            Some(b.expression.clone())
        });
        let default = binding_expr.map(|expr| emit_expression(&expr, ctx));
        out.push(RootProperty {
            name: name.clone(),
            is_public: decl.expose_in_public_api,
            ty: decl.property_type.clone(),
            default,
        });
    }
    out
}

/// Walks the element tree depth-first, threading an absolute-origin
/// accumulator through so that a nested `Rectangle { x: 6px }` inside a
/// parent `Rectangle { x: 4px }` ends up drawn at `x = 10`.
/// The root `Window` is always the first entry and uses `(0, 0)` as its
/// origin; its own `x`/`y` are not inherited by children.
fn walk_items(
    root: &ElementRc,
    parent_x: &TokenStream,
    parent_y: &TokenStream,
    ctx: &mut Ctx,
    out: &mut Vec<DrawItem>,
) {
    fn classify(element: &Element) -> Option<ItemKind> {
        let class_name = match &element.base_type {
            ElementType::Native(n) => n.class_name.clone(),
            ElementType::Builtin(b) => b.native_class.class_name.clone(),
            _ => return None,
        };
        // `resolve_native_classes` narrows Rectangle to the minimal variant
        // that still carries every used property.  Only the variants
        // without borders or gradients are supported here.
        match class_name.as_str() {
            "Empty" | "Rectangle" => Some(ItemKind::Rectangle),
            "BasicBorderRectangle" | "BorderRectangle" => Some(ItemKind::Rectangle),
            "ImageItem" | "ClippedImage" => Some(ItemKind::Image),
            "WindowItem" => Some(ItemKind::Window),
            _ => None,
        }
    }

    let element = root.borrow();
    let kind = classify(&element);
    let (abs_x, abs_y) = match kind {
        // The Window is the backdrop and fills the whole buffer; its own
        // x/y are meaningless, and children inherit `(0, 0)`.
        Some(ItemKind::Window) => (quote!(0i32), quote!(0i32)),
        Some(_) => {
            let el_x = emit_geometry_read(root, GeoKind::X);
            let el_y = emit_geometry_read(root, GeoKind::Y);
            (quote!((#parent_x + #el_x)), quote!((#parent_y + #el_y)))
        }
        None => {
            let tn = match &element.base_type {
                ElementType::Native(n) => n.class_name.clone(),
                ElementType::Builtin(b) => b.native_class.class_name.clone(),
                ElementType::Component(_) => SmolStr::new_static("(component)"),
                _ => SmolStr::new_static("(unknown)"),
            };
            ctx.errors.push(format!(
                "slint-sc: element of type `{tn}` is not supported. Only Window, Rectangle and \
                 Image may be used."
            ));
            return;
        }
    };

    out.push(DrawItem {
        kind: kind.unwrap(),
        element: root.clone(),
        abs_x: abs_x.clone(),
        abs_y: abs_y.clone(),
    });

    let children: Vec<ElementRc> = element.children.clone();
    drop(element);
    for child in &children {
        walk_items(child, &abs_x, &abs_y, ctx, out);
    }
}

fn emit_draw(item: &DrawItem, ctx: &mut Ctx) -> TokenStream {
    let element = &item.element;
    let width = emit_geometry_read(element, GeoKind::Width);
    let height = emit_geometry_read(element, GeoKind::Height);
    let abs_x = &item.abs_x;
    let abs_y = &item.abs_y;

    match &item.kind {
        ItemKind::Window => {
            let bg = get_element_binding(element, "background")
                .map(|expr| emit_expression(&expr, ctx))
                .unwrap_or_else(|| quote!(sp::Color::from_argb_encoded(0)));
            let width_expr = if element.borrow().bindings.contains_key("width") {
                width.clone()
            } else {
                quote!(buffer.line_slice(0).len() as i32)
            };
            let height_expr = if element.borrow().bindings.contains_key("height") {
                height.clone()
            } else {
                quote!(buffer.num_lines() as i32)
            };
            quote! {
                {
                    let __bg = #bg;
                    if __bg.alpha() != 0 {
                        sp::private_unstable_api::fill_rectangle(
                            buffer, 0, 0, #width_expr, #height_expr, __bg);
                    }
                }
            }
        }
        ItemKind::Rectangle => {
            reject_unsupported_props(element, &["x", "y", "width", "height", "background"], ctx);
            let bg = get_element_binding(element, "background")
                .map(|expr| emit_expression(&expr, ctx))
                .unwrap_or_else(|| quote!(sp::Color::from_argb_encoded(0)));
            quote! {
                sp::private_unstable_api::fill_rectangle(
                    buffer, #abs_x, #abs_y, #width, #height, #bg);
            }
        }
        ItemKind::Image => {
            reject_unsupported_props(element, &["x", "y", "width", "height", "source"], ctx);
            let source_expr = match get_element_binding(element, "source") {
                Some(expr) => expr,
                None => {
                    ctx.errors.push("slint-sc: Image is missing the `source` property".into());
                    return TokenStream::new();
                }
            };
            let Some(resource_id) = resolve_static_image(&source_expr) else {
                ctx.errors.push(
                    "slint-sc: Image source must resolve at compile time to an @image-url(...), \
                     either directly or through a `property <image>` with an @image-url initialiser"
                        .into(),
                );
                return TokenStream::new();
            };
            let sym = texture_symbol(resource_id);
            quote! {
                sp::private_unstable_api::draw_static_texture(buffer, #abs_x, #abs_y, &#sym);
            }
        }
    }
}

/// Follows a chain of property references until it lands on an
/// `@image-url(...)` literal and returns its texture resource id.
/// This is what lets `Image { source: my_image_property; }` work when
/// `my_image_property` was declared with `property <image>: @image-url(...)`.
fn resolve_static_image(expr: &Expression) -> Option<usize> {
    match expr {
        Expression::ImageReference {
            resource_ref: ImageReference::EmbeddedTexture { resource_id },
            ..
        } => Some(*resource_id),
        Expression::PropertyReference(nr) => {
            let elem = nr.element();
            let binding = elem.borrow().bindings.get(nr.name()).map(|b| b.borrow().expression.clone());
            resolve_static_image(&binding?)
        }
        _ => None,
    }
}

#[derive(Copy, Clone)]
enum GeoKind {
    X,
    Y,
    Width,
    Height,
}

/// Emits the given geometry coordinate as an `i32` expression, reading
/// from the materialised property on the root component that
/// `geometry_props` points at.  The stored value is already in physical
/// pixels (the scale factor was applied at binding-init time in
/// [`emit_number_literal`]).
fn emit_geometry_read(element: &ElementRc, kind: GeoKind) -> TokenStream {
    let borrow = element.borrow();
    let Some(geom) = borrow.geometry_props.as_ref() else {
        return quote!(0i32);
    };
    let nr = match kind {
        GeoKind::X => &geom.x,
        GeoKind::Y => &geom.y,
        GeoKind::Width => &geom.width,
        GeoKind::Height => &geom.height,
    };
    let n = ident(nr.name());
    quote!((_self.#n.get() as i32))
}

fn get_element_binding(element: &ElementRc, name: &str) -> Option<Expression> {
    let element = element.borrow();
    let binding = element.bindings.get(name)?;
    let b = binding.borrow();
    if !b.has_binding() || !b.two_way_bindings.is_empty() {
        return None;
    }
    Some(b.expression.clone())
}

fn reject_unsupported_props(element: &ElementRc, allowed: &[&str], ctx: &mut Ctx) {
    let element = element.borrow();
    for name in element.bindings.keys() {
        if !allowed.contains(&name.as_str()) {
            ctx.errors.push(format!(
                "slint-sc: property `{name}` on `{}` is not supported (allowed: {})",
                match &element.base_type {
                    ElementType::Native(n) => n.class_name.as_str(),
                    ElementType::Builtin(b) => b.native_class.class_name.as_str(),
                    _ => "?",
                },
                allowed.join(", ")
            ));
        }
    }
}

/// Lowers a small, safe subset of the `Expression` tree to a Rust
/// `TokenStream`.  The expression is assumed to be evaluated inside a method
/// that has `_self: &Self` in scope so that property references can be
/// resolved via `_self.<name>.get()`.
fn emit_expression(expr: &Expression, ctx: &mut Ctx) -> TokenStream {
    match expr {
        Expression::NumberLiteral(value, unit) => emit_number_literal(*value, *unit, ctx),
        Expression::BoolLiteral(b) => quote!(#b),
        Expression::PropertyReference(nr) => {
            let n = ident(nr.name());
            quote!(_self.#n.get())
        }
        Expression::Cast { from, to } => emit_cast(from, to, ctx),
        Expression::BinaryExpression { lhs, rhs, op } => {
            let l = emit_expression(lhs, ctx);
            let r = emit_expression(rhs, ctx);
            let op_tok = match op {
                '+' => quote!(+),
                '-' => quote!(-),
                '*' => quote!(*),
                '/' => quote!(/),
                _ => {
                    ctx.errors.push(format!(
                        "slint-sc: binary operator `{op}` is not supported in expressions"
                    ));
                    return quote!(Default::default());
                }
            };
            quote!(((#l) #op_tok (#r)))
        }
        Expression::UnaryOp { sub, op } => {
            let s = emit_expression(sub, ctx);
            match op {
                '-' => quote!(- (#s)),
                '+' => s,
                _ => {
                    ctx.errors.push(format!(
                        "slint-sc: unary operator `{op}` is not supported in expressions"
                    ));
                    quote!(Default::default())
                }
            }
        }
        Expression::ImageReference { resource_ref, .. } => match resource_ref {
            ImageReference::EmbeddedTexture { resource_id } => {
                let sym = texture_symbol(*resource_id);
                quote!(&#sym)
            }
            _ => {
                ctx.errors.push(
                    "slint-sc: Image source must be an @image-url(...) resolved at compile time"
                        .into(),
                );
                quote!(Default::default())
            }
        },
        _ => {
            ctx.errors.push(format!("slint-sc: unsupported expression `{expr:?}`"));
            quote!(Default::default())
        }
    }
}

fn emit_number_literal(value: f64, unit: Unit, ctx: &Ctx) -> TokenStream {
    match unit {
        // Color literals: NumberLiteral holds a 0xAARRGGBB-encoded u32 cast
        // to Color downstream.
        Unit::None => {
            let v = value;
            quote!((#v as f32))
        }
        Unit::Px => {
            // Slint SC addresses the framebuffer in physical pixels, so
            // logical-pixel literals (`px`) are pre-multiplied by the
            // compile-time scale factor here.  There is no runtime
            // conversion step downstream.
            let v = value * ctx.scale_factor as f64;
            quote!((#v as f32))
        }
        Unit::Phx => {
            // Already in physical pixels — emit as-is.
            let v = value;
            quote!((#v as f32))
        }
        _ => {
            // Other units (durations, angles, percent) are not used by the
            // supported subset of elements.  Emit a plain number and let the
            // rustc type checker reject it if it escapes.
            let v = value;
            quote!((#v as f32))
        }
    }
}

fn emit_cast(from: &Expression, to: &Type, ctx: &mut Ctx) -> TokenStream {
    // Color literals come through as `Cast { from: NumberLiteral(argb, None), to: Color }`.
    if matches!(to, Type::Color)
        && let Expression::NumberLiteral(v, _) = from
    {
        let encoded = *v as u32;
        return quote!(sp::Color::from_argb_encoded(#encoded));
    }
    // Brush cast from a Color expression: drop the cast (brushes in SC are
    // always solid colors).
    if matches!(to, Type::Brush) && matches!(from.ty(), Type::Color) {
        return emit_expression(from, ctx);
    }
    // Cast from Color to Brush via a fresh color expression: same as above.
    if matches!(to, Type::Brush) {
        let inner = emit_expression(from, ctx);
        return inner;
    }
    // LogicalLength <-> Float etc.: emit the inner expression as-is since we
    // already erase the distinction.
    if matches!(to, Type::LogicalLength | Type::PhysicalLength | Type::Float32 | Type::Int32) {
        let inner = emit_expression(from, ctx);
        return match to {
            Type::Int32 => quote!(((#inner) as i32)),
            _ => quote!(((#inner) as f32)),
        };
    }
    ctx.errors.push(format!("slint-sc: unsupported cast to `{to:?}`"));
    quote!(Default::default())
}
