// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

TestCase := Rectangle {
    width: 100phx;
    height: 100phx;
    property <int> value;
    callback clicked; // this callback shouldn't conflict with the other callback

    TouchArea {
        clicked => { value += 1; }
    }
}

/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
slint_testing::send_mouse_click(&instance, 5., 5.);
assert_eq(instance.get_value(), 1);
```

```rust
let instance = TestCase::new().unwrap();
slint_testing::send_mouse_click(&instance, 5., 5.);
assert_eq!(instance.get_value(), 1);

```

```js
var instance = new slint.TestCase();
instance.send_mouse_click(5., 5.);
assert.equal(instance.value, 1);
```
*/
