// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// ROTATION_THRESHOLD=45  - the border radius algorithm don't give the same result from every rotation

TestCase := Window {
    width: 64px;
    height: 64px;

    background: black;

    GridLayout {
        Rectangle { background: red; border-color: white; border-width: 1px; }
        Rectangle { background: #080c; border-radius: 8px; border-width: 5px; border-color: #d005; }
        Rectangle { background: blue; border-top-right-radius: 2px; border-bottom-left-radius: 4px; border-width: 4px; border-color: orange; }
    }
}
