// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// Skia font rendering is not consistent across platforms
//ignore:skia
// SIZE=200x100

export component TestCase inherits Window {
    width: 200px;
    height: 100px;
    background: white;
    StyledText {
        width: 100%;
        height: 100%;
        text: @markdown("Above\n\n---\n\nBelow");
        default-color: #025;
    }
}
