// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component TestCase inherits Window {
    width: 64phx;
    height: 64phx;

    text-input := TextInput {
        text: "Foo SELE CTED Bar";
        width: 64phx;
        height: 64phx;
        single-line: false;
        wrap: word-wrap;

        init => {
            text-input.set-selection-offsets(4, 13);
        }
    }
}
