# LICENSE BEGIN
# This file is part of the SixtyFPS Project -- https://sixtyfps.io
# Copyright (c) 2021 Olivier Goffart <olivier.goffart@sixtyfps.io>
# Copyright (c) 2021 Simon Hausmann <simon.hausmann@sixtyfps.io>
#
# SPDX-License-Identifier: GPL-3.0-only
# This file is also available under commercial licensing terms.
# Please contact info@sixtyfps.io for more information.
# LICENSE END

# Use cross-image once https://github.com/rust-embedded/cross/pull/591 is merged & released
#FROM rustembedded/cross:riscv64gc-unknown-linux-gnu-0.2.1
FROM ghcr.io/sixtyfpsui/cross-riscv64-base:1.0

RUN dpkg --add-architecture riscv64 && \
    apt-get update && \
    apt-get install --assume-yes libfontconfig1-dev:riscv64 libxcb1-dev:riscv64 libxcb-render0-dev:riscv64 libxcb-shape0-dev:riscv64 libxcb-xfixes0-dev:riscv64 libxkbcommon-dev:riscv64 python3

ENV PKG_CONFIG_PATH=/usr/lib/riscv64-linux-gnu/pkgconfig
