// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { CupertinoFontSettings, CupertinoPalette } from "styling.slint";
import { FocusBorder } from "components.slint";
import { LineEditBase, LineEditClearIcon, LineEditPasswordIcon } from "../common/lineedit-base.slint";

import { LineEditInterface } from "../common/std-widget-interfaces.slint";

export component LineEdit uses { LineEditInterface from base } {

    accessible-role: text-input;
    accessible-enabled: root.enabled;
    accessible-value <=> text;
    accessible-placeholder-text: placeholder-text;
    accessible-read-only: root.read-only;
    accessible-action-set-value(v) => {
        text = v;
        edited(v);
    }

    vertical-stretch: 0;
    horizontal-stretch: 1;
    min-width: max(160px, layout.min-width);
    min-height: max(22px, layout.min-height);
    forward-focus: base;

    states [
        disabled when !root.enabled: {
            base.text-color: CupertinoPalette.foreground;
            base.placeholder-color: CupertinoPalette.foreground-secondary;
            background.background: CupertinoPalette.tertiary-control-background;
        }
        focused when root.has-focus: {
            background.background: CupertinoPalette.control-background;
        }
    ]

    FocusBorder {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
        width: parent.width + 6px;
        height: parent.height + 6px;
        has-focus: root.has-focus;
    }

    background := Rectangle {
        background: CupertinoPalette.control-background;
        border-color: CupertinoPalette.border;
        border-width: 1px;
        opacity: root.enabled ? 1 : 0.5;
        layout := HorizontalLayout {
            padding-left: 7px;
            padding-right: 7px;
            spacing: 3px;

            base := LineEditBase {
                font-size: CupertinoFontSettings.body.font-size;
                font-weight: CupertinoFontSettings.body.font-weight;
                selection-background-color: CupertinoPalette.selection-background;
                selection-foreground-color: CupertinoPalette.selection-foreground;
                text-color: CupertinoPalette.foreground;
                margin: layout.padding-left + layout.padding-right;
                placeholder-color: CupertinoPalette.foreground-secondary;
                horizontal-stretch: 1;
            }

            if root.input-type == InputType.password: LineEditPasswordIcon {
                width: self.source.width * 1px;
                show-password-image: @image-url("_visibility.svg");
                hide-password-image: @image-url("_visibility_off.svg");
                colorize: base.text-color;
                show-password: base.input-type != InputType.password;
                show-password-changed(show) => {
                    base.input-type = show ? InputType.text : root.input-type;
                    base.focus();
                }
            }
        }
    }
}
