// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { CupertinoFontSettings, CupertinoPalette } from "styling.slint";
import { FocusBorder } from "components.slint";
import { SwitchBase } from "../common/switch-base.slint";

export component Switch inherits SwitchBase {

    private property <brush> control-background: root.checked && root.enabled ? CupertinoPalette.accent-background : CupertinoPalette.alternate-control-background;
    private property <color> text-color: CupertinoPalette.foreground;

    min-width: max(26px, i-layout.min-width);
    min-height: max(15px, i-layout.min-height);
    vertical-stretch: 0;
    horizontal-stretch: 0;
    states [
        disabled when !root.enabled : {
            root.opacity: 0.5;
        }
        pressed when root.pressed : {
            root.control-background: root.checked ? CupertinoPalette.secondary-accent-background : CupertinoPalette.secondary-control-background;
        }
        selected when root.checked : {
            i-rail.background: CupertinoPalette.accent-background;
        }
    ]

    i-layout := HorizontalLayout {
        spacing: 12px;

        VerticalLayout {
            alignment: center;

           Rectangle {
                width: 26px;
                height: 15px;
                border-radius: 8px;

                i-rail := Rectangle {
                    border-radius: parent.border-radius;
                    background: root.control-background;
                    border-width: 0.5px;
                    border-color: CupertinoPalette.border;
                    clip: true;

                    Rectangle {
                        border-width: 1px;
                        border-color: @radial-gradient(circle, #00000026, #00000000);
                        border-radius: parent.border-radius;
                    }

                    animate background, border-color { duration: 150ms; easing: linear; }
                }

                i-thumb := Rectangle {
                    x: root.checked ? parent.width - self.width - 1px : 2px;
                    y: (parent.height - self.height) / 2;
                    height: parent.height - 2px;
                    width: self.height;
                    border-radius: self.height / 2;
                    background: CupertinoPalette.control-background-thumb;
                    drop-shadow-blur: 0.5px;
                    drop-shadow-offset-y: 0.25px;
                    drop-shadow-color: #0000001F;

                    animate background { duration: 150ms; easing: linear; }
                }

                // focus border
                if (root.has-visible-focus && root.enabled) : FocusBorder {
                    border-radius: i-rail.border-radius;
                }
            }
        }

        if (root.text != "") : Text {
            text: root.text;
            color: root.text-color;
            vertical-alignment: center;
            horizontal-alignment: left;
            accessible-role: none;
        }
    }

}
