// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT
import { Palette, Measurements, Animation } from "../common.slint";
import { FancySlider } from "general/fancySlider.slint";
import { HaText } from "general/haText.slint";
import { Control } from "control.slint";

export component Overhead inherits Control {
    show-label: false;
    full-screen: false;
    tile-shadow-blur: 0px;
    control-background: @image-url("../images/overhead-frame.png", nine-slice(50));
    property <float> scaler: Math.min(1.0, root.height / 120px);

    in property <length> tilePadding: (root.height > Measurements.small-height-tile) ? 18px : 9px;
    tile := Rectangle {
        width: 100%;
        height: 100%;

        property <bool> on: true;

        TouchArea {
            clicked => {
                tile.on = !tile.on;
            }
        }

        VerticalLayout {
            alignment: space-between;
            padding: tilePadding;
            width: 100%;
            height: 100%;
            HaText {
                text: root.name;
                font-size: 15pt * scaler;
                font-weight: 400;
                color: Palette.overhead-foreground;
            }

            FancySlider {
                width: (root.height < Measurements.medium-height-tile) ? root.width - 0 - 18px : root.width * 0.8;
                value: 0.0;
                icon: @image-url("../images/brightness.svg");
                states [
                    on when !tile.on: {
                        opacity: 0;
                    }
                ]
                animate opacity {
                    duration: Animation.transition-duration;
                    easing: ease-in-out-sine;
                }
            }
        }
    }
}
