// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT
import { Palette, Measurements, Animation } from "../common.slint";
import { FancySlider } from "general/fancySlider.slint";
import { AppState } from "../appState.slint";
import { HaText } from "general/haText.slint";
import { InnerShadowRectangle } from "general/innerShadowRectangle.slint";
import { DropShadowToggle} from "general/toggle.slint";
import { Control } from "control.slint";

export component Overhead inherits Control {
    show-label: false;
    full-screen: false;
    tile-shadow-blur: 0px;
    control-background: @image-url("../images/overhead-frame.png", nine-slice(50));

    in property <length> tilePadding: (root.height > Measurements.small-height-tile) ? 18px : 9px;
    tile := Rectangle {
        width: 100%;
        height: 100%;

        TouchArea {
            clicked => {
                slider.toggle();
            }
        }

        VerticalLayout {
            alignment: space-between;
            padding: tilePadding;
            width: 100%;
            height: 100%;
            HorizontalLayout {
                spacing: 5px;
                alignment: space-between;
                VerticalLayout {
                    alignment: start;
                    HaText {
                        text: root.name;
                        font-size: 10pt;
                        font-weight: 400;
                        color: Palette.overhead-foreground;
                    }
                }
            }

            slider := FancySlider {
                width: (root.height < Measurements.medium-height-tile) ? root.width - 0 - 18px : root.width * 0.8;
                value: 0.0;
                icon: @image-url("../images/brightness.svg");
            }
        }
    }
}
