// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT
import { Palette, Style } from "../common.slint";
import { Info } from "info.slint";
import { HaText } from "./general/haText.slint";
import { Api, WeatherData, WeatherCondition } from "../api.slint";
import { AppState } from "../appState.slint";

export component Day inherits Rectangle {
    property <length> default-width: AppState.border-radius * 2;
    in property <length> special-height;
    width: default-width;
    in property <WeatherData> weather-data;
    in property <bool> highlight: false;

    border-radius: AppState.border-radius;

    if AppState.graphics-accelerator-available : Rectangle {
        Rectangle {
            border-radius: root.border-radius;
            background: @linear-gradient(1200deg, #191d44, #241433);
        }
        Rectangle {
            border-radius: root.border-radius;
            background: @linear-gradient(180deg, white.transparentize(85%) 0%, white.transparentize(93%) 60%, white.transparentize(90%) 92%, #ffffff.transparentize(75%) 100%);
        }
        Rectangle {
            border-radius: root.border-radius;
            border-width: 1px;
            border-color: Palette.glass-border;
        }
    }


    if !AppState.graphics-accelerator-available : Image {
        x: -14px;
        y: -12px;
        width: parent.width + 34px;
        height: parent.height + 32px;
        source: @image-url("../images/control-frame.png", nine-slice(40));
    }

    VerticalLayout {
        alignment: center;
        width: default-width;
        spacing: 10px;
        HaText {
            text: weather-data.day;
            horizontal-alignment: center;
            color: Palette.info-foreground;
            font-size: Style.H4-font-size;
        }

        property <length> icon-size: 40px;

        pure function weather-icon-source() -> image {
            if weather-data.condition == WeatherCondition.sunny {
                return @image-url("../images/weather/sunny.png");
            }
            if weather-data.condition == WeatherCondition.rainy {
                return @image-url("../images/weather/rainy.png");
            }
            if weather-data.condition == WeatherCondition.cloudy {
                return @image-url("../images/weather/cloudy.png");
            }
            if weather-data.condition == WeatherCondition.sunny-cloudy {
                return @image-url("../images/weather/sunny-cloudy.png");
            }
            if weather-data.condition == WeatherCondition.sunny-rainy {
                return @image-url("../images/weather/sunny-rainy.png");
            }
            // default
            return @image-url("../images/weather/sunny.png");
        }

        Rectangle {
            height: 38px;
            Image {
                width: AppState.graphics-accelerator-available ? self.source.width * 1px : self.source.width * 1px;
                source: weather-icon-source();
            }
        }

        HorizontalLayout {
            alignment: center;
            HaText {
                text: weather-data.temperature;
                horizontal-alignment: center;
                color: Palette.info-foreground;
                font-size: Style.H3-font-size;
                vertical-alignment: center;
            }

            Text {
                text: "°C";
                color: white;
                font-size: 8px;
                vertical-alignment: center;
            }
        }
    }
}

export component WeatherInfo {
    in property <int> index;
    property <length> margin: 16px;
    in property <string> name;
    in property <string> id;
    in property <bool> full-screen: false;
    property <length> special-height: Math.min(180px, root.height);

    Rectangle {
        y: 1px;
        width: 220px;
        height: parent.height - 2px;

        HorizontalLayout {
            alignment: space-between;
            spacing: 6px;
            width: 280px;
            Day {
                weather-data: Api.weather-forecast[0];
                highlight: true;
                special-height: root.special-height;
            }

            Day {
                weather-data: Api.weather-forecast[1];
                special-height: root.special-height;
            }

            Day {
                weather-data: Api.weather-forecast[2];
                special-height: root.special-height;
            }

            Day {
                weather-data: Api.weather-forecast[3];
                special-height: root.special-height;
            }

            Day {
                weather-data: Api.weather-forecast[4];
                special-height: root.special-height;
            }
        }
    }
}
