// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT
import { Palette,Measurements,Colors, Style } from "../common.slint";
import { Info } from "info.slint";
import { HaText } from "./general/haText.slint";
import { Api, WeatherData, WeatherCondition } from "../api.slint";

export component Day inherits Rectangle {

    in property <WeatherData> weather-data;
    in property <bool> highlight: false;

    if highlight: Rectangle {
        border-bottom-left-radius: Measurements.tile-radius;
        border-top-left-radius: Measurements.tile-radius;
        background: Palette.info-alternate-background;
    }
    VerticalLayout {
        alignment: center;
        HaText {
            text: weather-data.day;
            horizontal-alignment: center;
            color: Palette.info-foreground;
            font-size: Style.icon-title-font-size;
        }

        if weather-data.condition == WeatherCondition.sunny: Image {
            height: 25px;
            source: @image-url("../images/sunny.png");
        }
        if weather-data.condition == WeatherCondition.cloudy: Image {
            height: 25px;
            source: @image-url("../images/cloudy.png");
        }
        if weather-data.condition == WeatherCondition.rainy: Image {
            height: 25px;
            source: @image-url("../images/rainy.png");
        }

        HaText {
            text: weather-data.temperature + "°C";
            horizontal-alignment: center;
            color: Palette.info-alternate-foreground;
            font-size: Style.icon-title-font-size;
        }
    }
}

export component WeatherInfo inherits Info {
    in property <int> index;
    Rectangle {
        y: 1px;
        height: parent.height - 2px;
        HorizontalLayout {
            Day {
                weather-data: Api.weather-forecast[0];
                highlight: true;
            }
            Day {
                weather-data: Api.weather-forecast[1];
            }

            Day {
                weather-data: Api.weather-forecast[2];
            }

            Day {
                weather-data: Api.weather-forecast[3];
            }

            Day {
                weather-data: Api.weather-forecast[4];
            }
        }
    }

}
