// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

//! This file contains a generic implementation of the MenuBar and ContextMenu

import { Palette, MenuBarItem, MenuBar, MenuFrame, MenuItem } from "std-widgets-impl.slint";

export component PopupMenuImpl inherits Window {
    in property <[MenuEntry]> entries: [];

    property <int> current: -1;
    property <length> px: 1rem / 14;

    callback sub-menu(menu-entry: MenuEntry) -> [MenuEntry];
    callback activated(menu-entry: MenuEntry);
    callback close();

    forward-focus: focus-scope;
    background: transparent;

    focus-scope := FocusScope {
        frame := MenuFrame {
            for entry[index] in entries: MenuItem {
                entry: entry;
                is-current: current == index;

                set-current => {
                    focus-scope.focus();
                    root.current = index;
                    open-sub-menu-after-timeout.running = true;
                }

                clear-current => {
                    root.current = -1;
                }

                activate(entry, y) => {
                    root.activate(entry, y);
                }
            }
        }

        open-sub-menu-after-timeout := Timer {
            interval: 500ms;
            running: false;

            triggered => {
                self.running = false;

                if current >= 0 {
                    if entries[current].has-sub-menu {
                        activate(entries[current], y-pos(current));
                    } else {
                        sub-menu.close();
                    }
                }
            }
        }

        function y-pos(idx: int) -> length {
            frame.padding + idx * (frame.height - 2 * frame.padding) / entries.length
        }

        key-pressed(event) => {
            open-sub-menu-after-timeout.running = false;

            if event.text == Key.UpArrow {
                if current >= 1 {
                    current -= 1;
                } else {
                    current = entries.length - 1;
                }
                return accept;
            } else if event.text == Key.DownArrow {
                if current < entries.length - 1 {
                    current += 1;
                } else {
                    current = 0;
                }
                return accept;
            } else if event.text == Key.Return {
                if current >= 0 && current < entries.length {
                    activate(entries[current], y-pos(current));
                }
                return accept;
            } else if event.text == Key.RightArrow {
                if current >= 0 && current < entries.length && entries[current].has-sub-menu {
                    activate(entries[current], y-pos(current));
                }
                return accept;
            } else if event.text == Key.LeftArrow {
                // TODO: should close only if this menu is a sub menu
                root.close();
            }

            reject
        }
    }

    sub-menu := ContextMenuInternal {
        x: 0; y: 0; width: 0; height: 0;

        sub-menu(entry) => { root.sub-menu(entry); }

        activated(entry) => {
            root.activated(entry);
            root.close();
        }
    }

    function activate(entry : MenuEntry, y: length) {
        open-sub-menu-after-timeout.running = false;
        if entry.has-sub-menu {
            sub-menu.entries = root.sub-menu(entry);
            sub-menu.show({
                x: root.width,
                y: y - sub-menu.absolute-position.y,
            });
        } else {
            activated(entry);
            close();
        }
    }
}


export component MenuBarImpl {
    callback activated(menu-entry: MenuEntry);
    callback sub-menu(menu-entry: MenuEntry) -> [MenuEntry];

    property <[MenuEntry]> entries;
    property <length> px: 1rem / 14;

    preferred-width: 100%;
    height: base.min-height;

    base := MenuBar {
        width: 100%;

        for entry in entries: e := MenuBarItem {
            entry: entry;
            
            clicked => {
                context-menu.entries = root.sub-menu(entry);
                context-menu.show({ x: e.x, y: root.height });
            }
        }
    }

    context-menu := ContextMenuInternal {
        activated(entry) => { root.activated(entry); self.close(); }
        sub-menu(entry) => { root.sub-menu(entry); }
    }
}

