// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { StyleMetrics, Button } from "std-widgets-impl.slint";

import { StandardButtonInterface } from "./std-widget-interfaces.slint";

export component StandardButton implements StandardButtonInterface {
    enabled <=> base.enabled;
    primary <=> base.primary;
    has-focus <=> base.has-focus;
    pressed <=> base.pressed;

    forward-focus: base;

    HorizontalLayout {
        base := Button {
            text:
                root.kind == StandardButtonKind.ok ? @tr("OK") :
                root.kind == StandardButtonKind.cancel ? @tr("Cancel") :
                root.kind == StandardButtonKind.apply ? @tr("Apply") :
                root.kind == StandardButtonKind.close ? @tr("Close") :
                root.kind == StandardButtonKind.reset ? @tr("Reset") :
                root.kind == StandardButtonKind.help ? @tr("Help") :
                root.kind == StandardButtonKind.yes ? @tr("Yes") :
                root.kind == StandardButtonKind.no ? @tr("No") :
                root.kind == StandardButtonKind.abort ? @tr("Abort") :
                root.kind == StandardButtonKind.retry ? @tr("Retry") :
                root.kind == StandardButtonKind.ignore ? @tr("Ignore") : "";

            clicked() => root.clicked();
        }
    }
}
