// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { StyleMetrics, Button } from "std-widgets-impl.slint";

export StandardButton := Button {
    in property <StandardButtonKind> kind;
    text:
        kind == StandardButtonKind.ok ? "OK" :
        kind == StandardButtonKind.cancel ? "Cancel" :
        kind == StandardButtonKind.apply ? "Apply" :
        kind == StandardButtonKind.close ? "Close" :
        kind == StandardButtonKind.reset ? "Reset" :
        kind == StandardButtonKind.help ? "Help" :
        kind == StandardButtonKind.yes ? "Yes" :
        kind == StandardButtonKind.no ? "No" :
        kind == StandardButtonKind.abort ? "Abort" :
        kind == StandardButtonKind.retry ? "Retry" :
        kind == StandardButtonKind.ignore ? "Ignore" : "";
}
