// Copyright © 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nicholas Turner <nicholas.turner@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component TestCase inherits Window {
    in-out property <int> var1: 20;
    in-out property <int> var2: 50;
    in-out property <int> var3: 70;

    in-out property <string> cond1: "hello world";
    in-out property <string> cond2: "goodbye world";

    in-out property <string> output: "";

    match cond1 {
        "hello" + " world": TouchArea {
            Text {
                text: var1;
            }

            x: 0px;
            y: 100px;
            width: 100px;
            height: 100px;
            property <int> xx: var1;
            clicked => {
                var1 += self.xx;
            }
        }

        "hello" + "world": TouchArea {
            Text {
                text: var2;
            }

            x: 150px;
            y: 100px;
            width: 100px;
            height: 100px;
            property <int> xx: var2;
            clicked => {
                var2 += self.xx;
            }
        }

        "hello  world": TouchArea {
            Text {
                text: var3;
            }

            x: 300px;
            y: 100px;
            width: 100px;
            height: 100px;
            property <int> xx: var3;
            clicked => {
                var3 += self.xx;
            }
        }
    }
    Rectangle {
        x: 450px;
        y: 100px;
        match cond2 {
            cond1: TouchArea {
                clicked => {
                    output = "a";
                }
            }

            "goodbye " + " world": TouchArea {
                clicked => {
                    output = "b";
                }
            }

            "goodbye world ": TouchArea {
                clicked => {
                    output = "c";
                }
            }

            else: TouchArea {
                clicked => {
                    output = "d";
                }
            }
        }
    }

    in-out property <bool> test: cond1 == "hello world" && cond2 == "goodbye world" && output == "";
}

/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;

assert_eq(instance.get_output(), "");
assert_eq(instance.get_var1(), 20);
assert_eq(instance.get_var2(), 50);
assert_eq(instance.get_var3(), 70);

slint_testing::send_mouse_click(&instance, 0., 100.);
slint_testing::send_mouse_click(&instance, 150., 100.);
slint_testing::send_mouse_click(&instance, 300., 100.);

assert_eq(instance.get_var1(), 40);
assert_eq(instance.get_var2(), 50);
assert_eq(instance.get_var3(), 70);

slint_testing::send_mouse_click(&instance, 450., 100.);
assert_eq(instance.get_var1(), 40);
assert_eq(instance.get_var2(), 50);
assert_eq(instance.get_var3(), 70);
assert_eq(instance.get_output(), "d");
```

```rust
let instance = TestCase::new().unwrap();

assert_eq!(instance.get_output(), "");
assert_eq!(instance.get_var1(), 20);
assert_eq!(instance.get_var2(), 50);
assert_eq!(instance.get_var3(), 70);

slint_testing::send_mouse_click(&instance, 0., 100.);
slint_testing::send_mouse_click(&instance, 150., 100.);
slint_testing::send_mouse_click(&instance, 300., 100.);

assert_eq!(instance.get_var1(), 40);
assert_eq!(instance.get_var2(), 50);
assert_eq!(instance.get_var3(), 70);

slint_testing::send_mouse_click(&instance, 450., 100.);
assert_eq!(instance.get_var1(), 40);
assert_eq!(instance.get_var2(), 50);
assert_eq!(instance.get_var3(), 70);
assert_eq!(instance.get_output(), "d");
```
*/
