// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// Bindings are only allowed on properties in the Slint SC subset, and the
// expression can only be a color literal.

export component Test inherits Window {
    background: #123456;
    Rectangle {
        width: 100px;
//             >   <error{Number literals are not supported in Slint SC}
        opacity: 1.0;
//      >     <error{The property 'opacity' is not supported in Slint SC}
//               > <^error{Number literals are not supported in Slint SC}
        //#sls.expr.forms
        background: red;
//                  > <error{Identifier references are not supported in Slint SC}
        //#sls.binding.target-must-exist
        foo: #123456;
//      > <error{Unknown property foo in Rectangle}
    }
}
