// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// The two copyright lines above end with LF; every line from here on
// ends with CRLF. Both are equivalent line terminators. The bare CR
// inside the component body is not a line terminator.
//#sls.source.line-terminators
//#sls.source.bare-cr

export component Test inherits Window {}
