# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "food-processor"
version = "1.19.0"
authors = ["Slint Developers <info@slint.dev>"]
edition.workspace = true
publish = false
license = "MIT"

[[bin]]
path = "main.rs"
name = "food-processor"

[lib]
crate-type = ["lib", "cdylib"]
path = "lib.rs"
name = "food_processor_lib"

[dependencies]
slint = { path = "../../../api/rs/slint", default-features = false, features = ["compat-1-18", "std", "backend-android-activity-06"] }

[features]
default = ["slint/default"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3", features = ["console"] }
console_error_panic_hook = "0.1.5"

[package.metadata.android.sdk]
min_sdk_version = 23
target_sdk_version = 36

[[package.metadata.android.application.activity]]
name = "android.app.NativeActivity"
orientation = "sensorLandscape"

[[package.metadata.android.application.activity.meta_data]]
name = "android.app.lib_name"

[[package.metadata.android.application.activity.intent_filter]]
actions = ["android.intent.action.VIEW", "android.intent.action.MAIN"]
categories = ["android.intent.category.LAUNCHER"]
