// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { CosmicFontSettings, CosmicPalette } from "styling.slint";
import { StateLayerBase } from "components.slint";
import { ButtonBase } from "../common/button-base.slint";

export component Button inherits ButtonBase {
    focus-on-pointer-click: true;

    in property <image> icon;
    in property <length> icon-size: 20px;
    in property <bool> primary;
    in property <bool> colorize-icon;

    private property <brush> text-color: primary ? CosmicPalette.accent-foreground : CosmicPalette.control-foreground;

    min-width: max(32px, layout.min-width);
    min-height: max(32px, layout.min-height);
    horizontal-stretch: 0;
    vertical-stretch: 0;

    states [
        disabled when !root.enabled : {
            root.opacity: 0.5;
        }
    ]

    background := Rectangle {
        border-radius: 16px;
        background: root.primary ? CosmicPalette.accent-background : CosmicPalette.control-background;

        animate background, border-color { duration: 150ms; }

        layout := HorizontalLayout {
            padding-left: 12px;
            padding-right: 12px;
            padding-top: 5px;
            padding-bottom: 5px;
            spacing: 4px;
            alignment: center;

            if (root.icon.width > 0 && root.icon.height > 0) : Image {
                y: (parent.height - self.height) / 2;
                source <=> root.icon;
                width: root.icon-size;
                min-height: root.icon-size;
                colorize: root.colorize-icon ? root.text-color : transparent;
                accessible-role: none;
            }

            if (root.text != ""): Text {
                horizontal-alignment: center;
                vertical-alignment: center;
                text: root.text;
                color: root.text-color;
                animate color { duration: 150ms; }
                accessible-role: none;
            }
        }
    }

    state-layer := StateLayerBase {
        border-radius: background.border-radius;
        has-focus: root.has-visible-focus;
        has-hover: root.has-hover;
        pressed: root.pressed;
        checked: root.checked;
        enabled: root.enabled;
    }

}
