// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { CosmicPalette, Icons } from "styling.slint";
import { StateLayerBase } from "components.slint";
import { CheckBoxBase } from "../common/checkbox-base.slint";

export component CheckBox inherits CheckBoxBase {
    focus-on-pointer-click: true;

    in property <length> font-size;
    in property <int> font-weight;

    private property <color> text-color: CosmicPalette.foreground;

    min-height: max(16px, layout.min-height);
    states [
        disabled when !root.enabled : {
           opacity: 0.5;
        }
        checked when root.checked && root.enabled : {
            background.background: CosmicPalette.accent-background;
        }
    ]

    animate text-color { duration: 200ms; }

    layout := HorizontalLayout {
        spacing: 8px;

        background := Rectangle {
            width: 16px;
            height: self.width;
            y: (parent.height - self.height) / 2;
            background: CosmicPalette.control-background;
            border-radius: 4px;

            animate background, border-color { duration: 150ms; }

            border := Rectangle {
                border-color: CosmicPalette.alternate-border;
                border-width: root.checked ? 0 : 1px;
                border-radius: parent.border-radius;
            }

            icon := Image {
                image-fit: contain;
                visible: root.checked;
                source: Icons.check-mark;
                colorize: CosmicPalette.accent-foreground;
                width: 12px;
                accessible-role: none;

                animate colorize { duration: 150ms; }
            }

            StateLayerBase {
                border-radius: background.border-radius;
                has-focus: root.has-visible-focus;
                has-hover: root.has-hover;
                pressed: root.pressed;
                checked: root.checked;
                enabled: root.enabled;
            }
        }

        if (root.text != "") : Text {
            text: root.text;
            color: root.text-color;
            font-size: root.font-size;
            font-weight: root.font-weight;
            vertical-alignment: center;
            horizontal-alignment: left;
            accessible-role: none;
        }
    }
}
