// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { CosmicPalette } from "styling.slint";
import { MenuBarItemBase, MenuBarBase, MenuFrameBase } from "../common/menu-base.slint";

export component MenuBarItem {
    in property <MenuEntry> entry <=> base.entry;
    in property <bool> is-current <=> base.is-current;
    
    callback clicked <=> base.clicked;

    min-width: base.min-width;
    min-height: base.min-height;
        
    base := MenuBarItemBase {
        padding-left: 11px;
        padding-right: 11px;
        padding-top: 4px;
        padding-bottom: 6px;
        default-foreground: CosmicPalette.foreground;
        hover-foreground: CosmicPalette.accent-foreground;
        pressed-foreground: CosmicPalette.accent-foreground;
        hover-background: CosmicPalette.accent-background;
        pressed-background: CosmicPalette.accent-background;
        font-size: 14px;
        font-weight: 300;
        border-radius: 3px;
    }
}

export component MenuBar inherits MenuBarBase {
    padding: 9px;
    spacing: 10px;
    min-layout-height: 40px;
}

export component MenuFrame inherits MenuFrameBase {
    background: CosmicPalette.background;
    border-radius: 7px;
    border-width: 1px;
    border-color: CosmicPalette.border;
    drop-shadow-color: CosmicPalette.shadow;
    drop-shadow-offset-y: 8px;
    drop-shadow-blur: 16px;
    padding: 1px;
}
