// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { CosmicPalette } from "styling.slint";
import { StateLayerBase } from "components.slint";
import { Slider as SliderControl } from "../headless/controls.slint";

export component Slider inherits SliderControl {
    handle-x: thumb.x;
    handle-y: thumb.y;
    handle-width: thumb.width;
    handle-height: thumb.height;

    min-width: root.vertical ? 20px : 0px;
    min-height: root.vertical ? 0px : 20px;
    vertical-stretch: root.vertical ? 1 : 0;
    horizontal-stretch: root.vertical ? 0 : 1;
    accessible-value-step: min(root.step, (root.maximum - root.minimum) / 100);

    states [
        disabled when !root.enabled : {
            opacity: 0.5;
        }
    ]

    rail := Rectangle {
        x: root.vertical ? (parent.width - self.width) / 2 : thumb.width / 2;
        y: root.vertical ? thumb.height / 2 : (parent.height - self.height) / 2;
        width: root.vertical ? 4px : parent.width - thumb.width;
        height: root.vertical ? parent.height - thumb.height : 4px;
        background: CosmicPalette.neutral-6-background;
        border-radius: 2px;
    }

    track := Rectangle {
        x: root.vertical ? (parent.width - self.width) / 2 : thumb.width / 2;
        y: root.vertical ? thumb.y + thumb.height / 2 : (parent.height - self.height) / 2;
        width: root.vertical ? rail.width : thumb.x;
        height: root.vertical ? parent.height - thumb.y - thumb.height : rail.height;
        background: CosmicPalette.secondary-accent-background;
        border-radius: rail.border-radius;
    }

    thumb := Rectangle {
        x: root.vertical ? (parent.width - self.width) / 2 : clamp((parent.width - self.width) * (root.value - root.minimum) / (root.maximum - root.minimum), 0, parent.width - self.width);
        y: root.vertical ? clamp((parent.height - self.height) * (root.maximum - root.value) / (root.maximum - root.minimum), 0, parent.height - self.height) : (parent.height - self.height) / 2;
        width: 20px;
        height: self.width;
        border-radius: 10px;
        background: CosmicPalette.accent-background;

        StateLayerBase {
            width: parent.width + 8px;
            height: parent.height + 8px;
            border-radius: max(self.width, self.height) / 2;
            enabled: root.enabled;
            focus-border-margin: 0px;
            pressed: root.handle-pressed;
            has-hover: root.has-hover;
            has-focus: root.has-focus;
        }
    }
}
