// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { CosmicFontSettings, CosmicPalette } from "styling.slint";
import { ScrollView } from "scrollview.slint";
import { TextEditBase } from "../common/textedit-base.slint";

import { TextEditInterface } from "../common/std-widget-interfaces.slint";

export component TextEdit uses { TextEditInterface from base } {
    accessible-role: AccessibleRole.text-input;
    accessible-enabled: root.enabled;
    accessible-value <=> text;
    accessible-placeholder-text: placeholder-text;
    accessible-read-only: root.read-only;

    forward-focus: base;
    horizontal-stretch: 1;
    vertical-stretch: 1;

    states [
        disabled when !root.enabled: {
            root.opacity: 0.5;
        }
    ]

    base := TextEditBase {
        width: 100%;
        height: 100%;
        border-radius: 8px;
        background: CosmicPalette.control-background;
        border-width: 1px;
        border-color: CosmicPalette.control-divider;
        scroll-view-padding: 12px;
        foreground: CosmicPalette.foreground;
        font-size: CosmicFontSettings.body.font-size;
        font-weight: CosmicFontSettings.body.font-weight;
        selection-background-color: CosmicPalette.selection-background;
        selection-foreground-color: CosmicPalette.selection-foreground;
        placeholder-color: CosmicPalette.placeholder-foreground;
        if root.has-focus && root.enabled: Rectangle {
            width: parent.width + 2px;
            height: parent.height + 2px;
            border-radius: parent.border-radius + 2px;
            border-color: CosmicPalette.state-focus;
            border-width: 1px;
        }
    }
}
