# Generated by slint.codegen from counter.slint
from __future__ import annotations

import importlib.resources as _resources
import os
import types
from contextlib import nullcontext as _nullcontext
from pathlib import Path
from typing import Any

import slint

__all__ = ['CounterWindow']

_MODULE_DIR = Path(__file__).parent

_SLINT_RESOURCE = 'counter.slint'

def _load() -> types.SimpleNamespace:
    """Load the compiled Slint module for this package."""
    package = __package__ or (__spec__.parent if __spec__ else None)
    if package:
        ctx = _resources.as_file(_resources.files(package).joinpath(_SLINT_RESOURCE))
    else:
        ctx = _nullcontext(Path(__file__).with_name(_SLINT_RESOURCE))
    with ctx as slint_path:
        include_paths: list[os.PathLike[Any] | Path] | None = [_MODULE_DIR]
        library_paths: dict[str, os.PathLike[Any] | Path] | None = None
        return slint.load_file(
            path=slint_path,
            quiet=True,
            style=None,
            include_paths=include_paths,
            library_paths=library_paths,
            translation_domain=None,
        )

_module = _load()

CounterWindow = _module.CounterWindow
