// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export struct OptionalInt {
    maybe_value: int,
}

export struct OptionalFloat {
    maybe_value: float,
}

export struct OptionalString {
    maybe_value: string,
}

export struct OptionalBool {
    maybe_value: bool,
}

export enum OptionalEnum {
    OptionA,
    OptionB,
    OptionC,
}



export component OptionalDemo {
    in-out property <OptionalInt> maybe_count;
    callback on_action(value: OptionalFloat) -> OptionalInt;

    public function compute(input: OptionalString) -> OptionalBool {
        return { maybe_value: true };
    }
}