// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Software-3.0

export component BackgroundColor inherits Window {
    Rectangle {
        //#sls.binding.form
        background: #123456;
    }
    Rectangle {
        background: #18f;
        Rectangle {
            background: #1188ff88;
        }
    }
}
/*
```rust
let _ = BackgroundColor::new();
```
*/
