// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Software-3.0

//#sls.file.component.body
//#sls.file.element.instantiation-form
//#sls.file.element.body
//#sls.file.element.tree
export component NestedRectangles inherits Window {
    Rectangle {
        Rectangle {
        }
    }
    Rectangle {
    }
}
/*
```rust
let _ = NestedRectangles::new();
```
*/
