// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Software-3.0

export component TestCase inherits Window {
    //#sls.ref.window.background
    background: #123456;
    //#sls.ref.rectangle.empty
    Rectangle {
        x: 4px;
        y: 4px;
        width: 10px;
        height: 10px;
    }
    //#sls.paint.model
    //#sls.ref.rectangle.background
    Rectangle {
        //#sls.expr.length.form
        //#sls.expr.length.type
        //#sls.type.length
        x: 8px;
        y: 16px;
        width: 40px;
        height: 24px;
        //#sls.type.brush
        background: #ff8800;
    }
}

/*
```rust
let x = TestCase::new();
screenshot!(x);
```
*/
