// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Software-3.0

export component TestCase inherits Window {
    background: #f00;
}

/*
```rust
let x = TestCase::new();
screenshot!(x);
//#sls.gen.render-rgb8
let mut frame_buffer = [0u8; 64 * 64 * 3];
x.render_rgb8(64, 64, &mut frame_buffer)?;
assert!(frame_buffer.chunks(3).all(|pixel| pixel == [0xff, 0x00, 0x00]));
//#sls.gen.render-error
assert_eq!(x.render_rgb8(64, 64, &mut [0u8; 8]), Err(slint_sc::RenderError::InvalidFrameBufferSize));
```
*/
