// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { ComponentsView } from "components_view.slint";
import { Palette } from "std-widgets.slint";
import { MainWindowAdapter } from "../main_window_adapter.slint";
import { FilledIcons, OutlinedIcons } from "../icons.slint";
import {
    MaterialText,
    Typography,
    IconButton,
    MaterialPalette,
    Animations,
    NavigationRail,
    NavigationItem,
    NavigationBar,
    SmallAppBar

} from "../../../../material.slint";

export enum Views {
    components
}

export component MainView {
    property <Views> current_view: Views.components;
    property <[NavigationItem]> navigation_items: [
        {
            text: "Components",
            icon: OutlinedIcons.dashboard,
            icon_selected: FilledIcons.dashboard
        }
    ];

    VerticalLayout {
        SmallAppBar {
            title: "Material 3";
            trailing_icons: [{ icon: Palette.color_scheme == ColorScheme.light ? OutlinedIcons.dark_mode : OutlinedIcons.light_mode, enabled: true }];
            container_background: MainWindowAdapter.container_background;

            traling_clicked(index) => {
                if Palette.color_scheme == ColorScheme.light {
                    Palette.color_scheme = ColorScheme.dark;
                    return;
                }

                Palette.color_scheme = ColorScheme.light;
            }
        }

        Rectangle {
            background: MaterialPalette.background;

            if !MainWindowAdapter.break_layout : HorizontalLayout {
                 NavigationRail {
                     items: root.navigation_items;
                 }


                if root.current_view == Views.components : ComponentsView {
                    horizontal_stretch: 1;
                }
            }

            if MainWindowAdapter.break_layout : VerticalLayout {
                if root.current_view == Views.components : ComponentsView {
                    horizontal_stretch: 1;
                }

                NavigationBar {
                    items: root.navigation_items;
                }
            }
        }
    }
}
