// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component App inherits Window{
    background: blue;
    //          ^error{Function must be called}
    function blue()->color {
       blue
//     ^error{Function must be called}
    }



    in property <int> abc: get_abc1();
    function get_abc1() -> int { return get_abc2(); }
//  ^error{The binding for the property 'get-abc1' is part of a binding loop}
    function get_abc2() -> int { return get_abc1(); }
//  ^error{The binding for the property 'get-abc2' is part of a binding loop}

}

