// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

export global Images {
    in property <image> arrow-left: @image-url("assets/arrow-left.png");
    in property <image> arrow-right: @image-url("assets/arrow-right.png");
    in property <image> sunny: @image-url("assets/sunny.svg");
    in property <image> cloud: @image-url("assets/cloud.svg");
    in property <image> cloudy: @image-url("assets/cloudy.svg");
}