// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { Theme } from "theme.slint";
import { Navigation, MenuButton, Menu, Value } from "widgets/widgets.slint";
import { Balance, BalanceAdapter, Overview, OverviewAdapter, Usage, UsageAdapter, Weather, WeatherAdapter } from "pages/pages.slint";
export { OverviewAdapter, UsageAdapter, Value, WeatherAdapter }

export component MainWindow inherits Window {
    title: "EnergyMNG Demo";
    min_width: 320px;
    min_height: 240px;
    background: Theme.palette.pure-black;

    i-navigation := Navigation { 
        page-count: 4;
        current-index: 2;

        Overview {
            index: 0;
            current-index: i-navigation.current-index;
        }
        Usage { 
            index: 1;
            current-index: i-navigation.current-index;
        }
        Balance {
            index: 2;
            current-index: i-navigation.current-index;
        }
        Weather {
            index: 3; 
            current-index: i-navigation.current-index;
        }

        pagination-clicked => {  
            i-menu.show-button();
        }

        clicked => {
            // if the navigation is clicked and the arrow displayed a open menu button should be hide.
            i-menu.hide-button();
        }
    }

    i-menu := Menu {
        x: (parent.width - self.width) / 2;
        start-y: parent.height - 25px;
        end-y: 9px;
        width: parent.width - 8px;
        height: parent.height - 14px;  
    }
}