// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { Header, HeaderAdapter } from "blocks/blocks.slint";
import { Images } from "images.slint";
import { Theme } from "theme.slint";
import { Menu, PageScrollView, PageContainer } from "widgets/widgets.slint";
import { MenuPage } from "pages/pages.slint";
import { Balance, Overview, Usage, UsageAdapter, Weather } from "pages/pages.slint";
 
export component MidMain {
    private property <int> page-count: 4;
    private property <length> item-width: i-page-scroll-view.viewport-width / page-count;
    private property <length> max-viewport-x: i-page-scroll-view.width - i-page-scroll-view.viewport-width;

    Rectangle {
        background: Theme.palette.background-gradient;

        VerticalLayout {  
            padding-bottom: 50px;
            spacing: 35px;

            Header {}
 
            i-page-scroll-view := PageScrollView {
                vertical-stretch: 1;

                PageContainer {
                    Overview {}
                }

                PageContainer {
                    Usage {}
                }

                PageContainer {
                    Balance {}
                }

                PageContainer {
                    Weather {}
                }

                animate viewport-x { duration: Theme.durations.medium;  }
            }
        }

        i-menu := Menu {
            stays-open: true;
           
            start-y: 35px;
            end-y: 75px;
            menu-width: root.width / 3;
            menu-height: root.height - 75px;  
    
            i-menu-page := MenuPage {
                page-changed(index) => {  
                    i-menu.hide();
                    i-page-scroll-view.viewport-x = min(0px, max(max-viewport-x, -(index * item-width))); 
                }
            }

            opend => {
                i-menu-page.current-index = 0;
            }
        }
    }
}