// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export global FileTreeIcons {
    out property <image> chevron-down: @image-url("../../assets/octicons/chevron-down.svg");
    out property <image> chevron-right: @image-url("../../assets/octicons/chevron-right.svg");
    out property <image> directory: @image-url("../../assets/octicons/file-directory-fill.svg");
    out property <image> directory-open: @image-url("../../assets/octicons/file-directory-open-fill.svg");
    out property <image> file-code: @image-url("../../assets/octicons/file-code.svg");
    out property <image> image: @image-url("../../assets/octicons/image.svg");
}
