// Copyright © SixtyFPS GmbH <info@slint.dev>, Copyright © 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nathan Collins <nathan.collins@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export interface Button {
    in property <bool> checkable: false;
    in-out property <bool> checked: false;
    in property <bool> enabled: true;
    out property <bool> has-focus: false;
    in property <image> icon;
    in property <length> icon-size: 0px;
    out property <bool> pressed: false;
    in property <string> text: "";
    in property <bool> primary: false;
    in property <bool> colorize-icon: false;
    callback clicked;
}
