// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

export interface RadioButton {
    in property <string> text;
    in property <string> value;
    in property <bool> enabled;
    in property <bool> read-only;
    in property <bool> checked;

    out property <bool> has-focus;
    out property <bool> has-hover;
    out property <bool> pressed;

    callback selected;
    callback focus-change(bool);

    public function select();
}

export interface RadioGroup {
    in property <string> text;
    in property <bool> enabled;
    in property <bool> read-only;
    in-out property <string> selected-value;

    callback selected(string);

    public function select(value: string);
}

export interface RadioButtonGroupMember {
    in property <string> text;
    in property <bool> enabled;
    in property <bool> group-enabled;
    in property <int> item-index;
    in property <int> group-current-index;
    in-out property <bool> checked;

    out property <bool> has-focus;
    out property <bool> has-hover;
    out property <bool> pressed;

    callback toggled;
    callback group-select;
    callback focus-change(bool);

    public function select();
}

export interface RadioGroupSelection {
    in property <bool> enabled;
    in-out property <int> current-index;
    out property <string> current-value;

    callback selected(string);

    public function select(index: int, label: string);
}
