// Copyright © SixtyFPS GmbH <info@slint.dev>, Copyright © 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nathan Collins <nathan.collins@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export interface Slider {
    in property <bool> enabled;
    out property <bool> has-focus;
    in-out property <float> value;
    in property <float> step;
    in property <float> minimum;
    in property <float> maximum;
    in property <Orientation> orientation;

    callback changed(value: float);
    callback released(value: float);
}
