import { AboutSlint , VerticalBox, Button, HorizontalBox} from "std-widgets.slint";


Launcher := Window {
    width: 480px;
    height: 272px;

    callback quit();
    background: black;
    property <int> to_launch;


    property <[{ title: string, icon: string }]> demos : [
        {title: "Printer demo", icon: "🖨"},
        {title: "Slide puzzle", icon: "🎮"},
        {title: "Memory game", icon: "▦"},
    ];

    HorizontalLayout {
        height: 60%;
        width: 100%;
        spacing: 20px;
        padding: 20px;
        for d[idx] in demos: rect := Rectangle {
            background: !touch.pressed ? #131619 : #2c2f36;
            touch := TouchArea {
                clicked => { to-launch = idx + 1; }
            }
            VerticalLayout {
                padding: 5px;
                Rectangle {
                    Text {
                        text: d.icon;
                        color: {
                            // Workaround to quit after the animation
                            if (width >= parent.width*2) {
                                quit();
                                return red;
                            };
                            #0025ff;
                        }
                        font-size: min(self.width, self.height) * 0.6;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        property <bool> activated: to-launch == idx+1;
                        width: activated ? parent.width*2 : parent.width;
                        height: activated ? parent.height*2 : parent.height;
                        x: (parent.width - width) / 2;
                        y: (parent.height - height) / 2;
                        animate width, height { duration: 500ms; easing: ease-out; }

                    }
                }

                Text {
                    text: d.title;
                    color: white;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    font-size: 18px;
                }
            }
        }


    }



    /*VerticalBox {
        width: 50%;
        alignment: start;

    }*/

    Image {
        source: @image-url("../../logo/slint-logo-simple-dark.svg");
        //width: 25%;
        //height: 50%;
        x: parent.width - width - 10px;
        y: parent.height - height - 10px;
    }

   /* AboutSlint {
        width: 50%;
        height: 50%;
        x: parent.width - width;
        y: parent.height - height;
    }*/

}
