// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { TabWidget, HorizontalBox } from "std-widgets.slint";
import { MailView } from "mail_view.slint";
import { HeaderView } from "header_view.slint";
import { DashboardView } from "dashboard_view.slint";

export global MainViewAdapter { }

export component MainView {
    in property <bool> break-layout;

    forward-focus: focus-scope;
    focus-scope := FocusScope {}

    VerticalLayout {
        HeaderView {}

        HorizontalBox {
            TabWidget {
                Tab {
                    title: "Mail";

                    HorizontalBox {
                        MailView {
                            break-layout: root.break-layout;
                        }
                    }
                }

                Tab {
                    title: "Dashboard";

                    HorizontalLayout {
                        padding: 4px;

                        DashboardView { }
                    }
                }
            }
        }
    }
}
