// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

component Extra2 inherits Rectangle {
    in-out property<int> top_level;
    in-out property<int> value;
    callback update_value;
    for aaa[r] in [[10, top_level], [2, 3]] : blah := Rectangle {
        y:0;
        width: parent.width;
        height: root.height;
        property <int> some_value: 1000;
        for bb[l] in aaa : TouchArea {
            property <int> some_value: 1515;
            width: 10phx;
            height: 10phx;
            x: r*10phx;
            y: l*10phx;
            clicked => {
                value += bb + blah.some_value;
                update_value();
            }
        }
    }
}

export component TestCase inherits Rectangle {
    width: 100phx;
    height: 100phx;
    background: white;
    in-out property<float> top_level: 42;
    in-out property<int> value: 0;

    Extra2 {
        y:0;
        width: parent.width;
        height: root.height;
        top_level: top_level;
        update_value => {
            value = self.value;
        }
    }
}

/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;

slint_testing::send_mouse_click(&instance, 5., 5.);
assert_eq(instance.get_value(), 1010);

slint_testing::send_mouse_click(&instance, 15., 15.);
assert_eq(instance.get_value(), 2013);

slint_testing::send_mouse_click(&instance, 5., 15.);
assert_eq(instance.get_value(), 3000+13+42);
```


```rust
let instance = TestCase::new().unwrap();

slint_testing::send_mouse_click(&instance, 5., 5.);
assert_eq!(instance.get_value(), 1010);

slint_testing::send_mouse_click(&instance, 15., 15.);
assert_eq!(instance.get_value(), 2013);

slint_testing::send_mouse_click(&instance, 5., 15.);
assert_eq!(instance.get_value(), 3000+13+42);

```

```js
var instance = new slint.TestCase();
slintlib.private_api.send_mouse_click(instance, 5., 5.);
assert.equal(instance.value, 1010);

instance.cond1 = true;
slintlib.private_api.send_mouse_click(instance, 15., 15.);
assert.equal(instance.value, 2013);

instance.cond1 = false;
slintlib.private_api.send_mouse_click(instance, 5., 15.);
assert.equal(instance.value, 3000+13+42);
```
*/
