// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

export global MaterialStyleMetrics {
    // sizes
    out property <length> size_1: 1px;
    out property <length> size_2: 2px;
    out property <length> size_3: 3px;
    out property <length> size_4: 4px;
    out property <length> size_6: 6px;
    out property <length> size_8: 8px;
    out property <length> size_14: 14px;
    out property <length> size_16: 16px;
    out property <length> size_18: 18px;
    out property <length> size_20: 20px;
    out property <length> size_24: 24px;
    out property <length> size_30: 30px;
    out property <length> size_32: 32px;
    out property <length> size_36: 36px;
    out property <length> size_38: 38px;
    out property <length> size_40: 40px;
    out property <length> size_48: 48px;
    out property <length> size_49: 49px;
    out property <length> size_52: 52px;
    out property <length> size_56: 56px;
    out property <length> size_64: 64px;
    out property <length> size_72: 72px;
    out property <length> size_80: 80px;
    out property <length> size_90: 96px;
    out property <length> size_200: 200px;
    out property <length> size_256: 256px;
    out property <length> size_344: 344px;
    out property <length> size_360: 360px;
    out property <length> size_572: 572px;
    out property <length> size_640: 640px;

    // icon
    out property <length> icon_size_18: 18px;
    out property <length> icon_size_24: 24px;
    out property <length> icon_size_36: 36px;
    out property <length> icon_size_90: 27px;

    // padding
    out property <length> padding_4: 4px;
    out property <length> padding_6: 6px;
    out property <length> padding_10: 10px;
    out property <length> padding_12: 12px;
    out property <length> padding_8: 8px;
    out property <length> padding_14: 14px;
    out property <length> padding_16: 16px;
    out property <length> padding_20: 20px;
    out property <length> padding_24: 24px;
    out property <length> padding_28: 28px;
    out property <length> padding_30: 30px;
    out property <length> padding_44: 44px;
    out property <length> padding_56: 56px;

    // spacing
    out property <length> spacing_2: 2px;
    out property <length> spacing_6: 6px;
    out property <length> spacing_4: 4px;
    out property <length> spacing_8: 8px;
    out property <length> spacing_12: 12px;
    out property <length> spacing_16: 16px;
    out property <length> spacing_40: 40px;
    out property <length> spacing_52: 52px;

    // border_radius
    out property <length> border_radius_2: 2px;
    out property <length> border_radius_4: 4px;
    out property <length> border_radius_8: 8px;
    out property <length> border_radius_12: 12px;
    out property <length> border_radius_16: 16px;
    out property <length> border_radius_28: 28px;
}
