// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { LineEdit, Button, Slider, StandardListView, GridBox, HorizontalBox } from "std-widgets.slint";

MainWindow := Window {

    GridBox {
        Text { text: "Filter prefix:"; }
        LineEdit {}

        StandardListView {
            row: 1;
            rowspan: 3;
            colspan: 2;
            model: root.names-list;
        }

        Text { col: 2; row: 1; text: "Name: "; }
        LineEdit { text <=> root.name; }
        Text { col: 2; row: 2; text: "Surname: "; }
        LineEdit { text <=> root.surname; }

        HorizontalBox {
            row: 4;
            alignment: start;
            Button {
                text: "Create";
                clicked => { root.createClicked() }
            }
            Button {
                text: "Update";
                clicked => { root.updateClicked() }
            }
            Button {
                text: "Delete";
                clicked => { root.deleteClicked() }
            }
        }

    }
    property <[StandardListViewItem]> names-list;
    property <string> name;
    property <string> surname;

    callback createClicked();
    callback updateClicked();
    callback deleteClicked();
}
