// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

Win := Window {
    property <color> base: #00007F;
    GridLayout {
        r := Rectangle {
            background: base;
        }
        Rectangle {
            background: base.brighter(50%);
        }
        Rectangle {
            background: base.darker(50%);
        }
    }
}
