// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

Win := Window {
    GridLayout {
        Image {
            source: @image-url("../../../examples/printerdemo/ui/images/cat.jpg");
        }
        Image {
            source: @image-url("../../../examples/printerdemo/ui/images/cat.jpg");
            image-fit: contain;
        }
        Image {
            row: 1;
            source: @image-url("../../../examples/printerdemo/ui/images/cat.jpg");
            image-fit: cover;
        }
        Image {
            source: @image-url("../../../examples/printerdemo/ui/images/cat.jpg");
            image-fit: fill;
        }
    }
}
