// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

component Comp inherits Rectangle {
    Rectangle {
        x:0;y:0;
        width: 5%;
        height: 5%;
        background: white;
        opacity: 1;
    }
}


export component TestCase inherits Window {
    width: 800px;
    height: 600px;
    background: green;

    Rectangle {
        x:0;y:0;
        background: red;
        width: 50%;
        height: 50%;
        opacity: 0.5;
    }

    Comp {
        background: blue;
        x: parent.width / 4;
        y: parent.height / 4;
        width: 50%;
        height: 50%;
        opacity: 0.5;
        Rectangle {
            x:0;y:0;
            width: 10%;
            height: 10%;
            background: yellow;
        }
    }

    for i in 3 : Rectangle {
        background: black;
        width: 10%;
        height: 10%;
        opacity: 0.2 * (i + 1);
        y: parent.height / 3;
        x: parent.width / 4 * i;
    }


}
