// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

use std::path::PathBuf;

fn main() {
    napi_build::setup();

    // workaround bug that the `#[napi]` macro generate some invalid `#[cfg(feature="...")]`
    println!("cargo:rustc-check-cfg=cfg(feature,values(\"noop\", \"used_linker\"))");

    generate_language_module();
}

/// Collect every `pub enum` declared in `i_slint_common::for_each_enums!` and emit
/// `typescript/generated/language.ts`. Each enum becomes an `as const` map from the Rust
/// variant identifier to the kebab-case string the Slint runtime accepts; a type-only
/// `namespace language { … }` declaration provides the named union types so users can write
/// `let s: language.ColorScheme = language.ColorScheme.Dark;`.
fn generate_language_module() {
    struct EnumEntry {
        name: &'static str,
        docs: Vec<&'static str>,
        values: Vec<(&'static str, Vec<&'static str>)>,
    }
    let mut entries: Vec<EnumEntry> = Vec::new();
    macro_rules! collect_public_enums {
        ($(
            $(#[doc = $enum_doc:literal])*
            $(#[non_exhaustive])?
            $vis:vis enum $Name:ident {
                $( $(#[doc = $value_doc:literal])* $Value:ident, )*
            }
        )*) => {
            $(
                if stringify!($vis) == "pub" {
                    entries.push(EnumEntry {
                        name: stringify!($Name),
                        docs: vec![$($enum_doc),*],
                        values: vec![$( (stringify!($Value), vec![$($value_doc),*]) ),*],
                    });
                }
            )*
        };
    }
    i_slint_common::for_each_enums!(collect_public_enums);

    let mut ts = String::new();
    ts.push_str("// Copyright © SixtyFPS GmbH <info@slint.dev>\n");
    // Build the SPDX header from concatenated parts so REUSE's linter doesn't try to
    // parse the literal as if it applied to this Rust file.
    ts.push_str(concat!(
        "// SPDX-License-",
        "Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0\n\n",
    ));
    ts.push_str(
        "// AUTO-GENERATED by api/node/build.rs from internal/common/enums.rs. Do not edit.\n\n",
    );

    ts.push_str("const _data = {\n");
    for entry in &entries {
        write_jsdoc(&mut ts, "    ", &entry.docs);
        ts.push_str(&format!("    {}: {{\n", entry.name));
        for (variant, value_docs) in &entry.values {
            write_jsdoc(&mut ts, "        ", value_docs);
            ts.push_str(&format!(
                "        {variant}: \"{kebab}\",\n",
                kebab = to_kebab_case(variant)
            ));
        }
        ts.push_str("    },\n");
    }
    ts.push_str("} as const;\n\n");

    ts.push_str("/**\n");
    ts.push_str(" * Built-in enums from the Slint language, exported with both value and type semantics.\n");
    ts.push_str(" * Use as `language.ColorScheme.Dark` for the runtime value, and as `language.ColorScheme`\n");
    ts.push_str(" * in type position for the variant union (e.g. `let s: language.ColorScheme = …`).\n");
    ts.push_str(" */\n");
    ts.push_str("export const language = _data;\n\n");

    ts.push_str("/** Named union types for the values in {@link language}. */\n");
    ts.push_str("// biome-ignore lint/style/useConst: declaration-merging namespace, type-only.\n");
    ts.push_str("export namespace language {\n");
    for entry in &entries {
        write_jsdoc(&mut ts, "    ", &entry.docs);
        ts.push_str(&format!(
            "    export type {name} = (typeof _data.{name})[keyof typeof _data.{name}];\n",
            name = entry.name
        ));
    }
    ts.push_str("}\n");

    let out_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("typescript").join("generated");
    std::fs::create_dir_all(&out_dir).expect("create typescript/generated directory");
    let out_path = out_dir.join("language.ts");
    // Only write if the content actually changed, so we don't invalidate downstream builds.
    let need_write =
        std::fs::read_to_string(&out_path).map(|existing| existing != ts).unwrap_or(true);
    if need_write {
        std::fs::write(&out_path, ts).expect("write typescript/generated/language.ts");
    }
}

/// Emit the rustdoc lines as a JSDoc block at the given indent. No-op if `docs` is empty.
/// Each Rust `///` line carries a leading space; we keep it (it's how the original prose is
/// formatted) and just wrap with `/**` … `*/`.
fn write_jsdoc(out: &mut String, indent: &str, docs: &[&str]) {
    if docs.is_empty() {
        return;
    }
    out.push_str(indent);
    out.push_str("/**\n");
    for line in docs {
        out.push_str(indent);
        out.push_str(" *");
        out.push_str(line);
        out.push('\n');
    }
    out.push_str(indent);
    out.push_str(" */\n");
}

/// Convert `CamelCase` to `kebab-case`. Matches `i_slint_compiler::generator::to_kebab_case`
/// so generated values line up with `Enumeration::values` in the type register.
fn to_kebab_case(s: &str) -> String {
    let mut out = Vec::with_capacity(s.len());
    for b in s.as_bytes() {
        if b.is_ascii_uppercase() {
            if !out.is_empty() {
                out.push(b'-');
            }
            out.push(b.to_ascii_lowercase());
        } else {
            out.push(*b);
        }
    }
    String::from_utf8(out).unwrap()
}
