// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

TestCase := Window {
    property <int> t_: 8;
    property <int> t_old: -1;
    background: {
         if (t_ == 8) { t_old = t_; t_=1; }
         t_ == 1 ?  white : black
    }

    property <bool> test: background == Colors.white && t_ == 1 && t_old == 8;
}

/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert(instance.get_test());
```

```rust
let instance = TestCase::new().unwrap();
assert!(instance.get_test());

```

```js
var instance = new slint.TestCase({});
assert(instance.test);
```
*/



