// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

export global Icons {
    out property <image> check: @image-url("check.svg");
    out property <image> close: @image-url("close.svg");
    out property <image> menu: @image-url("menu.svg");
    out property <image> arrow_back: @image-url("arrow_back.svg");
    out property <image> arrow_right: @image-url("arrow_right.svg");
    out property <image> remove: @image-url("remove.svg");
    out property <image> schedule: @image-url("schedule.svg");
    out property <image> keyboard: @image-url("keyboard.svg");
}
