# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

[package]
name = "i-slint-springboard"
description = "Shared project and device management for Slint development sessions"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[dependencies]
cargo_metadata = "0.23"
directories = "6.0"
serde = { workspace = true, features = ["std"] }
serde_json = { workspace = true }
tempfile = "3"
toml_edit = { workspace = true }
