
// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.2 OR LicenseRef-Slint-commercial

import { NotExist } from "idontexist.slint";
//                       ^error{Cannot find requested import "idontexist.slint" in the include search path}

export component Bug {
    callback foo <=> xx.foo;
    out property bar <=> xx.bar;
    in property <int> wyz <=> xx.wyz;
    xx := NotExist {   }
}