// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

export Unused := Rectangle {
   // FIXME: looks like binding loop is not diagnozed in exports if the properties are not used
    property <int> a1: a2;
    property <int> a2: a1;
}

export Z := Rectangle {
    property <int> b1: b2;
                     //^error{loop}
    property <int> b2: b1;
                     //^error{loop}
}
