#!/usr/bin/env bash
# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

#MISE description="Run clang-format fix on all files"

set -e

fd '.*\.(h|H|hpp|hxx|c|C|cpp|cxx)$' | \
  xargs clang-format -i
