// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { SettingsAdapter } from "../pages/menu_page/settings.slint";
import { Theme } from "../theme.slint";

export component KioskOverlay {
    TouchArea {
        clicked => {
            SettingsAdapter.kiosk-mode-checked = false;
        }
    }

    Rectangle { 
        x: i-text.x - 1px;
        y: i-text.y - 1px;
        width: i-text.width + 2px;
        height: i-text.height + 2px;
        background: Theme.palette.pure-black;
        opacity: 0.5;
    }

    i-text := Text {
        x: parent.width - self.width - 5px;
        y: 5px;
        font-size: Theme.typo.desciption.size;
        font-weight: Theme.typo.desciption.weight;
        text: "Kiosk";
        color: Theme.palette.limon-green;
        opacity: 0.5;
    }
}