// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

import { FluentFontSettings, FluentPalette } from "styling.slint";

export component GroupBox {
    in property <string> title <=> label.text;
    in property <bool> enabled: true;

    VerticalLayout {
        spacing: 8px;
        padding-top: 16px;
        padding-bottom: 8px;

        label := Text {
            vertical-stretch: 0;
            color: !root.enabled ? FluentPalette.text-disabled : FluentPalette.control-foreground;
            font-size: FluentFontSettings.body-strong.font-size;
            font-weight: FluentFontSettings.body-strong.font-weight;
        }

        Rectangle {
            vertical-stretch: 1;

            GridLayout {
                @children
            }
        }
    }
}
