// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

import { ColorSchemeSelector } from "color-scheme.slint";

import { Button } from "button.slint";
export { Button }

import { ScrollView } from "scrollview.slint";
export { ScrollView }

import { Palette, Typography } from "styling.slint";

export global StyleMetrics  {
    out property<length> layout-spacing: 8px;
    out property<length> layout-padding: 8px;
    out property<length> text-cursor-width: 1px;
    out property<color> window-background: Palette.background;
    out property<color> default-text-color: Palette.text-primary;
    out property<color> textedit-background: Palette.background;
    out property<color> textedit-text-color: Palette.text-primary;
    out property<color> textedit-background-disabled: Palette.control-disabled;
    out property<color> textedit-text-color-disabled: Palette.text-disabled;
    out property<bool> dark-color-scheme: Palette.dark-color-scheme;
}