// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Style, GridStyle } from "../style.slint";

export component EditorGrid inherits Rectangle {
    in property <GridStyle> style: Style.grid;
    clip: true;
    for row in ceil(root.height / root.style.pitch): Rectangle {
        y: row * root.style.pitch;
        height: root.style.line-width;
        background: root.style.color;
    }
    for col in ceil(root.width / root.style.pitch): Rectangle {
        x: col * root.style.pitch;
        width: root.style.line-width;
        background: root.style.color;
    }
}
