// Copyright © 2025 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nathan Collins <nathan.collins@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export interface ValidInterfacePropertyDeclarations {
    property <bool> implicit-private;
//  >                               <error{'private' properties are inaccessible in an interface}

    private property <int> private;
//  >                             <error{'private' properties are inaccessible in an interface}

    in property <int> in-property;
    out property <string> out-property;
    in-out property <angle> in-out-property;
    in_out property <angle> in-out-underscore-property;
}

export interface Background {
    in-out property <color> background;
    callback clip();
}

export component MyComponent implements Background inherits Rectangle { }
//                                      >         <error{Cannot implement interface 'Background' because 'background' conflicts with an existing property in 'Rectangle'}
//                                      >         <^error{Cannot implement interface 'Background' because 'clip' conflicts with an existing property in 'Rectangle'}
