// Copyright © 2025 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nathan Collins <nathan.collins@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0


interface InterfaceI {
    out property <bool> test;
}

component Base implements InterfaceI { }

export component InvalidUses uses { InterfaceI from
, } { }
//^<<error{Syntax error: expected Identifier}
