// Copyright © 2025 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nathan Collins <nathan.collins@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component UsesBuiltin uses { Rectangle from base } {
//                                  >        <error{'Rectangle' is not an interface}
    base := Rectangle { }
}

component ComponentA { }

export component UsesComponent uses { ComponentA from base } {
//                                    >         <error{'ComponentA' is not an interface}
    base := ComponentA { }
}

export component UsesMissing uses { MissingInterface from base } {
//                                  >               <error{Unknown element 'MissingInterface'}
    base := ComponentA { }
}

export component UsesRow uses { Row from base } {
//                              >  <error{Row can only be within a GridLayout element}
    base := ComponentA { }
}

export component UsesRowInGridLayout uses { Row from base } inherits GridLayout {
//                                          >  <error{Row can only be within a GridLayout element}
    base := ComponentA { }
}

export component MultipleErrors uses { MissingInterface from base, Rectangle from base, ComponentA from base, Row from base } {
//                                     >               <error{Unknown element 'MissingInterface'}
//                                                                 >        <^error{'Rectangle' is not an interface}
//                                                                                      >         <^^error{'ComponentA' is not an interface}
//                                                                                                            >  <^^^error{Row can only be within a GridLayout element}
    base := ComponentA { }
}

export interface ValidInterface {
    in-out property <int> value;
    callback speak();
}

export component MissingChild uses { ValidInterface from base} { }
//                                                       >  <error{'base' does not exist}

export component ChildDoesNotImplementInterface uses { ValidInterface from base } {
//                                                                         >  <error{base does not implement ValidInterface}
    base := ComponentA { }
}

component ValidBase implements ValidInterface { }

export component ConflictingNames uses { ValidInterface from base } {
    base := ValidBase { }

    in-out property <int> value;
//                        >   <error{Cannot override 'value' from 'ValidInterface'}

    callback speak();
//           >   <error{Cannot override 'speak' from 'ValidInterface'}

}

component BaseWithConflicts {
    in-out property <int> value: 10;
    callback speak();
    @children
}

export component DuplicatPropertyOnBase uses { ValidInterface from base } inherits BaseWithConflicts {
//                                             >             <error{Cannot use interface 'ValidInterface' because 'speak' conflicts with an existing callback in 'BaseWithConflicts'}
//                                             >             <^error{Cannot use interface 'ValidInterface' because 'value' conflicts with an existing property in 'BaseWithConflicts'}
    base := ValidBase { }
}

interface InterfaceA {
    in property <bool> test;
}

component AImpl implements InterfaceA { }

interface InterfaceB {
    out property <bool> test: true;
}

component BImpl implements InterfaceB { }

export component ConflictingUses uses { InterfaceA from a, InterfaceB from b } {
//                                                         >         <error{'test' occurs in 'InterfaceB' and 'InterfaceA'}
    a := AImpl { }

    b := BImpl { }
}

export component DuplicateUses uses { InterfaceA from a, InterfaceA from b } {
//                                                       >         <error{'InterfaceA' is used multiple times}
    a := AImpl { }

    b := AImpl { }
}
