// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import "myfont.ttf";
//     ^error{File "myfont.ttf" not found}
import "myfontcollection.ttc";
//     ^error{File "myfontcollection.ttc" not found}
import "myimage.png";
//     ^error{Unsupported foreign import "myimage.png"}

export Test := Window {
}
