// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// Even if that file exists in the style, it shouldn't be loaded.
// Nothing is importable from "std-widgets-impl.slint", regardless of the symbol.
import { StyleMetrics } from "std-widgets-impl.slint";
//                           >                      <error{Cannot find requested import "std-widgets-impl.slint" in the include search path}
import { ToolTipImpl } from "std-widgets-impl.slint";
//                          >                      <error{Cannot find requested import "std-widgets-impl.slint" in the include search path}
import { Button } from "std-widgets-impl.slint";
//                     >                      <error{Cannot find requested import "std-widgets-impl.slint" in the include search path}
import { NotAThing } from "std-widgets-impl.slint";
//                        >                      <error{Cannot find requested import "std-widgets-impl.slint" in the include search path}
