// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { NotExported } from "../../typeloader/incpath/local_helper_type.slint";
//                          ^error{No exported type called 'NotExported' found}
  import { } from "../../typeloader/incpath/local_helper_type.slint";
//^error{Import names are missing. Please specify which types you would like to import}

export X := Rectangle {

}
