// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

export { Foo as Bar }
//       ^error{'Foo' not found}

export { Image as Plop }
//       ^error{Cannot export 'Image' because it is not a component}

export { string as Boob }
//       ^error{Cannot export 'string' because it is not a component}

export Hello := Plop {
//              ^error{Unknown type Plop}
}
