// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { SomeRect } from "../../typeloader/incpath/local_helper_type.slint";

import { X } from "../../typeloader/incpath/should_fail.slint";

export Blah := X {
//          ^warning{':=' to declare a component is deprecated. The new syntax declare components with 'component MyComponent {'. Read the documentation for more info}
    width: 100px;
//  ^error{Unknown property width in X}
}
