// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { BaseButton } from "./base_button.slint";
import { Typography } from "../styling/typography.slint";
import { MaterialPalette } from "../styling/material_palette.slint";
import { MaterialStyleMetrics } from "../styling/material_style_metrics.slint";

export component ActionChip {
    in property <image> icon <=> base.icon;
    in property <string> text <=> base.text;
    in property <bool> enabled <=> base.enabled;
    in property <string> tooltip <=> base.tooltip;
    in property <image> avatar <=> base.avatar;
    in property <color> avatar_background <=> base.avatar_background;

    callback clicked <=> base.clicked;

    accessible-role: button;
    accessible-enabled: root.enabled;
    accessible-label: root.text == "" ? root.tooltip : root.text;
    accessible-action-default => { base.clicked(); }
    
    base := BaseButton {
        min_layout_height: MaterialStyleMetrics.size_32;
        border_radius: MaterialStyleMetrics.border_radius_8;
        color: MaterialPalette.on_surface;
        icon_color: MaterialPalette.primary;
        spacing: MaterialStyleMetrics.spacing_8;
        padding_left: self.has_icon ? MaterialStyleMetrics.padding_8 : MaterialStyleMetrics.padding_16;
        padding_right:MaterialStyleMetrics.padding_16;
        vertical_padding: MaterialStyleMetrics.padding_6;
        avatar_size: MaterialStyleMetrics.size_18;

        border := Rectangle {
            border_radius: base.border_radius;
            border_width: 1px;
            border_color: MaterialPalette.outline;
        }
    }

    states [
        disabled when !root.enabled : {
            base.display_background: false;
            base.icon_color: MaterialPalette.on_surface;
        }
    ]
}

export component FilterChip {
    
}

export component InputChip {
    
}

