// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { MaterialPalette } from "../styling/material_palette.slint";
import { MaterialStyleMetrics } from "../styling/material_style_metrics.slint";

export component Avatar {
    in property <image> image;
    in property <color> background: MaterialPalette.primary;

    min_width: MaterialStyleMetrics.size_32;
    height: self.width;

    Rectangle {
        width: 100%;
        height: 100%;
        border_radius: self.width / 2;
        background: root.background;
        clip: true;

        Image {
            width: 100%;
            source: root.image;
        }
    }
}

export component ListItemTemplate {
    in property <string> text;
    in property <string> supporting_text;
    in property <image> avatar;
    in property <color> avatar_background;
    in property <color> avatar_colorize;
}

