// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

component Foo {
    foo := {}
    //     ^error{Syntax error: expected Identifier}

    Image {}

    bar :=
  }
//^error{Syntax error: expected Identifier}

component Bar inherits {
//                     ^error{Syntax error: expected Identifier}
    if true : {}
//            ^error{Syntax error: expected Identifier}
}
