// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

 TestCase := Rectangle {
    property<angle> t1: asin(0);
    property<angle> t2: asin(0.5);
    property<angle> t3: asin(1);
}
/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert(std::abs(instance.get_t1()) < 0.0001);
assert(std::abs(instance.get_t2() - 30.0) < 0.0001);
assert(std::abs(instance.get_t3() - 90.0) < 0.0001);
```

```rust
let instance = TestCase::new().unwrap();
assert!(instance.get_t1().abs() < 0.0001);
assert!((instance.get_t2() - 30.0).abs() < 0.0001);
assert!((instance.get_t3() - 90.0).abs() < 0.0001);
```

```js
var instance = new slint.TestCase({});
assert.equal(instance.t1, 0);
assert.equal(instance.t2, 30);
assert.equal(instance.t3, 90);
```
*/
