// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

TestCase := Rectangle {
    property<string> text: "init";
    property<string> text2: { debug(text); text }
    callback foo;
    foo => {
        debug("callback");
    }
    background: { test; text2; blue  }

    im := Image {}

    property <bool> test: {
        debug();
        debug(42, 42px, width / 5s, { x: 42, y: im.image_fit, z: { d: im.opacity } }, root.background, im.source);
        true;
    }
}
