// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

 TestCase := Rectangle {
    property <float> t1: ln(1);
    property <float> t2: ln(exp(3));
}
/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert_eq(instance.get_t1(), 0.0);
assert_eq(instance.get_t2(), 3.0);
```

```rust
let instance = TestCase::new().unwrap();
assert_eq!(instance.get_t1(), 0.0);
assert_eq!(instance.get_t2(), 3.0);
```

```js
var instance = new slint.TestCase({});
assert.equal(instance.t1, 0);
assert.equal(instance.t2, 3);
```

```go
instance, err := ui.NewTestCase()
assertion.NoError(err)

t1, err := instance.GetT1()
assertion.NoError(err)
assertion.InDelta(0.0, t1, 0.0001)
t2, err := instance.GetT2()
assertion.NoError(err)
assertion.InDelta(3.0, t2, 0.0001)
```
*/
