// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

 TestCase := Rectangle {
    property<float> t1: log(4.0, 2);
    property<float> t2: log(64, 4.0);
}
/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert_eq(instance.get_t1(), 2.0);
assert_eq(instance.get_t2(), 3.0);
```

```rust
let instance = TestCase::new().unwrap();
assert_eq!(instance.get_t1(), 2.0);
assert_eq!(instance.get_t2(), 3.0);
```

```js
var instance = new slint.TestCase({});
assert.equal(instance.t1, 2);
assert.equal(instance.t2, 3);
```
*/
