// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

 component TestCase inherits Window {
    out property<int> t1: round(42.2);
    out property<int> t2: round(23.5);
    out property<int> t3: round(24.6);
    out property<int> t4: round(25);

    out property<int> n1: round(-42.2);
    out property<int> n2: round(-23.5);
    out property<int> n3: round(-24.6);
    out property<int> n4: round(-25);

    out property <bool> test: 188.9.round() == 189 && (-4.58).round() == -(5.1).round()
        && round(10.1) != 10.1 && !(30.3 == round(30.3));
}
/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert_eq(instance.get_t1(), 42);
assert_eq(instance.get_t2(), 24);
assert_eq(instance.get_t3(), 25);
assert_eq(instance.get_t4(), 25);
assert_eq(instance.get_n1(), -42);
assert_eq(instance.get_n2(), -24);
assert_eq(instance.get_n3(), -25);
assert_eq(instance.get_n4(), -25);
assert(instance.get_test());
```

```rust
let instance = TestCase::new().unwrap();
assert_eq!(instance.get_t1(), 42);
assert_eq!(instance.get_t2(), 24);
assert_eq!(instance.get_t3(), 25);
assert_eq!(instance.get_t4(), 25);
assert_eq!(instance.get_n1(), -42);
assert_eq!(instance.get_n2(), -24);
assert_eq!(instance.get_n3(), -25);
assert_eq!(instance.get_n4(), -25);
assert!(instance.get_test());
```

```js
var instance = new slint.TestCase({});
assert.equal(instance.t1, 42);
assert.equal(instance.t2, 24);
assert.equal(instance.t3, 25);
assert.equal(instance.t4, 25);
assert.equal(instance.n1, -42);
assert.equal(instance.n2, -24);
assert.equal(instance.n3, -25);
assert.equal(instance.n4, -25);
assert(instance.test);
```

```go
instance, err := ui.NewTestCase()
assertion.NoError(err)

t1, err := instance.GetT1()
assertion.NoError(err)
assertion.Equal(42, t1)
t2, err := instance.GetT2()
assertion.NoError(err)
assertion.Equal(24, t2)
t3, err := instance.GetT3()
assertion.NoError(err)
assertion.Equal(25, t3)
t4, err := instance.GetT4()
assertion.NoError(err)
assertion.Equal(25, t4)
n1, err := instance.GetN1()
assertion.NoError(err)
assertion.Equal(-42, n1)
n2, err := instance.GetN2()
assertion.NoError(err)
assertion.Equal(-24, n2)
n3, err := instance.GetN3()
assertion.NoError(err)
assertion.Equal(-25, n3)
n4, err := instance.GetN4()
assertion.NoError(err)
assertion.Equal(-25, n4)
test, err := instance.GetTest()
assertion.NoError(err)
assertion.True(test)
```
*/
