// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

 TestCase := Rectangle {
    property<float> t1: tan(0);
    property<float> t2: tan(45deg);
    property<float> t3: tan(75deg);
}
/*
```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert(std::abs(instance.get_t1()) < 0.0001);
assert(std::abs(instance.get_t2() - 1.0) < 0.0001);
assert(std::abs(instance.get_t3() - (2.0 + std::sqrt(3.0))) < 0.0001);
```

```rust
let instance = TestCase::new().unwrap();
assert!(instance.get_t1().abs() < 0.0001);
assert!((instance.get_t2() - 1.0).abs() < 0.0001);
assert!((instance.get_t3() - (2.0 + 3.0_f32.sqrt())).abs() < 0.0001);
```

```js
var instance = new slint.TestCase({});
assert(Math.abs(instance.t1) < 0.0001);
assert(Math.abs(instance.t2 - 1) < 0.0001);
assert(Math.abs(instance.t3 - (2 + Math.sqrt(3))) < 0.0001);
```

```go
instance, err := ui.NewTestCase()
assertion.NoError(err)

t1, err := instance.GetT1()
assertion.NoError(err)
assertion.InDelta(0.0, t1, 0.0001)
t2, err := instance.GetT2()
assertion.NoError(err)
assertion.InDelta(1.0, t2, 0.0001)
t3, err := instance.GetT3()
assertion.NoError(err)
assertion.InDelta(3.732050807568877, t3, 0.0001)
```
*/
