import { DemoPalette, Theme, ComponentTheme, SubPage } from "../common.slint";
import { PrinterState } from "../common.slint";

component SideBarIcon inherits Rectangle {
    in-out property <bool> active;
    in-out property <image> icon <=> i.source;
    in-out property <brush> icon-colorize <=> i.colorize;

    callback activate;
    width: ComponentTheme.side-bar.icon-size;
    height: self.width;
    background: active || ta.has-hover ? ComponentTheme.side-bar.active-background : Colors.transparent;
    border-radius: ComponentTheme.side-bar.icon-border-radius;

    i := Image {
        colorize: root.active || ta.has-hover ? ComponentTheme.side-bar.active-icon-color : ComponentTheme.side-bar.inactive-icon-color;
    }

    ta := TouchArea {
        clicked => {
            root.activate();
        }
    }
}

export component Sidebar inherits Rectangle {
    background: ComponentTheme.side-bar.background;
    x: 0px;
    width: DemoPalette.side-bar-width;

    callback select-theme;

    VerticalLayout {
        width: self.preferred-width;
        padding-top: DemoPalette.default-margin;
        spacing: DemoPalette.default-margin;
        alignment: start;

        for page-icon[index] in [
            @image-url("../images/sidebar/home.svg"),
            @image-url("../images/sidebar/settings.svg"),
            @image-url("../images/sidebar/ink.svg"),
        ]: SideBarIcon {
            activate => {
                PrinterState.current-subpage = SubPage.none;
                PrinterState.active-page = index;
            }
            icon: page-icon;
            active: PrinterState.active-page == index;
        }
    }

    VerticalLayout {
        width: self.preferred-width;
        padding-bottom: DemoPalette.default-margin;
        spacing: DemoPalette.default-margin;
        alignment: end;

        SideBarIcon {
            activate => {
                root.select-theme();
            }
            icon: @image-url("../images/sidebar/theme.svg");
            icon-colorize: ComponentTheme.side-bar.inactive-icon-color;
        }
    }

    side-separator := Rectangle {
        x: root.width - self.width;
        width: 1px;
        background: ComponentTheme.side-bar.separator;
        height: 100%;
    }
}
