// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Palette, VerticalBox, ScrollView }  from "std-widgets.slint";

import { Api, ElementInformation, PropertyGroup, PropertyInformation, PropertyValueKind } from "../api.slint";
import { GroupHeader } from "../components/group.slint";
import { EditorSizeSettings, EditorSpaceSettings } from "../components/styling.slint";

import { BooleanWidget, ColorWidget, CodeWidget, EnumWidget, ExpandableGroup, FloatWidget, IntegerWidget, StringWidget } from "../components/property-widgets.slint";

export component PropertyView {
    in property <bool> enabled;

    property <ElementInformation> element-information <=> Api.current-element;
    property <[PropertyGroup]> properties <=> Api.properties;

    property <length> key-width: self.width / 2.5;
    property <bool> element-loaded: root.properties.length > 0;

    width: EditorSizeSettings.property-bar-width;

    content-layer := VerticalLayout {
        GroupHeader {
            title: @tr("{} Properties", root.element-information.type-name);
            vertical-stretch: 0;
        }

        if !root.element-loaded: Text {
            text: @tr("Select an Element");
            horizontal-alignment: center;
            vertical-alignment: center;
            vertical-stretch: 1;
        }

        if root.element-loaded: ScrollView {
            preferred-height: groups.preferred-height;
            groups := VerticalBox {
                alignment: start;

                for group in root.properties: eg := ExpandableGroup {
                    property <[PropertyInformation]> properties: group.properties;
                    
                    enabled: root.enabled;

                    text: group.group-name;
                    panel-width: content-layer.width;

                    VerticalLayout {
                        spacing: EditorSpaceSettings.property-spacing;
                        padding-left: EditorSpaceSettings.group-indent;
                        padding-right: EditorSpaceSettings.group-indent;
                        padding-top: EditorSpaceSettings.default-padding;
                        padding-bottom: EditorSpaceSettings.default-padding;

                        for property in eg.properties: HorizontalLayout {
                            alignment: stretch;

                            if property.value.kind == PropertyValueKind.boolean: BooleanWidget {
                                enabled: root.enabled;
                                element-information <=> root.element-information;
                                property-information: property;
                            }
                            if (property.value.kind == PropertyValueKind.color) || (property.value.kind == PropertyValueKind.brush): ColorWidget {
                                enabled: root.enabled;
                                element-information <=> root.element-information;
                                property-information: property;
                            }

                            if property.value.kind == PropertyValueKind.code: CodeWidget {
                                enabled: root.enabled;
                                element-information <=> root.element-information;
                                property-information: property;
                            }
                            if property.value.kind == PropertyValueKind.enum:  EnumWidget {
                                enabled: root.enabled;
                                element-information <=> root.element-information;
                                property-information: property;
                            }
                            if property.value.kind == PropertyValueKind.float: FloatWidget {
                                enabled: root.enabled;
                                element-information <=> root.element-information;
                                property-information: property;
                            }
                            if property.value.kind == PropertyValueKind.integer: IntegerWidget {
                                enabled: root.enabled;
                                element-information <=> root.element-information;
                                property-information: property;
                            }
                            if property.value.kind == PropertyValueKind.string: StringWidget {
                                enabled: root.enabled;
                                element-information <=> root.element-information;
                                property-information: property;
                            }
                        }
                    }
                    
                }
            }
        }
    }

    Rectangle {
        x: 0;
        width: 1px;
        background: Palette.border;
    }
}
