import { Theme } from "theme.slint";
import { Label } from "label.slint";

export Pill := Rectangle {
    property <color> foreground: Theme.window-background;
    property <string> text: "text";

    padding: Theme.widget-spacing-medium;
    background: Theme.widget-foreground;
    border-radius: Theme.widget-radius-regular;

    width: label.width + self.padding;
    height: label.height + self.padding;

    label := Label { 
        x: root.padding / 2;
        y: root.padding / 2;
        color: root.foreground;
        text <=> root.text;
     }
}