// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Palette } from "std-widgets.slint";

export global Icons {
    out property <image> archive: @image-url("assets/archive.svg");
    out property <image> inbox: @image-url("assets/inbox.svg");
    out property <image> cloud: @image-url("assets/cloud.svg");
    out property <image> document: @image-url("assets/document.svg");
    out property <image> forward: @image-url("assets/forward.svg");
    out property <image> junk: @image-url("assets/junk.svg");
    out property <image> message: @image-url("assets/message.svg");
    out property <image> reply: @image-url("assets/reply.svg");
    out property <image> search: @image-url("assets/search.svg");
    out property <image> send: @image-url("assets/send.svg");
    out property <image> trash: @image-url("assets/trash.svg");
    out property <image> updates: @image-url("assets/updates.svg");
    out property <image> useres: @image-url("assets/users.svg");
    out property <image> slint-logo: Palette.color-scheme == ColorScheme.dark ? @image-url("../../../logo/slint-logo-simple-dark.png") : @image-url("../../../logo/slint-logo-simple-light.png");
    out property <image> menu: @image-url("assets/menu.svg");
}
