// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { DashboardView, DashboardViewAdapter } from "views/dashboard_view.slint";
export { DashboardView, DashboardViewAdapter }

import { MailView, MailViewAdapter, MailBoxViewAdapter } from "views/mail_view.slint";
export { MailView, MailViewAdapter, MailBoxViewAdapter }

import { MainView, MainViewAdapter } from "views/main_view.slint";
export { MainView, MainViewAdapter }