// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0


struct NotExportedStruct0  { a: int }
struct NotExportedStruct1  { b: int, c: NotExportedStruct0 }
struct NotExportedStruct2  { z: int }

export enum ExportEnum { Hello, Bonjour }

export struct ExportedStruct  { d: int, e: NotExportedStruct0 }

export component UseStruct inherits Rectangle {
    in-out property<ExportedStruct> exp;
    in-out property<NotExportedStruct1> nexp;
    in-out property<[NotExportedStruct2]> arr;
}
