// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Slider, GroupBox, HorizontalBox, VerticalBox } from "std-widgets.slint";

export component MainWindow inherits Window {
    in property <image> texture <=> image.source;
    out property <int> texture-width: image.width / 1phx;
    out property <int> texture-height: image.height / 1phx;
    out property <float> amplitude <=> amplitude.value;
    out property <float> pitch: 0.15;
    out property <float> yaw: 0.5;
    title: "Slint Plotter Integration Example";
    preferred-width: 999px;
    preferred-height: 720px;
    VerticalBox {
        Text {
            font-size: 20px;
            text: "2D Gaussian Probability Density Function";
            horizontal-alignment: center;
        }

        HorizontalBox {
            image := Image {
                touch := TouchArea {
                    property <float> starting-drag-pitch;
                    property <float> starting-drag-yaw;
                    pointer-event(event) => {
                        if (event.kind == PointerEventKind.down && event.button == PointerEventButton.left) {
                            self.starting-drag-pitch = root.pitch;
                            self.starting-drag-yaw = root.yaw;
                        }
                    }
                    moved => {
                        if (self.enabled && self.pressed) {
                            root.pitch = self.starting-drag-pitch + (touch.mouse-y - touch.pressed-y) / self.height * 3.14;
                            root.yaw = self.starting-drag-yaw - (touch.mouse-x - touch.pressed-x) / self.width * 3.14;
                        }
                    }
                    mouse-cursor: self.pressed ? MouseCursor.grabbing : MouseCursor.grab;
                }
            }

            VerticalBox {
                amplitude := Slider {
                    orientation: Orientation.vertical;
                    transform-rotation: -180deg;
                    minimum: 0;
                    maximum: 1;
                    value: 0.5;
                }

                Text {
                    text: "Amplitude";
                    font-weight: 600;
                    vertical-alignment: center;
                }
            }
        }
    }
}
