// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { CheckBoxInterface } from "../common/std-widget-interfaces.slint";

export component CheckBox implements CheckBoxInterface inherits NativeCheckBox {
    accessible-enabled: root.enabled;
    accessible-checkable: true;
    accessible-checked <=> root.checked;
    accessible-label <=> root.text;
    accessible-role: checkbox;
    accessible-action-default => {
        if (root.enabled) {
           root.checked = !root.checked;
           root.toggled();
        }
    }
}
