// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.2 OR LicenseRef-Slint-commercial

import { VerticalBox } from "./layouts.slint";
import { Button } from "./button.slint";
import { Palette } from "./std-widgets-impl.slint";

import { Date, DatePickerBase } from "../common/datepicker_base.slint";
export { Date } 

export component DatePicker {
    in property <string> title: "Select date";
    in property <string> cancel-text: "Cancel";
    in property <string> ok-text: "Ok";
    in property <Date> date <=> base.date;

    property <brush> state: Palette.color-scheme == ColorScheme.dark ? #ffffff : #000000;
    property <brush> state-secondary: Palette.color-scheme == ColorScheme.dark ? #000000 : #ffffff;

    callback canceled();
    callback accepted(/* current-date */ Date);

    min-width: content-layer.min-width;
    min-height: content-layer.min-height;

    background-layer := Rectangle {
        border-radius: 8px;
        background: Palette.control-background;
    }

    content-layer := VerticalBox {
        spacing: 8px;

        Text {
            text: root.title;
            horizontal-alignment: left;
            overflow: elide;
            color: Palette.foreground;
        }
   
        base := DatePickerBase {           
            style: {
                  calendar-style: {
                      delegate-style: {
                          font-size: 14px,
                          font-weight: 500,
                          foreground: Palette.foreground,
                          state-brush: root.state,
                          background-selected: Palette.accent-background,
                          foreground-selected: Palette.accent-foreground,
                          state-brush-selected: root.state-secondary,
                          border-color-today: Palette.accent-background,
                          foreground-today: Palette.accent-background,
                          state-brush-today: root.state,
                      }
                  }  
            };
        }

        HorizontalLayout {
            spacing: 8px;
        
            Rectangle { }

            Button {
                text: root.cancel-text;

                clicked => {
                    root.canceled();
                }
            }

            Button {
                text: root.ok-text;
                enabled: base.ok-enabled();

                clicked => {
                    root.accepted(base.get-current-date());
                }
            }
        }
    }
}
