// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.2 OR LicenseRef-Slint-commercial

export component GroupBox {
    in property title <=> native.title;
    in property enabled <=> native.enabled;

    native := NativeGroupBox {
        GridLayout {
            padding-left: native.native-padding-left;
            padding-right: native.native-padding-right;
            padding-top: native.native-padding-top;
            padding-bottom: native.native-padding-bottom;

            @children
        }
    }
}