// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import {
    ProgressIndicatorInterface,
} from "../common/std-widget-interfaces.slint";

export component ProgressIndicator implements ProgressIndicatorInterface inherits NativeProgressIndicator {
    accessible-role: progress-indicator;
    accessible-value: !root.indeterminate ? root.progress : "";
    accessible-value-minimum: 0.0;
    accessible-value-maximum: 1.0;
}
