// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.2 OR LicenseRef-Slint-commercial

export component SpinBox inherits NativeSpinBox {
    value: root.minimum;
    accessible-role: spinbox;
    accessible-value: root.value;
    accessible-value-minimum: root.minimum;
    accessible-value-maximum: root.maximum;
    accessible-value-step: (root.maximum - root.minimum) / 100;

    accessible-action-set-value(v) => { if v.is-float() {update-value(v.to-float());} }
    accessible-action-increment => { update-value(root.value + 1); }
    accessible-action-decrement => { update-value(root.value - 1); }

    function update-value(value: int) {
        if (value >= root.minimum && value <= root.maximum) {
            root.value = value;
            root.edited(value);
        }
    }
}