// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

export global Icons {
    out property <image> arrow-up: @image-url("assets/arrow-up.svg");
    out property <image> arrow-left: @image-url("assets/arrow-left.svg");
    out property <image> arrow-right: @image-url("assets/arrow-right.svg");
    out property <image> chevron-left: @image-url("assets/chevron-left.svg");
    out property <image> arrow-circle-o-left: @image-url("assets/arrow-circle-o-left.svg");
    out property <image> globe: @image-url("assets/globe.svg");
}