export component Demo inherits Window {
    width: 240px;
    height: 72px;
    background: transparent;
    Rectangle {
        background: @linear-gradient(90deg, #2F80ED 0%, #9B51E0 100%);
        border-width: 1px;
        border-color: #1D4ED8;
        border-radius: 12px;
    }
    Text {
        x: 0px;
        y: 0px;
        width: 240px;
        height: 72px;
        color: #FFFFFF;
        text: "Slint";
        font-family: "Inter";
        font-size: 20px;
        font-weight: 400;
        horizontal-alignment: center;
        vertical-alignment: center;
    }
}
