// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { DemoPalette } from "../common.slint";
import { MiniPopup } from "./MiniPopup.slint";
import { ShadowBox } from "ShadowBox.slint";

export component ComboBox {
    in property <[string]> choices;
    in-out property <int> current-index;
    in-out property <string> label;
    property <length> margin: 13px;

    height: 108px;

    ShadowBox { }

    label := Text {
        text <=> root.label;
        color: DemoPalette.text-foreground-color;
        font-size: 16px;
        x: margin;
        y: self.x;
    }

    Rectangle {
        y: parent.height - self.height - margin;
        height: 48px;
        width: parent.width - margin * 2;
        border-radius: 10px;
        border-width: 2px;
        border-color: #CAD5E2;

        Text {
            vertical-alignment: center;
            horizontal-alignment: left;
            text: root.choices[current-index];
            color: DemoPalette.text-foreground-color;
            font-size: 16px;
            x: 12px;
        }

        Image {
            source: @image-url("../images/mcu/combo-arrow.svg");
            x: parent.width - self.width - margin;
        }
    }

    TouchArea {
        pointer-event(ev) => {
            if (ev.kind == PointerEventKind.up) {
                popup.show()
            }
        }

        width: 100%;
        height: 100%;
    }

    popup := MiniPopup {

        frame := Rectangle {
            width: 192px;
            height: 174px;
            border-radius: 14px;

            Image {
                y: current-index == 0 ? 1px : current-index == 1 ? (parent.height - self.height) / 2 : parent.height - self.height - 1px;
                source: @image-url("../images/mcu/combo-active-background.png");
            }

            VerticalLayout {
                for choice[index] in root.choices: Rectangle {
                    border-top-left-radius: index == 0 ? frame.border-radius : 0;
                    border-top-right-radius: index == 0 ? frame.border-radius : 0;
                    border-bottom-left-radius: index == root.choices.length - 1 ? frame.border-radius : 0;
                    border-bottom-right-radius: index == root.choices.length - 1 ? frame.border-radius : 0;
                    background: index == root.current-index ? transparent : white;
                    height: parent.height / 3;
                    width: 100%;
                    Text {
                        x: 12px;
                        font-size: 16px;
                        text: choice;
                        color: index == root.current-index ? white : DemoPalette.text-foreground-color;
                    }

                    Image {
                        x: parent.width - self.width - 12px;
                        width: 20px;
                        source: @image-url("../images/mcu/tick-combo.svg");
                    }

                    TouchArea {
                        pointer-event(ev) => {
                            if (ev.kind == PointerEventKind.down) {
                                root.current-index = index;

                            }
                        }
                        clicked => {
                            popup.close();
                        }
                    }
                }
            }

            for choice[index] in root.choices.length - 1: Rectangle {
                background: #E2E8F0;
                height: 1px;
                width: 100%;
                y: (parent.height / 3) * (1 + index);
            }
            Rectangle {
                border-radius: frame.border-radius;
                border-width: 3px;
                border-color: #E2E8F0;
            }
        }
    }
}
