// Copyright © Klarälvdalens Datakonsult AB, a KDAB Group company, info@kdab.com, author David Faure <david.faure@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component X inherits Rectangle {

    flex := FlexBoxLayout {
        alignment: center;
        align-content: stretch;
        align-items: stretch;
        gap: 10px;
//      > <error{Use spacing instead of gap}
        row-gap: 5px;
//      >     <error{Use spacing-vertical instead of row-gap}
        column-gap: 8px;
//      >        <error{Use spacing-horizontal instead of column-gap}
        justify-content: center;
//      >             <error{Use alignment instead of justify-content}
//                       >    <^error{Unknown unqualified identifier 'center'}
    }
}
