// Code generated by Slint. DO NOT EDIT.

package ui

import (
	"fmt"
	"path/filepath"
	"runtime"
	"sync"

	slint "github.com/slint-ui/slint/api/go/slint"
)

var generatedSource = "export global Logic {\n    pure callback make-greeting(string) -> string;\n}\n\nexport component AppWindow inherits Window {\n    in-out property <string> name: \"World\";\n\n    title: \"Slint + Go\";\n    width: 360px;\n    height: 140px;\n\n    Text {\n        text: Logic.make-greeting(root.name);\n        horizontal-alignment: center;\n        vertical-alignment: center;\n    }\n}\n"

var generatedSourcePathRelative = "../app.slint"

var generatedCompilationOnce sync.Once
var generatedCompilation *slint.CompilationResult
var generatedCompilationErr error

func generatedSourcePath() string {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return generatedSourcePathRelative
	}
	return filepath.Clean(filepath.Join(filepath.Dir(file), generatedSourcePathRelative))
}

func generatedCompilationResult() (*slint.CompilationResult, error) {
	generatedCompilationOnce.Do(func() {
		generatedCompilation, generatedCompilationErr = slint.CompileSource(generatedSourcePath(), generatedSource)
	})
	return generatedCompilation, generatedCompilationErr
}

func generatedComponentDefinition(name string) (*slint.ComponentDefinition, error) {
	result, err := generatedCompilationResult()
	if err != nil {
		return nil, err
	}
	definition := result.Component(name)
	if definition == nil {
		return nil, fmt.Errorf("slint: component %q not found", name)
	}
	return definition, nil
}

type AppWindow struct {
	inner *slint.ComponentInstance
}

func NewAppWindow() (*AppWindow, error) {
	definition, err := generatedComponentDefinition("AppWindow")
	if err != nil {
		return nil, err
	}
	inner, err := definition.Create()
	if err != nil {
		return nil, err
	}
	return &AppWindow{inner: inner}, nil
}

func (c *AppWindow) Inner() *slint.ComponentInstance { return c.inner }

func (c *AppWindow) Show() error { return c.inner.Show() }

func (c *AppWindow) Hide() error { return c.inner.Hide() }

func (c *AppWindow) Run() error { return c.inner.Run() }

func (c *AppWindow) GetName() (string, error) {
	value, err := c.inner.GetProperty("name")
	if err != nil {
		var zero string
		return zero, err
	}
	return value.String()
}

func (c *AppWindow) SetName(value string) error {
	return c.inner.SetProperty("name", slint.StringValue(value))
}

type AppWindowLogicGlobal struct {
	inner *slint.ComponentInstance
}

func (c *AppWindow) Logic() *AppWindowLogicGlobal {
	return &AppWindowLogicGlobal{inner: c.inner}
}

func (c *AppWindowLogicGlobal) OnMakeGreeting(handler func(arg_0 string) string) error {
	return c.inner.SetGlobalCallback(
		"Logic",
		"make-greeting",
		func(args []slint.Value) slint.Value {
			convertedArg0, err := func() (string, error) {
				return args[0].String()
			}()
			if err != nil {
				panic(err)
			}
			return slint.StringValue(handler(convertedArg0))
		},
	)
}

func (c *AppWindowLogicGlobal) InvokeMakeGreeting(arg_0 string) (string, error) {
	value, err := c.inner.InvokeGlobal("Logic", "make-greeting", slint.StringValue(arg_0))
	if err != nil {
		var zero string
		return zero, err
	}
	return value.String()
}

