// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

// cSpell: ignore Heade

import { Button, ComboBox, HorizontalBox, ListView, ScrollView, Palette, VerticalBox } from "std-widgets.slint";
import { Diagnostics, DiagnosticsOverlay } from "diagnostics-overlay.slint";
import { Resizer } from "resizer.slint";

enum SelectionKind {
    none,
    select_at,
    select_up_or_down,
}

export struct Selection {
    x: length,
    y: length,
    width: length,
    height: length,
    border-color: color,
}

export component DrawArea {
    in property <[Diagnostics]> diagnostics;
    in property <[Selection]> selections;
    in property <component-factory> preview-area;
    in property <bool> design-mode;

    out property <bool> preview-visible: i-preview-area-container.has-component && !diagnostics.diagnostics-open;

    out property <length> preview-area-position-x: i-preview-area-container.absolute-position.x;
    out property <length> preview-area-position-y: i-preview-area-container.absolute-position.y;
    out property <length> preview-area-width: preview-visible ? i-preview-area-container.width : 0px;
    out property <length> preview-area-height: preview-visible ? i-preview-area-container.height : 0px;

    callback select-at(/* x */ length, /* y */ length, /* enter_component? */ bool);
    callback select-behind(/* x */ length, /* y */ length, /* enter_component? */ bool, /* reverse */ bool);
    callback show-document(/* url */ string, /* line */ int, /* column */ int);
    callback unselect();

    preferred-height: max(i-preview-area-container.preferred-height, i-preview-area-container.min-height) + 2 * i-scroll-view.border;
    preferred-width: max(i-preview-area-container.preferred-width, i-preview-area-container.min-width) + 2 * i-scroll-view.border;

    i-scroll-view := ScrollView {
        out property <length> border: 60px;

        viewport-width: i-drawing-rect.width;
        viewport-height: i-drawing-rect.height;

        i-drawing-rect := Rectangle {
            background: Palette.alternate-background;

            width: max(i-scroll-view.visible-width, i-resizer.width + i-scroll-view.border);
            height: max(i-scroll-view.visible-height, i-resizer.height + i-scroll-view.border);

            unselect-area := TouchArea {
                clicked => { root.unselect(); }
                mouse-cursor: crosshair;
                enabled <=> root.design-mode;
            }

            i-content-border := Rectangle {
                x: i-resizer.x + (i-resizer.width - self.width) / 2;
                y: i-resizer.y + (i-resizer.height - self.height) / 2;
                width: i-resizer.width + 2 * self.border-width;
                height: i-resizer.height + 2 * self.border-width;
                border-width: 1px;
                border-color: Palette.border;
            }

            i-resizer := Resizer {
                is-resizable <=> i-preview-area-container.is-resizable;

                resize(w, h) => {
                    i-preview-area-container.width = clamp(w, i-preview-area-container.min-width, i-preview-area-container.max-width);
                    i-preview-area-container.height = clamp(h, i-preview-area-container.min-height, i-preview-area-container.max-height);
                }

                width: i-preview-area-container.width;
                height: i-preview-area-container.height;


                // Also make a condition that abuses the fact that the init callback
                // is called every time the condition is dirty, to make sure that the size
                // is within the bounds.
                // Querty the preview-area to make sure this is evaluated when it changes
                if i-preview-area-container.has-component && root.preview-area == i-preview-area-container.component-factory : Rectangle {
                    init => {
                        i-preview-area-container.width = clamp(i-preview-area-container.width, i-preview-area-container.min-width, i-preview-area-container.max-width);
                        i-preview-area-container.height = clamp(i-preview-area-container.height, i-preview-area-container.min-height, i-preview-area-container.max-height);
                    }
                }

                i-preview-area-container := ComponentContainer {

                    property <bool> is-resizable: (self.min-width != self.max-width && self.min-height != self.max-height) && self.has-component;

                    component-factory <=> root.preview-area;

                    // The width and the height can't depend on the layout info of the inner item otherwise this would
                    // cause a recursion if this happens (#3989)
                    // Instead, we use a init function to initialize
                    width: 0px;
                    height: 0px;
                    init => {
                        self.width = max(self.preferred-width, self.min-width);
                        self.height = max(self.preferred-height, self.min-height);
                    }
                }

                i-selection-area := TouchArea {
                    private property <length> selection-x: 0px;
                    private property <length> selection-y: 0px;
                    private property <SelectionKind> selection-kind: SelectionKind.none;

                    clicked => {
                        self.selection-x = self.pressed-x;
                        self.selection-y = self.pressed-y;
                        self.selection-kind = SelectionKind.select-at;
                    }
                    double-clicked => {
                        self.selection-x = self.pressed-x;
                        self.selection-y = self.pressed-y;
                        self.selection-kind = SelectionKind.select-up-or-down;
                    }

                    pointer-event(event) => {
                        // This needs to fire AFTER clicked and double-clicked to work :-/
                        if (event.kind == PointerEventKind.up) {
                            if (self.selection-kind == SelectionKind.select_up_or_down) {
                                root.select_behind(self.selection-x, self.selection-y, event.modifiers.control, event.modifiers.shift);
                            } else if (self.selection-kind == SelectionKind.select-at) {
                                root.select-at(self.selection-x, self.selection-y, event.modifiers.control);
                            }
                        }
                        self.selection-kind = SelectionKind.none;
                    }
                    mouse-cursor: crosshair;
                    enabled <=> root.design-mode;
                }

                i-selection-display-area := Rectangle {
                    for s in root.selections: Rectangle {
                        x: s.x;
                        y: s.y;
                        width: s.width;
                        height: s.height;
                        border-color: s.border-color;
                        border-width: 1px;
                    }
                }
            }

            // Diagnostics overlay:
            diagnostics := DiagnosticsOverlay {
                width: 100%;
                height: 100%;
                diagnostics <=> root.diagnostics;
                show-document(url, line, column) => { root.show-document(url, line, column); }
            }
        }
    }
}
