// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { Api, BrushKind, GradientStop, PreviewData, PropertyValueTable } from "./api.slint";

export enum WidgetMode { edit, preview, color-stop }

// Color and Brush properties are related, but while a <brush> can be a color,
// a <color> property cannot be a brush. This property type is used to ensure
// <color> properties do not show the more complex brush editor.
export enum BrushPropertyType {
    color,
    brush,
}

export enum BrushMode {
    color,
    linear,
    radial,
    svg-color,
    code,
}

export global TableData {
    callback populate-table(property-group-id: string, preview-data: PreviewData);
    out property <string> property-group-id;
    out property <PreviewData> preview-data;
    out property <PropertyValueTable> current-table;

    populate-table(property-group-id, preview-data) => {
        self.property-group-id = property-group-id;
        self.preview-data = preview-data;
        self.current-table = Api.get-property-value-table(property-group-id, preview-data.name);
    }
}
