// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { VerticalBox, ScrollView } from "std-widgets.slint";
import { ListHead } from "list-head.slint";

export component SideBarElement {
    in property <string> name;

    VerticalLayout {
        spacing: 10px;

        Text {
            text: root.name;
            horizontal-alignment: center;
            font-size: 1.4rem;
            font-weight: 800;
        }

        scroll-area := ScrollView {
            VerticalLayout {
                spacing: 10px;

                @children
            }
        }
    }
}

export component SideBar {
    in property <bool> show-side-bar;
    in property <length> default-width;

    private property <length> side-bar-element-spacing: 10px;

    VerticalLayout {
        spacing: root.side-bar-element-spacing;

        @children
    }

    states [
        visible when !self.show-side-bar: {
            width: 0px;
        }
        hidden when self.show-side-bar: {
            width: self.default-width;
        }
    ]
}
