# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

name: Visual Editor overlap experiment

on:
  pull_request:
    branches: [master, "feature/*", "pre-release/*"]
  workflow_dispatch:
  merge_group:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
    CARGO_INCREMENTAL: false
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    ci:
        permissions:
            contents: read
        uses: ./.github/workflows/ci.yaml
        with:
            full: false
            changes: '["visual_editor"]'
        secrets: inherit
