# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
    branches: [master, "feature/*"]
  push:
    branches: [master, "feature/*"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
    format_lint_typecheck:
        runs-on: ubuntu-24.04
        env:
            CARGO_INCREMENTAL: false
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-rust
              with:
                  toolchain: nightly
                  components: rustfmt
                  target: aarch64-linux-android
            - uses: jdx/mise-action@v2
              with:
                  install: false
            - name: Install helper tools (needed for clang-format)
              run: mise use -g ninja
            - name: Install tools
              run: mise install
            - name: Run fixes
              run: mise run --force --jobs=1 'ci:autofix:fix:*:all'
            - name: Suggest format changes
              uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
            - name: Run lints
              run: mise run --force 'ci:autofix:lint:*:all'
