# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

name: Visual Editor Linux package

on:
  workflow_dispatch:
    inputs:
      save_if:
        description: "Condition to save the cache"
        required: false
        type: boolean
        default: true

  pull_request:
    branches:
      - visual-editor

permissions:
  contents: read

env:
  SLINT_BUILD_NUMBER: ${{ github.run_number }}

jobs:
  flatpak:
    name: Build flatpak
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      CARGO_PROFILE: package-release
      FLATPAK_CARGO_GENERATOR_URL: https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/737c0085912f9f7dabf9341d4608e2a77a51a73a/cargo/flatpak-cargo-generator.py
    steps:
      - uses: actions/checkout@v6

      - name: Download flatpak helper script + dependencies
        run: |
          python3 -m pip install aiohttp tomlkit
          curl -o scripts/flatpak-cargo-generator.py \
                  ${FLATPAK_CARGO_GENERATOR_URL}
          chmod +x scripts/flatpak-cargo-generator.py

      # cache the build
      - uses: ./.github/actions/setup-rust
        with:
          key: visual-editor-windows-msix
          save_if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository || inputs.save_if }}

      - name: Install Linux x86_64 Rust target
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Install flatpak tools
        run: |
          sudo apt-get install -y flatpak flatpak-builder
          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Build flatpak
        run: scripts/build_linux_flatpak.bash

      - name: Upload flatpak artifact
        uses: actions/upload-artifact@v7
        with:
          name: slint-visual-editor-linux-flatpak
          path: |
            tools/lsp/slint-visual-editor_0.17.1.flatpak
            slint-visual-editor-self-signed.cer
          if-no-files-found: error
