// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component A  {
    ContextMenu {
        show => {
//      ^error{'show' is not a callback in ContextMenu}
            debug("hello");
        }

        MenuItem {
        }

        property <int> entries: 45;
//      ^error{Cannot re-define internal property 'entries'}
        property <int> sub-menu: 45;
//      ^error{Cannot re-define internal property 'sub-menu'}
        property <string> activated: "me";
//      ^error{Cannot re-define internal property 'activated'}

        property <string> xyz: "me";

    }
}

