// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { ListView  } from "std-widgets.slint";

Foo := Rectangle {
    ListView {
        @children
//      ^error{A ListView can just have a single 'for' as children. Anything else is not supported}
    }
}

export Bar := Rectangle {
    Foo { Text {} }
    ListView {
        Text {}
//      ^error{A ListView can just have a single 'for' as children. Anything else is not supported}
    }
    ListView {
        Text { }
//      ^error{A ListView can just have a single 'for' as children. Anything else is not supported}
        for x in 2: Rectangle {}
        Text { }
//      ^error{A ListView can just have a single 'for' as children. Anything else is not supported}
        for x in 2: Rectangle {}
//      ^error{A ListView can just have a single 'for' as children. Anything else is not supported}
    }

    ListView { for x in 2: Rectangle {} }
    ListView {
        for x in 2: Rectangle {}
        for x in 2: Rectangle {}
//      ^error{A ListView can just have a single 'for' as children. Anything else is not supported}
    }
}
