// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

component MyPopup inherits PopupWindow {}

component MyPopup2 inherits MyPopup {}

export component TopLevel inherits MyPopup2 {
//                                 ^error{PopupWindow cannot be the top level}
    if true : MyPopup2 {}
//            ^error{PopupWindow cannot be directly repeated or conditional}
}
