// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { RadioGroup } from "std-widgets.slint";

component Inner {
    RadioGroup {
        @children
//      >       <error{The @children placeholder is not allowed as a child of 'RadioGroup'}
    }
}

component Root inherits RadioGroup {
    @children
}

export component Test inherits Window {
    Inner {
        RadioButton { text: "a"; }
    }
    Root {
        RadioButton { text: "b"; }
    }
}
