// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

//config:generate_all_exported_windows

export component A inherits SystemTray {
    if false : Menu {}
//             >   <error{SystemTray's Menu cannot be in a conditional or repeated element}
}

export component B inherits SystemTray {
    for _ in [1,2,3] : Menu {}
//                     >   <error{SystemTray's Menu cannot be in a conditional or repeated element}
}

export component C inherits SystemTray {
    Menu {
//  >   <note{First Menu defined here}
        MenuItem { title: "ok"; }
    }
    Menu {
//  >   <error{Only one Menu is allowed in a SystemTray}
        MenuItem { title: "another"; }
    }
}
