// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { TabWidget } from "std-widgets.slint";

component Inner {
    TabWidget {
        @children
//      >       <error{The @children placeholder is not allowed as a child of 'TabWidget'}
    }
}

component Root inherits TabWidget {
    @children
}

export component Test inherits Window {
    Inner {
        Tab { title: "a"; }
    }
    Root {
        Tab { title: "b"; }
    }
}
