// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

import { TabWidget  } from "std-widgets.slint";
export Test1 := Rectangle {
    TabWidget {
        Rectangle {}
//      ^error{Rectangle is not allowed within TabWidget. Only Tab are valid children}
        Tab {
            Tab {}
//          ^error{Tab can only be within a TabWidget element}
        }
    }

    Tab {}
//  ^error{Tab can only be within a TabWidget element}
}
