// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { TabWidget  } from "std-widgets.slint";

export Test2 := Rectangle {
    TabWidget {
        Tab {
            visible: false;
//                   ^error{The property 'visible' cannot be set for Tabs inside a TabWidget}
            Rectangle { }
        }
        f := Tab {
            height: 50%;
//                  ^error{The property 'height' cannot be set for Tabs inside a TabWidget}
        }
        Tab {
            Rectangle { }
            visible <=> f.visible;
//          ^error{The property 'visible' cannot be set for Tabs inside a TabWidget}
        }

        if (true) : Tab {
//                  ^error{dynamic tabs \('if' or 'for'\) are currently not supported}
            title: "hello";
        }
    }
}
