// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component Test inherits Window {
    Rectangle {
        ToolTip {
            text: "Hello";
            x: 10px;
//          ^error{Unknown property x in ToolTip}
            y: 20px;
//          ^error{Unknown property y in ToolTip}
            width: 30px;
//          >   <error{Unknown property width in ToolTip}
            height: 40px;
//          >    <error{Unknown property height in ToolTip}
        }
    }
}
