// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// Dynamic z in a repeater is not supported.

export component Foo inherits Rectangle {
    Rectangle {
        Rectangle { z: root.width > 10px ? 5 : 0; }
        for dyn_z in [5, 40, 23] : Rectangle {
            z: dyn_z;
//             >    <error{'z' in a repeated element must be a constant}
        }
    }
}
