// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Community OR LicenseRef-Slint-commercial

import { Slider } from "std-widgets.slint";

export component TestCase inherits Window {
    width: 64px;
    height: 64px;
    background: lightyellow;
    Image {
        width: 100%;
        height: 100%;
        source: @image-url("border-image-rect.png", nine-slice(5  5 15 5));
        VerticalLayout {
            padding: 5px;
            Image {
                // The border is bigger than the image
                source: @image-url("border-image-rect.png", nine-slice(50 2));
            }
            Image {
                source: @image-url("border-image-rect.png", nine-slice(1 0));
            }
        }
    }
}

