// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

TestCase := Window {
    width: 64px;
    height: 64px;
    forward-focus: i-text-input;
    VerticalLayout {
        i-text-input := TextInput {
            text: "Hello Everyone";
            wrap: word-wrap;
            color: green;
            font-size: 10px;
            cursor-position-byte-offset: 7;
            anchor-position-byte-offset: 7;
        }
        TextInput {
            text: "Hello";
            color: #abcd;
            opacity: 0.9;
            font-size: 10px;
            horizontal-alignment: center;
            cursor-position-byte-offset: 2;
            anchor-position-byte-offset: 4;
        }
        TextInput {
            text: "Everyone";
            font-size: 10px;
            width: 100%;
            horizontal-alignment: right;
            cursor-position-byte-offset: 5;
            anchor-position-byte-offset: 7;
        }
    }
}
