// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

export component TestCase inherits Window {
    width: 64px;
    height: 64px;

    Text {
        text: "No wrap, single line";
        y: 0px;
        width: 100%;
        overflow: elide;
        font-size: 9px;
        color: red;
    }

    Text {
        text: "No wrap, first line\nand also second line";
        y: 14px;
        width: 100%;
        overflow: elide;
        font-size: 9px;
        color: green;
        horizontal-alignment: center;
    }

    Text {
        text: "Wrap and elide multiple lines of text";
        y: 40px;
        width: 100%;
        height: parent.height - self.y;
        wrap: word-wrap;
        overflow: elide;
        font-size: 9px;
        color: blue;
        horizontal-alignment: right;
    }
}
