// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { ButtonInterface } from "../common/std-widget-interfaces.slint";
import { Pressable } from "pressable.slint";

export component Button {
    implement ButtonInterface <=> self;

    in property <string> text;
    in property <bool> enabled: true;
    in property <bool> checkable: false;
    in-out property <bool> checked: false;

    out property <bool> has-focus: pressable.has-focus;
    out property <bool> has-hover: pressable.has-hover;
    out property <bool> pressed: pressable.pressed;

    out property <length> pressed-x: pressable.pressed-x;
    out property <length> pressed-y: pressable.pressed-y;

    callback clicked;

    preferred-width: 100%;
    preferred-height: 100%;
    min-width: pressable.min-width;
    min-height: pressable.min-height;
    forward-focus: pressable;

    public function activate() {
        if (root.enabled) {
            if (root.checkable) {
                root.checked = !root.checked;
            }
            root.clicked();
        }
    }

    pressable := Pressable {
        enabled: root.enabled;
        clicked => { root.activate(); }

        @children
    }
}
