// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { SwitchInterface } from "../common/std-widget-interfaces.slint";

import { Pressable } from "pressable.slint";

export component Switch {
    implement SwitchInterface <=> self;

    in property <string> text;
    in property <bool> enabled: true;
    in-out property <bool> checked: false;

    out property <bool> has-focus: pressable.has-focus;
    out property <bool> has-hover: pressable.has-hover;
    out property <bool> pressed: pressable.pressed;

    callback toggled;

    preferred-width: 100%;
    preferred-height: 100%;
    min-width: pressable.min-width;
    min-height: pressable.min-height;
    forward-focus: pressable;

    public function toggle() {
        if (root.enabled) {
            root.checked = !root.checked;
            root.toggled();
        }
    }

    pressable := Pressable {
        enabled: root.enabled;
        clicked => { root.toggle(); }

        @children
    }
}
